Repository langfuse/langfuse, pull requests merged in 2024-12, with the labels that each got.

#4498 chore: apply v3 defaults to environment variables
  .env.dev-azure.example
  .env.dev.example
  .env.dev.legacy.example
  .env.local.example
  .env.prod.example
  .github/workflows/pipeline.yml
  .github/workflows/snyk.yml
  .gitignore
  docker-compose.build.yml
  docker-compose.v3preview.yml
  docker-compose.yml
  ee/src/env.ts
  packages/shared/src/env.ts
  packages/shared/src/index.ts
  packages/shared/src/server/ingestion/legacy/index.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/redis/cloudUsageMeteringQueue.ts
  packages/shared/src/server/repositories/clickhouse.ts
  web/Dockerfile
  web/src/env.mjs
  worker/Dockerfile
  worker/src/env.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:XL

#4487 fix: increase attempts for evals
  worker/src/ee/experiments/experimentService.ts
  worker/src/features/evaluation/evalService.ts
Labels: size:XS

#4511 chore: move batch export s3 env variable names into new naming pattern
  .env.dev-azure.example
  .env.dev.example
  .env.dev.legacy.example
  .env.prod.example
  .github/workflows/pipeline.yml
  web/src/__tests__/generation-exports.servertest.ts
  web/src/env.mjs
  web/src/server/api/routers/generations/exportQuery/index.ts
  worker/src/env.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:L

#4515 fix(ui): overflow of session view on mobile
  web/src/components/session/index.tsx
Labels: ui, size:S

#4516 fix(ui): disallow creation of projects if project name already exists in the org
  web/src/features/projects/server/projectsRouter.ts
Labels: ui, size:S

#4517 build: cancel concurrent PR jobs on new commit
  .github/workflows/pipeline.yml
  .github/workflows/snyk.yml
Labels: size:S

#4512 chore: remove backend cloud version checks
  docker-compose.build.yml
  docker-compose.yml
  web/src/ee/features/evals/server/addDatasetRunItemsToEvalQueue.ts
  web/src/ee/features/experiments/server/router.ts
Labels: lgtm, size:S

#4519 chore: add logging for datasets router
  web/src/features/datasets/server/service.ts
Labels: size:XS

#4520 fix: fix score source public api filter
  web/src/pages/api/public/scores/index.ts
Labels: bug, size:XS

#4521 fix(media): use db upserts instead of prisma
  web/src/pages/api/public/media/index.ts
Labels: size:L

#4522 fix: no need to decode nextjs path variables, causes issues with special characters
  web/src/pages/project/[projectId]/sessions/[sessionId].tsx
  web/src/pages/project/[projectId]/traces/[traceId].tsx
  web/src/pages/project/[projectId]/users/[userId].tsx
Labels: bug, size:XS

#4524 fix(IO-ui): render additional input in pretty view
  web/src/components/trace/IOPreview.tsx
Labels: size:S

#4526 fix(io-ui): padding additional input
  web/src/components/trace/IOPreview.tsx
Labels: size:XS

#4527 fix: on cache schema change, delete cached api keys
  web/src/features/public-api/server/apiAuth.ts
Labels: lgtm, size:XS

#4528 fix: show dataset run if not run item exists yet
  web/src/features/datasets/server/service.ts
Labels: size:XS

#4529 feat: optionally disable csp headers via `LANGFUSE_CSP_DISABLE=true`
  web/next.config.mjs
  web/src/env.mjs
Labels: size:M

#4532 [cherry-pick][2.93.x] feat: optionally disable csp headers via `LANGFUSE_CSP_DISABLE=true`
  web/next.config.mjs
  web/src/env.mjs
Labels: size:M

#4533 chore: add LANGFUSE_CSP_DISABLE to .env.prod.example
  .env.prod.example
Labels: size:XS

#4534 perf: improve scores API query performance
  packages/shared/src/server/queries/clickhouse-sql/clickhouse-filter.ts
  web/src/features/public-api/server/sores.ts
Labels: feat-scores, size:M

#4535 chore: include projectId in event processing error message
  packages/shared/src/server/ingestion/processEventBatch.ts
Labels: size:XS

#4538 perf: improve count query performance for scores public api
  web/src/features/public-api/server/sores.ts
Labels: feat-api, feat-scores, size:M

#4547 fix(media): add wait time before retries
  web/src/pages/api/public/media/index.ts
Labels: size:XS

#4545 fix: remove LANGFUSE_CSP_DISABLE (did not work) and disable csp headers on HF Spaces
  .env.prod.example
  web/next.config.mjs
  web/src/env.mjs
Labels: size:M

#4546 chore: migrate /metrics/daily API route to Clickhouse
  web/src/__tests__/async/daily-metrics-api.servertest.ts
  web/src/features/public-api/server/dailyMetrics.ts
  web/src/features/public-api/server/traces.ts
  web/src/pages/api/public/metrics/daily.ts
Labels: feat-api, size:XL

#4548 feat(ui): add "not found" error page for unknown traces and sessions
  web/src/components/error-page.tsx
  web/src/components/session/index.tsx
  web/src/components/trace/index.tsx
Labels: size:M

#2866 feat(auth): add KeyCloak authentication option
  .env.prod.example
  web/src/ee/features/multi-tenant-sso/types.ts
  web/src/ee/features/multi-tenant-sso/utils.ts
  web/src/env.mjs
  web/src/pages/auth/sign-in.tsx
  web/src/server/auth.ts
Labels: lgtm, size:L

#4549 fix: fix time to first token
  packages/shared/src/server/repositories/observations_converters.ts
  web/jest.config.mjs
  web/src/__tests__/async/daily-metrics-api.servertest.ts
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/__tests__/async/observation-api.servertest.ts
  web/src/__tests__/async/repositories/clickhouse-helpers.ts
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
  web/src/__tests__/async/repositories/score-repository.servertest.ts
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
  web/src/__tests__/async/scores-api.servertest.ts
  web/src/__tests__/async/sessions-api.servertest.ts
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/__tests__/async/traces-ui-table.servertest.ts
  web/src/__tests__/server/api/tables/prompts-ui.servertest.ts
  web/src/__tests__/server/repositories/observation-repository.servertest.ts
Labels: bug, size:L

#4552 chore: refactor tests async
  web/src/__tests__/async/daily-metrics-api.servertest.ts
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/__tests__/async/observation-api.servertest.ts
  web/src/__tests__/async/repositories/clickhouse-helpers.ts
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
  web/src/__tests__/async/repositories/score-repository.servertest.ts
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
  web/src/__tests__/async/scores-api.servertest.ts
  web/src/__tests__/async/sessions-api.servertest.ts
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/__tests__/async/traces-ui-table.servertest.ts
  web/src/__tests__/server/api/tables/prompts-ui.servertest.ts
Labels: size:L

#4554 perf: add a user_id bloom filter
  packages/shared/clickhouse/migrations/clustered/0006_add_user_id_index.down.sql
  packages/shared/clickhouse/migrations/clustered/0006_add_user_id_index.up.sql
  packages/shared/clickhouse/migrations/unclustered/0006_add_user_id_index.down.sql
  packages/shared/clickhouse/migrations/unclustered/0006_add_user_id_index.up.sql
Labels: size:XS

#4558 fix: disable x frame options header on Hugging Face
  web/next.config.mjs
Labels: size:M

#4553 chore: remove public users api
  web/src/pages/api/public/users.ts
Labels: size:L

#4544 chore: double ingestion API rate limits
  web/src/features/public-api/server/RateLimitService.ts
Labels: feat-api, size:XS

#4565 chore: increase timeout for daily metrics query
  web/src/features/public-api/server/dailyMetrics.ts
Labels: size:XS

#4564 fix: convert json strings to json in traces api metadata field
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/server/traces.ts
Labels: bug, size:S

#4569 fix(ui): show scrollbar for scores in column visibility
  web/src/components/table/data-table-column-visibility-filter.tsx
Labels: ui, size:XS

#4568 perf: improve user metrics for large projects
  packages/shared/src/server/repositories/traces.ts
  web/src/__tests__/async/users-ui-table.servertest.ts
  web/src/server/api/routers/users.ts
Labels: size:L

#4570 fix: perform batch trace deletion on clickhouse
  packages/shared/src/server/queues.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/traces.ts
  worker/src/env.ts
  worker/src/queues/traceDelete.ts
Labels: size:M

#4572 fix(cloud): only active evals count towards free plan limit
  web/src/ee/features/evals/pages/evaluators.tsx
Labels: size:S

#4573 chore(ingestion): add back async ingestion processing flag
  docker-compose.yml
  packages/shared/src/env.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
Labels: lgtm, size:S

#4576 chore(cost-tracking): add gpt-4o-2024-11-20 prices
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:S

#4578 fix(media): add self host env vars
  .env.dev-azure.example
  .env.dev.example
  .env.dev.legacy.example
  docker-compose.yml
  web/src/env.mjs
  web/src/pages/api/public/media/index.ts
Labels: size:S

#4581 chore: explicitly mention worker/src/ee
  LICENSE
Labels: size:XS

#4580 chore: add aggregateScores tests
  .github/workflows/pipeline.yml
  web/package.json
  web/src/__tests__/aggregateScores.clienttest.ts
  web/src/features/datasets/server/service.ts
Labels: size:M

#4577 feat(comments): increase content character limit to 3,000
  fern/apis/server/definition/comments.yml
  packages/shared/src/features/comments/types.ts
  web/public/generated/api/openapi.yml
  web/src/__tests__/comments.servertest.ts
Labels: feat-comments, size:M

#4575 feat(url): support AWS S3 signed images in trace/observation preview
  web/src/server/api/routers/utilities.ts
Labels: lgtm, size:L

#4593 fix: return timestamps in API response as ISO strings
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/server/traces.ts
Labels: bug, size:S

#4595 chore: check early whether clickhouse url is configured
  web/entrypoint.sh
Labels: size:XS

#4399 chore: make project deletion asynchronous
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241124115100_add_projects_deleted_at/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/redis/projectDelete.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/features/organizations/components/ProjectOverview.tsx
  web/src/features/organizations/server/organizationRouter.ts
  web/src/features/projects/server/projectsRouter.ts
  web/src/features/rbac/server/membersRouter.ts
  web/src/features/telemetry/index.ts
  web/src/pages/api/public/projects.ts
  web/src/server/api/trpc.ts
  web/src/server/auth.ts
  web/types/next-auth.d.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/queues/projectDelete.ts
Labels: size:L

#4596 chore: add wait time during validation of clickhouse background migra…
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateScoresFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateTracesFromPostgresToClickhouse.ts
Labels: size:L

#4598 feat: adjust trace redirect to uniqueness of trace ids to projects
  packages/shared/src/server/repositories/traces.ts
  web/src/pages/trace/[traceId].tsx
Labels: size:M

#4601 fix: fix front end confirmations to delete traces
  web/src/components/deleteButton.tsx
  web/src/components/trace/index.tsx
Labels: bug, size:S

#4611 fix(experiments): don't create experiment run items for archived dataset items
  web/src/components/trace/IOPreview.tsx
  web/src/ee/features/experiments/server/router.ts
  worker/src/ee/experiments/experimentService.ts
Labels: size:XS

#4602 feat: add ui for background migrations
  web/src/components/VersionLabel.tsx
  web/src/components/layouts/status-badge.tsx
  web/src/features/background-migrations/components/background-migrations.tsx
  web/src/features/background-migrations/components/retry-background-migration.tsx
  web/src/features/background-migrations/server/background-migrations-router.ts
  web/src/pages/background-migrations.tsx
  web/src/server/api/root.ts
Labels: ui, size:L

#4612 chore: drop FK v3 constraints
  packages/shared/prisma/migrations/20241206115829_remove_trace_score_observation_constraints/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/server/repositories/scores.ts
  web/src/ee/features/evals/server/router.ts
Labels: size:M

#4613 feat: set v3 default variables
  .github/workflows/pipeline.yml
  packages/shared/src/env.ts
  web/src/__e2e__/api.servertest.ts
  web/src/env.mjs
  web/src/server/api/routers/scores.ts
  worker/src/env.ts
  worker/src/features/evaluation/evalService.ts
Labels: size:L

#4616 chore: move eval to correct ee directory
  worker/src/__tests__/evalService.test.ts
  worker/src/ee/evaluation/evalService.ts
  worker/src/queues/evalQueue.ts
Labels: size:XS

#3848 feat(comments): add support for comment button on each trace preview in session view
  web/src/__tests__/async/comments-api.servertest.ts
  web/src/components/session/index.tsx
  web/src/features/comments/CommentDrawerButton.tsx
  web/src/features/comments/CommentList.tsx
  web/src/features/comments/validateCommentReferenceObject.ts
  web/src/server/api/routers/comments.ts
Labels: feat-comments, size:L

#4619 feat: increase trace upsert delay
  packages/shared/src/server/redis/traceUpsert.ts
Labels: size:XS

#4615 fix: fix numeric chart for dashboards
  packages/shared/src/server/repositories/scores.ts
Labels: bug, size:XS

#4620 fix: fix traces publishing in V3 without postgres
  web/src/server/api/routers/traces.ts
Labels: bug, size:S

#4618 fix: only read trace and score from prisma if `LANGFUSE_POSTGRES_INGESTION_ENABLED`
  web/src/server/api/routers/scores.ts
Labels: lgtm, size:L

#4628 chore: hide background migrations on cloud and show queued status
  web/src/components/VersionLabel.tsx
  web/src/features/background-migrations/components/background-migrations.tsx
Labels: ui, size:M

#4629 perf: fetch observations using timestamps
  packages/shared/src/server/repositories/observations.ts
  web/src/components/table/use-cases/generations.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/server/api/routers/observations.ts
Labels: size:S

#4624 fix: check postgres negative flag
  pnpm-lock.yaml
  web/src/server/api/routers/scores.ts
  worker/package.json
  worker/src/__tests__/evalService.test.ts
  worker/src/ee/evaluation/evalService.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: bug, size:M

#4621 fix: support reading observations from clickhouse for observations in annotation queue
  packages/shared/src/server/repositories/observations.ts
  web/src/ee/features/annotation-queues/server/annotationQueueItems.ts
  web/src/ee/features/annotation-queues/server/annotationQueues.ts
Labels: bug, size:L

#4630 chore: use s3 region `auto` in docker-compose.yml
  docker-compose.yml
Labels: size:XS

#4636 feat: move session tests to async suite
  web/src/__tests__/async/sessions-api.servertest.ts
  web/src/__tests__/sessions.servertest.ts
Labels: feat-sessions, size:L

#4634 feat: move exports to ch
  packages/shared/src/server/index.ts
  packages/shared/src/server/repositories/index.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/scores_converters.ts
  packages/shared/src/server/repositories/trace-sessions.ts
  packages/shared/src/server/test-utils/clickhouse-helpers.ts
  packages/shared/src/server/test-utils/index.ts
  packages/shared/src/server/test-utils/org-factory.ts
  packages/shared/src/server/test-utils/tracing-factory.ts
  web/src/__tests__/async/comments-api.servertest.ts
  web/src/__tests__/async/daily-metrics-api.servertest.ts
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/__tests__/async/observation-api.servertest.ts
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
  web/src/__tests__/async/repositories/score-repository.servertest.ts
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
  web/src/__tests__/async/scores-api.servertest.ts
  web/src/__tests__/async/sessions-api.servertest.ts
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/__tests__/async/traces-ui-table.servertest.ts
  web/src/__tests__/async/users-ui-table.servertest.ts
  web/src/__tests__/generation-exports.servertest.ts
  web/src/__tests__/server/api/tables/prompts-ui.servertest.ts
  web/src/__tests__/test-utils.ts
  web/src/components/table/use-cases/generations.tsx
  web/src/server/api/routers/generations/exportQuery/index.ts
  web/src/server/api/routers/generations/index.ts
  web/src/server/api/routers/sessions.ts
  worker/src/__tests__/batch-export.test.ts
  worker/src/__tests__/evalService.test.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: feat-sessions, size:XXL

#4638 fix: fix trace bookmarking
  web/src/server/api/routers/traces.ts
Labels: bug, size:M

#4639 fix: fix trace tagging without postgres
  web/src/server/api/routers/traces.ts
Labels: size:S

#4640 fix: default to empty string for csv export in case of null
  packages/shared/src/server/utils/transforms/transformStreamToCsv.ts
Labels: size:XS

#4641 fix: always pull the project_id for generations queries
  packages/shared/src/server/repositories/observations.ts
Labels: bug, size:XS

#4644 fix: allow userId filter on /api/public/observations again
  web/src/__tests__/async/observation-api.servertest.ts
  web/src/features/public-api/server/observations.ts
Labels: bug, size:M

#4648 build: add latest tags to v3 tags
  .github/workflows/pipeline.yml
Labels: size:XS

#4627 fix: fix fern spec for MediaContentType
  fern/apis/server/definition/media.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
Labels: bug, lgtm, size:M

#4643 fix(experiments): ensure experiment runs on all valid inputs
  packages/shared/src/features/experiments/utils.ts
  packages/shared/src/index.ts
  packages/shared/src/utils/stringChecks.ts
  web/src/ee/features/experiments/server/router.ts
  worker/src/ee/experiments/experimentService.ts
Labels: bug, size:M

#4649 fix: always restart all docker services
  docker-compose.yml
Labels: size:XS

#4651 fix(model-form): increase max token limit to 16384
  web/src/components/ModelParameters/index.tsx
Labels: size:XS

#4653 chore: update default docker compose to use `3` docker tag
  docker-compose.yml
Labels: size:XS

#4655 docs: update upgrade guide url in entrypoint
  web/entrypoint.sh
Labels: size:XS

#4666 fix(vertex): at least 1 user message always
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  web/src/ee/features/playground/page/context/index.tsx
Labels: feat-playground, size:M

#4659 fix(experiments): don't require name in experiment creation
  web/src/ee/features/experiments/components/CreateExperimentsForm.tsx
Labels: size:XS

#3859 feat(annotation): optimistic updates on annotation form
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemPage.tsx
  web/src/features/scores/components/AnnotateDrawer.tsx
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/server/api/routers/scores.ts
Labels: feat-scores, size:XL

#4687 fix(playground): Model side menu in playground not scrollable
  web/src/ee/features/playground/page/playground.tsx
Labels: size:XS

#4686 feat(ui): add editable note for each api key
  web/src/features/public-api/components/ApiKeyList.tsx
  web/src/features/public-api/components/CreateApiKeyButton.tsx
  web/src/features/public-api/server/apiKeyRouter.ts
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/features/setup/components/SetupTracingButton.tsx
Labels: ui, size:L

#4694 chore: improve trace export tests
  worker/src/__tests__/batch-export.test.ts
Labels: size:M

#4697 feat: add observations status chart
  packages/shared/src/server/repositories/dashboards.ts
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/pages/project/[projectId]/index.tsx
Labels: feat-dashboard, size:L

#4690 security: upgrade next-auth
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  web/src/server/auth.ts
Labels: dependencies, size:S

#4700 chore: improve naming for observations by level chart
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
Labels: feat-dashboard, size:XS

#4701 fix: use clickhouse for failIfRecentEvent condition in healthcheck
  web/src/pages/api/public/health.ts
Labels: bug, size:M

#4702 security: upgrade next-auth
  ee/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  web/src/server/auth.ts
Labels: dependencies, size:S

#4704 fix: fix level filter on trace upsert queue
  packages/shared/src/server/repositories/traces.ts
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
Labels: bug, size:L

#4707 fix(organizations): block org deletion in case of active projects
  web/src/features/organizations/components/DeleteOrganizationButton.tsx
  web/src/features/organizations/server/organizationRouter.ts
Labels: bug, size:M

#4708 fix: do not fetch dataset run items which are not active
  web/src/__tests__/async/datasets-api.servertest.ts
  web/src/pages/api/public/datasets.ts
Labels: size:L

#4709 chore(evals/experiments): support retries via bullmq; set 2 minute LLM call completion timeouts
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/redis/evalExecutionQueue.ts
  packages/shared/src/server/redis/experimentCreateQueue.ts
  worker/src/ee/evaluation/evalService.ts
  worker/src/ee/experiments/experimentService.ts
  worker/src/features/utilities.ts
  worker/src/queues/evalQueue.ts
  worker/src/queues/experimentQueue.ts
Labels: feat-evals, lgtm, size:M

#4710 fix: fix pagination on public api
  packages/shared/src/features/scores/scoreConfigTypes.ts
  packages/shared/src/features/scores/scoreTypes.ts
  packages/shared/src/utils/zod.ts
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/types/comments.ts
  web/src/features/public-api/types/datasets.ts
  web/src/features/public-api/types/metrics.ts
  web/src/features/public-api/types/models.ts
  web/src/features/public-api/types/observations.ts
  web/src/features/public-api/types/sessions.ts
  web/src/features/public-api/types/traces.ts
Labels: bug, size:L

#4713 feat: in HF Spaces, prompt opening in new tab when running in iframe
  web/public/assets/huggingface-logo.svg
  web/src/components/layouts/layout.tsx
  web/src/pages/auth/hf-spaces.tsx
  web/src/pages/auth/sign-in.tsx
  web/src/pages/auth/sign-up.tsx
Labels: size:L

#4715 fix: rate limit deletions globally to 1 per 3s
  worker/src/app.ts
Labels: size:S

#4718 chore: remove filterlist console log
  web/src/features/public-api/server/filter-builder.ts
Labels: size:XS

#4727 fix(ui): redirect after org/project deletion when using custom base path
  web/src/features/organizations/components/DeleteOrganizationButton.tsx
  web/src/features/projects/components/DeleteProjectButton.tsx
Labels: ui, size:XS

#4729 fix: use correct golang-migrate in build
  web/Dockerfile
  worker/Dockerfile
Labels: bug, size:XS

#4731 feat(ui): new experiment modal to highlight prompt and custom experiments
  web/src/ee/features/experiments/components/CreateExperimentsForm.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: ui, size:XXL

#4685 feat: add posthog integration processing
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/cloudUsageMeteringQueue.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/redis/postHogIntegrationProcessingQueue.ts
  packages/shared/src/server/redis/postHogIntegrationQueue.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  pnpm-lock.yaml
  web/src/features/entitlements/constants/entitlements.ts
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/integrations/posthog.tsx
  web/src/server/api/routers/batchExport.ts
  worker/package.json
  worker/src/app.ts
  worker/src/ee/integrations/posthog/handlePostHogIntegrationProjectJob.ts
  worker/src/ee/integrations/posthog/handlePostHogIntegrationSchedule.ts
  worker/src/env.ts
  worker/src/queues/postHogIntegrationQueue.ts
Labels: size:XL

#4733 fix(annotation): fail postgres upsert, delete silentley while Clickhouse is in lead
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/server/api/routers/scores.ts
Labels: bug, size:L

#4536 feat(cost-tracking): allow additional cost and usage keys
  fern/apis/server/definition/commons.yml
  fern/apis/server/definition/ingestion.yml
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/queries/createGenerationsQuery.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  packages/shared/src/tableDefinitions/mapDashboards.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  web/public/generated/api/openapi.yml
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/token-usage-badge.tsx
  web/src/components/trace/BreakdownToolTip.tsx
  web/src/components/trace/IOPreview.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/components/cards/DashboardCard.tsx
  web/src/features/dashboard/lib/score-analytics-utils.ts
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/public-api/server/dailyMetrics.ts
  web/src/features/public-api/types/observations.ts
  web/src/pages/api/public/traces/[traceId].ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/services/queryBuilder.ts
  worker/src/constants/default-model-prices.json
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-cost-tracking, size:XXL

#4737 chore(annotation): return previous score props in delete method
  web/src/server/api/routers/scores.ts
Labels: size:S

#4738 fix(dashboard-modelUsage): NaN handling on totals
  web/src/features/dashboard/components/ModelUsageChart.tsx
Labels: size:S

#4741 feat(ui): add organizations menu item link for all global pages
  web/src/components/layouts/routes.tsx
Labels: ui, size:XS

#4748 fix(dashboard-modelUsage): none model name handling
  packages/shared/src/server/repositories/observations.ts
  web/src/features/dashboard/components/ModelUsageChart.tsx
Labels: bug, size:S

#4749 docs: update readme
  README.md
Labels: size:M

#4753 chore(cloud): remove posthog metrics cron job
  web/src/pages/api/cron/ingestion-metrics.ts
  web/vercel.json
Labels: size:M

#4751 chore: increase rate limits
  docker-compose.build.yml
  web/src/features/public-api/server/RateLimitService.ts
Labels: size:XS

#4776 chore(ui): order score names alphabetically in dropdowns
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/scores/components/ScoreDetailColumnHelpers.tsx
  web/src/features/scores/hooks/useIndividualScoreColumns.ts
  web/src/features/scores/lib/helpers.ts
  web/src/features/scores/lib/types.ts
Labels: ui, feat-scores, size:M

#4779 chore: add attributes to ingestion queue processing
  worker/src/queues/ingestionQueue.ts
Labels: size:S

#4781 chore: do not add latest, major, and major.minor tags to docker images of `-rc` versions
  .github/workflows/pipeline.yml
Labels: size:S

#4728 feat(auth): add `AUTH_IGNORE_ACCOUNT_FIELDS` to sanitize IDP fields before creating an account
  .env.prod.example
  web/src/env.mjs
  web/src/server/auth.ts
Labels: feat-auth, size:S

#4787 chore: measure lookup hits in ingestion pipeline
  worker/src/services/IngestionService/index.ts
Labels: size:M

#4796 fix: fix time to first token in trace detail view
  packages/shared/src/server/repositories/observations_converters.ts
Labels: size:XS

#4797 fix: fix tests
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
Labels: size:XS

#4798 fix(cloud): remove unnecessary posthog events
  web/src/features/setup/components/SetupTracingButton.tsx
  web/src/pages/_app.tsx
Labels: size:S

#4754 feat(datasets): support charts for scores and resource metrics
  web/src/ee/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/ee/features/experiments/components/CreateExperimentsForm.tsx
  web/src/features/dashboard/components/score-analytics/CategoricalScoreChart.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/dashboard/lib/score-analytics-utils.ts
  web/src/features/datasets/components/DatasetAnalytics.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/datasets/server/service.ts
  web/src/features/scores/adapters/index.ts
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/features/scores/components/ScoreChart.tsx
  web/src/features/scores/components/TimeseriesChart.tsx
  web/src/features/scores/components/multi-select-key-values.tsx
  web/src/features/scores/types.ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: feat-datasets, feat-scores, size:XXL

#4801 chore(ui): move dataset details into popover on runs table
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: ui, size:M

#4804 fix: add latencies to trace exports
  web/src/__tests__/async/dataset-service.servertest.ts
  worker/src/__tests__/batch-export.test.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:S

#4805 fix: fix json parsing of trace / observation i/o
  packages/shared/src/server/repositories/traces_converters.ts
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
  worker/src/__tests__/evalService.test.ts
Labels: bug, size:M

#4807 chore(ui): toggle json editor for text prompts
  web/src/features/prompts/components/NewPromptForm/index.tsx
Labels: ui, size:M

#4808 fix: include time filter into user metrics query
  packages/shared/src/server/repositories/traces.ts
  web/src/__tests__/async/users-ui-table.servertest.ts
  web/src/pages/project/[projectId]/users.tsx
  web/src/server/api/routers/users.ts
Labels: size:M

#4802 feat(models): add UI to add all usage types
  packages/shared/src/observationsTable.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  web/src/components/table/data-table.tsx
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/models.tsx
  web/src/components/trace/BreakdownToolTip.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/useLocalStorage.tsx
  web/src/features/models/components/CloneModelButton.tsx
  web/src/features/models/components/DeleteModelButton.tsx
  web/src/features/models/components/EditModelButton.tsx
  web/src/features/models/components/NewModelForm.tsx
  web/src/features/models/components/PriceBreakdownTooltip.tsx
  web/src/features/models/components/PricePreview.tsx
  web/src/features/models/components/PriceUnitSelector.tsx
  web/src/features/models/components/UpsertModelFormDrawer.tsx
  web/src/features/models/hooks/usePriceUnitMultiplier.ts
  web/src/features/models/utils.ts
  web/src/features/models/validation.ts
  web/src/pages/project/[projectId]/models.tsx
  web/src/pages/project/[projectId]/models/[modelId].tsx
  web/src/pages/project/[projectId]/models/new.tsx
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/models.ts
  web/src/server/api/routers/traces.ts
Labels: ui, size:XXL

#4810 feat(auth): Add AUTH_CUSTOM_CLIENT_AUTH_METHOD to support PKCE code flow
  .env.prod.example
  web/src/env.mjs
  web/src/server/auth.ts
Labels: feat-auth, lgtm, size:S

#4815 feat(cloud): improve open/close state of support chat
  web/src/features/setup/components/SetupPage.tsx
  web/src/features/support-chat/chat.tsx
Labels: ui, size:M, auto-merge

#4812 fix(ui): clarify what applying producation label to a new prompt does
  web/src/features/prompts/components/NewPromptForm/index.tsx
Labels: feat-prompt-management, size:M, auto-merge

#4816 feat(ui): add export status table to project settings
  web/src/components/BatchExportTableButton.tsx
  web/src/components/layouts/status-badge.tsx
  web/src/features/batch-exports/README.md
  web/src/features/batch-exports/components/BatchExportsSettingsPage.tsx
  web/src/features/batch-exports/components/BatchExportsTable.tsx
  web/src/features/batch-exports/server/batchExport.ts
  web/src/features/notifications/SuccessNotification.tsx
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/server/api/root.ts
  web/src/server/api/routers/batchExport.ts
Labels: ui, size:L

#4819 feat(ui): enable the creation of a new LLM connection from the LLM selection dropdown
  web/src/components/ModelParameters/index.tsx
Labels: ui, size:XS, auto-merge

#4818 chore(ui): remove dateRangeFilter on prompt metrics table as no longer necessary on CH
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: ui, size:M, auto-merge

#4821 chore: export core information tables to S3 daily
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/coreDataS3ExportQueue.ts
  packages/shared/src/server/redis/getQueue.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/queues/coreDataS3ExportQueue.ts
Labels: size:L, auto-merge

#4822 feat(ui): switch to github discussions and issues for in-product feedback
  web/src/components/nav-main.tsx
  web/src/features/feedback/component/FeedbackButton.tsx
  web/src/pages/project/[projectId]/index.tsx
Labels: ui, size:L

#4826 chore: clean up error message bullmq endpoint
  web/src/pages/api/admin/bullmq/index.ts
Labels: size:XS, auto-merge

#4831 fix: ensure idemptence of project deletion queue
  worker/src/queues/projectDelete.ts
Labels: size:S, auto-merge

#4841 fix(legacy-ingestion): usageDetails support
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
Labels: size:XS

#4847 fix: support large amount of traces for sessions in session.byid
  web/src/server/api/routers/sessions.ts
Labels: size:S, auto-merge
