Repository langfuse/langfuse, pull requests merged in 2024-11, with the labels that each got.

#3837 feat(ui): add new sidebar and main navigation
  pnpm-lock.yaml
  web/src/components/EnvLabel.tsx
  web/src/components/LangfuseLogo.tsx
  web/src/components/app-sidebar.tsx
  web/src/components/layouts/doc-popup.tsx
  web/src/components/layouts/header.tsx
  web/src/components/layouts/layout.tsx
  web/src/components/layouts/routes.tsx
  web/src/components/layouts/scroll-screen-page.tsx
  web/src/components/nav-main.tsx
  web/src/components/nav-user.tsx
  web/src/components/session/index.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/index.tsx
  web/src/components/ui/sheet.tsx
  web/src/components/ui/sidebar.tsx
  web/src/components/ui/tabs-bar.tsx
  web/src/ee/features/evals/components/eval-template-detail.tsx
  web/src/ee/features/evals/pages/new-template.tsx
  web/src/features/organizations/components/ProjectOverview.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/components/prompt-new.tsx
  web/src/features/setup/components/SetupPage.tsx
  web/src/features/theming/ThemeToggle.tsx
  web/src/hooks/use-mobile.tsx
  web/src/pages/organization/[organizationId]/settings/index.tsx
  web/src/pages/project/[projectId]/index.tsx
  web/src/pages/project/[projectId]/models/new.tsx
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
  web/src/pages/support.tsx
  web/src/styles/globals.css
  web/tailwind.config.ts
Labels: ui, size:XXL

#3998 fix: remove final from ingestion
  worker/src/services/IngestionService/index.ts
Labels: size:XS

#3999 fix: opening public langfuse urls
  web/src/components/layouts/layout.tsx
Labels: bug, size:XS

#4002 perf(ui): do not refetch filter options on page mount
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/index.tsx
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/features/prompts/components/NewPromptForm/index.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/components/prompts-table.tsx
  web/src/pages/project/[projectId]/index.tsx
Labels: ui, size:M

#3982 feat: support for traces detail view with clickhouse
  packages/shared/src/server/repositories/index.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/components/layouts/ClickhouseAdminToggle.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/index.tsx
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
Labels: feat-scores, size:XL

#4004 fix: select all functionality on prompt metrics table
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: bug, size:XS

#4005 fix: fix traces table latency
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/traces.ts
Labels: size:S

#4010 fix: fix eval execution retries
  worker/src/features/evaluation/evalService.ts
Labels: size:M

#4008 chore: fix fetching model
  packages/shared/src/server/repositories/observations.ts
Labels: size:M

#4011 fix: fix timestamps in clickhouse reading
  .github/workflows/pipeline.yml
  packages/shared/src/server/clickhouse/schema-utils.ts
  packages/shared/src/server/clickhouse/schema.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  web/jest.config.mjs
  web/package.json
  web/src/__tests__/server/repositories/clickhouse-helpers.ts
  web/src/__tests__/server/repositories/observation-repository.servertest.ts
  web/src/__tests__/server/repositories/trace-repository.servertest.ts
  web/src/__tests__/test-utils.ts
  web/src/server/api/routers/traces.ts
  worker/src/services/IngestionService/index.ts
Labels: bug, size:XL

#4013 fix: fix clickhouse untis and conversions
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/observations.ts
  web/src/__tests__/server/repositories/observation-repository.servertest.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: bug, size:L

#4014 chore: improve clickhouse observability
  packages/shared/src/server/repositories/clickhouse.ts
Labels: size:M

#4016 fix: respect limit and offset for traces table query
  packages/shared/src/server/repositories/traces.ts
Labels: size:XS

#4017 perf: improve traces metrics API performance
  web/src/server/api/routers/traces.ts
Labels: size:S

#4015 feat: add generations table clickhouse support
  packages/shared/src/server/filterToPrisma.ts
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/queries/createGenerationsQuery.ts
  packages/shared/src/server/repositories/index.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/repositories/types.ts
  packages/shared/src/tableDefinitions/index.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  web/src/components/table/use-cases/generations.tsx
  web/src/server/api/routers/generations/db/getAllGenerationsSqlQuery.ts
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/generations/getAllQueries.ts
Labels: feat-api, size:XXL

#4020 feat: add order by to clickhouse tables
  packages/shared/src/server/queries/clickhouse-filter/orderby-factory.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  packages/shared/src/tableDefinitions/types.ts
  web/src/server/api/routers/generations/db/getAllGenerationsSqlQuery.ts
  web/src/server/api/routers/traces.ts
Labels: size:L

#4021 perf: improve select by id observations performance
  packages/shared/src/server/repositories/observations.ts
Labels: size:XS

#4029 fix: multi-select header partially cut off on Firefox
  web/src/components/table/use-cases/traces.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemsTable.tsx
Labels: bug, ui, size:XS

#4003 fix: show generations count on prompt metrics table
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: size:S

#4031 chore: remove temporary column from PG to CH migrations
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241104111600_background_migrations_add_state_column/migration.sql
  packages/shared/prisma/schema.prisma
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateScoresFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateTracesFromPostgresToClickhouse.ts
Labels: size:L

#4034 chore: include usagedetails from postgres in ingestion pipeline
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:S

#4030 fix: scores tab in observation preview to only show scores liked to observation and trace id
  web/src/components/trace/ObservationPreview.tsx
Labels: bug, size:XS

#4039 chore: init migration scripts with state on restarts
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateScoresFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateTracesFromPostgresToClickhouse.ts
Labels: size:M

#4042 chore(ui): slightly lighter bg of darkmode sidebar
  web/src/styles/globals.css
Labels: size:XS

#4023 feat: add first three dashboards in clickhouse
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/index.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/index.ts
  packages/shared/src/tableDefinitions/mapDashboards.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/ScoresTable.tsx
  web/src/features/dashboard/components/TracesBarListChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/pages/project/[projectId]/index.tsx
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/traces.ts
Labels: feat-dashboard, size:L

#4044 chore: reduce startTime missing logs to create events
  worker/src/services/IngestionService/index.ts
Labels: feat-log-levels, size:XS

#4047 perf: only join in dashboard if required
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/repositories/dashboards.ts
Labels: feat-dashboard, size:S

#4048 feat: query second row of dashboards using clickhouse
  packages/shared/src/server/repositories/dashboards.ts
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/utils/date-range-utils.ts
Labels: feat-dashboard, size:L

#4049 perf: fix timeseries clickouse
  packages/shared/src/server/repositories/dashboards.ts
Labels: size:XS

#4022 feat: add metadata filter for all UI tables using clickhouse
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/observations.ts
Labels: ui, lgtm, feat-metadata, size:M

#4055 feat(models): add claude haiku 3.5 support
  packages/shared/prisma/migrations/20241105110900_add_claude_haiku_35/migration.sql
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: size:M

#4059 chore: ignore all .env files aside from examples
  .gitignore
Labels: size:XS

#4058 chore: retry legacy ingestion batches on errors
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:XS

#3971 feat(datasets): view to compare different dataset runs
  web/src/components/table/data-table.tsx
  web/src/components/trace/IOPreview.tsx
  web/src/components/ui/table.tsx
  web/src/ee/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunAggregateColumnHelpers.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/datasets/hooks/useDatasetRunAggregateColumns.ts
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/features/scores/components/multi-select-key-values.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: feat-datasets, size:XL

#4062 chore: do not send auth errors to DLQ in bull
  packages/shared/src/server/ingestion/legacy/index.ts
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:S

#4061 chore: add test case for different input/output values
  web/src/__tests__/ingestion.servertest.ts
Labels: size:M

#4057 chore: update cost calculation to handle null values from DB
  packages/shared/src/server/repositories/definitions.ts
  pnpm-lock.yaml
  worker/package.json
  worker/src/scripts/verifyClickhouseRecords/index.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-cost-tracking, size:L

#4063 fix: unify ordering of `dataset_items` and `dataset_run_items`
  web/src/features/datasets/server/dataset-router.ts
Labels: size:XS

#4064 chore: forward /api/public/scores to /api/public/ingestion
  web/src/pages/api/public/ingestion.ts
  web/src/pages/api/public/scores/index.ts
Labels: size:XL

#4083 chore: add type filter to observation lookup in ingestion queue
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:L

#4084 chore: drop redundant observation project_id index on Clickhouse
  packages/shared/clickhouse/migrations/0004_drop_observations_index.down.sql
  packages/shared/clickhouse/migrations/0004_drop_observations_index.up.sql
Labels: size:XS

#4085 chore: restrict domain timestamp updates to one day in clickhouse ingestion
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:M

#4089 fix(ui): render dataset run description and metadata on screen given table
  web/src/pages/project/[projectId]/datasets/[datasetId]/runs/[runId].tsx
Labels: ui, size:M

#4094 chore: include backgroundmigration state default in schema.prisma
  packages/shared/prisma/schema.prisma
Labels: size:XS

#4095 chore: convert starttime filter to DateTime in Ingestion pipeline
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.unit.test.ts
Labels: size:M

#4092 feat: build scores table for clickhouse
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/tableDefinitions/index.ts
  packages/shared/src/tableDefinitions/mapScoresTable.ts
  web/src/components/table/use-cases/scores.tsx
  web/src/server/api/routers/scores.ts
Labels: feat-scores, size:L

#4098 fix: pagination for clickhouse tables
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/traces.ts
Labels: bug, size:S

#4101 chore: add stateSuffix to observation migration for potential parallelization
  packages/shared/prisma/generated/types.ts
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
Labels: size:S

#4104 chore: merge observation backfill states in table
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
Labels: size:M

#4105 perf: query traces via timestamps
  packages/shared/src/server/clickhouse/client.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/components/star-toggle.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.unit.test.ts
Labels: size:M

#4065 feat: support sessions API from Clickhouse
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/mapSessionTable.ts
  web/src/components/session/index.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
Labels: feat-sessions, size:XL

#4108 perf: add sessions index in clickhouse
  packages/shared/clickhouse/migrations/0005_add_session_id_index.down.sql
  packages/shared/clickhouse/migrations/0005_add_session_id_index.up.sql
Labels: feat-sessions, size:XS

#4111 perf: improve generations performance
  packages/shared/src/server/repositories/traces.ts
Labels: size:M

#4124 perf: improve generations table on clickhouse
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  web/src/server/api/routers/generations/filterOptionsQuery.ts
Labels: size:L

#4109 chore: move legacy api endpoints to async ingestion
  web/src/features/public-api/types/events.ts
  web/src/features/public-api/types/generations.ts
  web/src/features/public-api/types/spans.ts
  web/src/pages/api/public/events.ts
  web/src/pages/api/public/generations.ts
  web/src/pages/api/public/ingestion.ts
  web/src/pages/api/public/scores/index.ts
  web/src/pages/api/public/spans.ts
  web/src/pages/api/public/traces/index.ts
Labels: feat-api, size:L

#4130 fix: reduce ingestion concurrency
  .env.prod.example
  web/src/env.mjs
  web/src/pages/api/public/ingestion.ts
  worker/src/services/IngestionService/index.ts
Labels: lgtm, size:S

#4081 chore: inject eval and annotation scores into clickhouse
  .env.dev.example
  packages/shared/src/db.ts
  packages/shared/src/env.ts
  packages/shared/src/server/clickhouse/schemaUtils.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/ingestion/validateAndInflateScore.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/pages/api/public/scores/[scoreId].ts
  web/src/server/api/routers/scores.ts
  worker/src/__tests__/evalService.test.ts
  worker/src/__tests__/eventsApi.test.ts
  worker/src/__tests__/network.ts
  worker/src/__tests__/redisConsumer.test.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-scores, size:XL

#4137 feat(ui): add notification card in sidebar
  web/src/components/app-sidebar.tsx
  web/src/components/layouts/layout.tsx
  web/src/components/sidebar-notifications.tsx
  web/src/features/notifications/checkNotifications.tsx
Labels: ui, size:L

#4138 feat: delete traces from clickhouse from the UI
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/traces.ts
Labels: ui, size:M

#4139 fix: fix latency calculations when reading from clickhouse
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
Labels: bug, size:S

#4140 fix: correctly parse model params from clickhouse
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/repositories/observations.ts
  web/src/__tests__/server/repositories/observation-repository.servertest.ts
Labels: bug, size:S

#4141 chore: clean ups of clickhouse read logic
  packages/shared/prisma/seed.ts
  packages/shared/src/features/scores/index.ts
  packages/shared/src/features/scores/types.ts
  packages/shared/src/index.ts
  packages/shared/src/server/queries/clickhouse-sql/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-sql/factory.ts
  packages/shared/src/server/queries/clickhouse-sql/orderby-factory.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/index.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/scores_converters.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/repositories/traces_converters.ts
  web/src/components/grouped-score-badge.tsx
  web/src/components/scores-table-cell.tsx
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/features/scores/components/ScoreDetailColumnHelpers.tsx
  web/src/features/scores/lib/aggregateScores.ts
  web/src/features/scores/lib/types.ts
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
  web/src/pages/project/[projectId]/users.tsx
  web/src/server/api/routers/traces.ts
  web/src/server/api/routers/users.ts
Labels: feat-datasets, feat-scores, size:XL

#4142 feat: add table search for clickhouse
  packages/shared/src/server/queries/clickhouse-sql/search.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/generations/db/getAllGenerationsSqlQuery.ts
  web/src/server/api/routers/traces.ts
Labels: size:M

#4132 chore: update bookmarked, tags, and public for clickhouse traces
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/repositories/traces_converters.ts
  web/src/server/api/routers/traces.ts
Labels: feat-tags, size:L

#4144 perf: scores dashboard performance improvement
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/observations.ts
Labels: feat-dashboard, feat-scores, size:M

#4146 feat: add user charts
  packages/shared/scripts/load-seed.ts
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/features/dashboard/components/UserChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
Labels: feat-dashboard, size:L

#4148 chore: set source: API if no source provided
  packages/shared/src/server/ingestion/validateAndInflateScore.ts
Labels: size:XS

#4149 feat: query scores over time
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/tableDefinitions/mapDashboards.ts
  web/src/features/dashboard/components/ChartScores.tsx
  web/src/features/dashboard/server/dashboard-router.ts
Labels: feat-dashboard, feat-scores, size:M

#4150 feat: read latency tables from clickhouse
  packages/shared/src/server/repositories/dashboards.ts
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/server/dashboard-router.ts
Labels: feat-dashboard, size:L

#4151 fix: traces aggregate trace filter
  packages/shared/src/server/repositories/dashboards.ts
Labels: size:XS

#4152 feat: query model latencies from clickhouse
  packages/shared/src/server/repositories/dashboards.ts
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
Labels: feat-dashboard, size:M

#4155 perf: increase traces metrics performance
  packages/shared/scripts/load-seed.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:M

#4153 feat: steer reading from CH and PG
  packages/shared/src/server/instrumentation/index.ts
  web/src/env.mjs
  web/src/server/api/routers/traces.ts
  web/src/server/utils/checkClickhouseAccess.ts
Labels: size:L

#4158 perf: add timestamp to filteroptions api
  web/src/components/table/use-cases/traces.tsx
  web/src/server/api/routers/traces.ts
Labels: feat-api, size:XS

#4159 perf: add time filter for sessions
  packages/shared/src/server/repositories/traces.ts
Labels: feat-sessions, size:S

#4160 feat: move generations api to experimentation setup
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/generations/getAllQueries.ts
Labels: feat-api, size:L

#4161 feat: move sessions api to experimentation setup
  web/src/server/api/routers/sessions.ts
Labels: feat-sessions, size:XL

#4162 chore: read dashboards form clickhouse flag
  web/src/env.mjs
  web/src/features/dashboard/server/dashboard-router.ts
Labels: size:L

#4164 perf: improve performance for latency dashboard
  packages/shared/src/server/repositories/dashboards.ts
Labels: feat-dashboard, size:S

#4167 fix: fix aggregated user consumption
  packages/shared/src/server/repositories/dashboards.ts
Labels: bug, size:XS

#4170 fix(ui): width of date range time input
  web/src/components/ui/time-picker-input.tsx
Labels: size:XS

#4171 perf(cloud): add 60 min stale time for usage indicator
  web/src/ee/features/billing/components/UsageTracker.tsx
Labels: size:XS

#4173 fix: correctly filter observations by generations for generations ui table
  packages/shared/src/server/repositories/observations.ts
Labels: bug, ui, size:XS

#4175 chore: update latency calculation for clickhouse dashboard queries
  packages/shared/src/server/repositories/dashboards.ts
Labels: size:L

#4176 fix(dataset_runs): ensure consistent ordering to fetch score data for dataset run aggregation metrics table
  web/src/features/datasets/server/dataset-router.ts
Labels: size:S

#4180 chore: remove uninstantiated projectId from clickhouse seeder
  packages/shared/clickhouse/scripts/seed.ts
Labels: size:XS

#4181 chore: migrate spammy log messages to debug level
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
  packages/shared/src/server/ingestion/legacy/index.ts
  packages/shared/src/server/services/PromptService.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/features/tokenisation/usage.ts
  worker/src/services/IngestionService/index.ts
Labels: size:M

#4182 Revert "fix(dataset_runs): ensure consistent ordering to fetch score data for dataset run aggregation metrics table"
  web/src/features/datasets/server/dataset-router.ts
Labels: size:S

#4184 chore: add error logs in trpc route
  web/src/server/api/trpc.ts
Labels: size:S

#4185 perf: add timestamp to traces table link
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/repositories/traces_converters.ts
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/index.tsx
  web/src/pages/project/[projectId]/traces/[traceId].tsx
Labels: size:M

#4186 feat: up/down detail navigation support params
  web/src/components/session/index.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/index.tsx
  web/src/ee/features/evals/components/evaluator-detail.tsx
  web/src/ee/features/evals/components/evaluator-table.tsx
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/navigate-detail-pages/DetailPageNav.tsx
  web/src/features/navigate-detail-pages/context.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/components/prompts-table.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items/[itemId].tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/runs/[runId].tsx
  web/src/pages/project/[projectId]/users.tsx
  web/src/pages/project/[projectId]/users/[userId].tsx
Labels: feat-datasets, feat-evals, size:L

#4187 feat: use timestamp to link single traces from navigation
  packages/shared/src/server/repositories/traces.ts
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/index.tsx
Labels: size:S

#4190 fix: fix clickhouse filters
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapSessionTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  web/src/components/table/use-cases/scores.tsx
  web/src/server/api/definitions/scoresTable.ts
  web/src/server/api/routers/sessions.ts
Labels: bug, size:L

#4188 chore: centralize lookback guarantees
  packages/shared/src/server/repositories/Readme.md
  packages/shared/src/server/repositories/constants.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
Labels: lgtm, size:M

#4192 feat: move scores table apis to experimentation setup
  web/src/server/api/routers/scores.ts
Labels: feat-scores, size:L

#4193 chore: remove logs
  web/src/server/utils/checkClickhouseAccess.ts
Labels: size:XS

#4194 fix: fix indefinite table queries
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/sessions.ts
Labels: bug, size:S

#4195 fix: fix public trace access
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/server/api/routers/generations/getAllQueries.ts
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
  web/src/server/utils/checkClickhouseAccess.ts
Labels: bug, lgtm, size:M

#4206 fix(playground): disable stream_options for openai adapter
  packages/shared/src/server/llm/fetchLLMCompletion.ts
Labels: size:XS

#4207 chore: remove superfluous isClickhouseAdminEligible checks
  web/src/server/api/routers/generations/getAllQueries.ts
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/traces.ts
  web/src/server/utils/checkClickhouseAccess.ts
Labels: lgtm, size:L

#4209 chore: apply trace timestamp filter correctly on user model query
  packages/shared/src/server/repositories/constants.ts
  packages/shared/src/server/repositories/dashboards.ts
Labels: size:S

#4210 chore: handle clickhouse errors gracefully and correct formatting for getTraceById timestamp
  packages/shared/src/server/clickhouse/client.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/server/utils/checkClickhouseAccess.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.unit.test.ts
Labels: size:M

#4211 security: upgrade dd-trace
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:M

#4216 revert: "security: upgrade dd-trace (#4211)"
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:M

#4214 chore: use event_ts instead of final for obs and score retrieval
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:S

#4191 chore: migrate users table to clickhouse
  packages/shared/src/server/repositories/traces.ts
  web/src/pages/project/[projectId]/users.tsx
  web/src/pages/project/[projectId]/users/[userId].tsx
  web/src/server/api/routers/users.ts
Labels: feat-users, size:XL

#4218 feat: fetch number of generations for prompts table form clickhouse
  packages/shared/src/server/repositories/observations.ts
  web/src/__tests__/server/api/tables/prompts-ui.servertest.ts
  web/src/__tests__/server/repositories/clickhouse-helpers.ts
  web/src/features/prompts/components/prompts-table.tsx
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: feat-prompt-management, size:L

#4220 fix: fix observations order by
  packages/shared/src/tableDefinitions/mapTracesTable.ts
Labels: size:XS

#4221 fix: fix order by in clickhouse
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapScoresTable.ts
  packages/shared/src/tableDefinitions/mapSessionTable.ts
Labels: size:S

#4222 fix(playground): jump to playground for clickhouse reads
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: size:S

#4225 fix: fix trace filter on score analytics charts
  packages/shared/src/server/repositories/dashboards.ts
Labels: bug, size:XS

#3989 feat(multimodal): add media upload / download endpoints
  .env.dev.example
  fern/apis/server/definition/media.yml
  fern/apis/server/definition/score.yml
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241106122605_add_media_tables/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/env.ts
  packages/shared/src/server/instrumentation/index.ts
  packages/shared/src/server/services/S3StorageService.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/media.servertest.ts
  web/src/__tests__/static/bitcoin.pdf
  web/src/__tests__/static/langfuse-logo.png
  web/src/__tests__/test-utils.ts
  web/src/env.mjs
  web/src/features/media/server/getFileExtensionFromContentType.ts
  web/src/features/media/server/getMediaStorageClient.ts
  web/src/features/media/validation.ts
  web/src/pages/api/public/media/[mediaId].ts
  web/src/pages/api/public/media/index.ts
Labels: feat-multimodal, size:XXL

#4234 chore: add timestamp filter for dashboard queries
  packages/shared/src/server/repositories/dashboards.ts
Labels: size:M

#4233 chore: reduce use of FINAL in clickhouse queries
  packages/shared/src/interfaces/filters.ts
  packages/shared/src/server/filterToPrisma.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/routers/users.ts
Labels: size:L

#4235 fix: use todate for trace timestamps
  packages/shared/src/server/repositories/traces.ts
  web/src/__tests__/server/repositories/trace-repository.servertest.ts
Labels: size:M

#4237 fix: sessions metrics query
  packages/shared/src/server/queries/clickhouse-sql/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-sql/factory.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/sessions.ts
Labels: size:M

#4238 chore: add query parameter to healthcheck which enables failure on unavailable database
  web/src/pages/api/public/health.ts
Labels: size:S

#4239 chore: improve clickhouse experimentation
  web/src/server/utils/checkClickhouseAccess.ts
Labels: size:XS

#4240 feat(cloud): move hobby plan usage info to sidebar
  web/src/components/app-sidebar.tsx
  web/src/components/layouts/routes.tsx
  web/src/components/sidebar-notifications.tsx
  web/src/ee/features/billing/components/UsageTracker.tsx
Labels: size:M

#4224 feat: read metrics for prompts table
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/prisma/seed.ts
  packages/shared/scripts/load-seed.ts
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  web/src/__tests__/server/api/tables/prompts-ui.servertest.ts
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: ui, feat-prompt-management, size:L

#4242 feat: exclude project_ids from clickhouse experimentation
  web/src/env.mjs
  web/src/server/utils/checkClickhouseAccess.ts
Labels: size:S

#4245 chore: add clickhouse migrations to web entrypoint
  docker-compose.v3preview.yml
  packages/shared/clickhouse/scripts/up.sh
  web/Dockerfile
  web/entrypoint.sh
Labels: size:S

#4248 chore: add note for future score create removal
  worker/src/features/evaluation/evalService.ts
Labels: size:XS

#4246 chore: fill clickhouse trace for observations with missing traceId
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
  worker/src/services/IngestionService/index.ts
Labels: size:M

#4252 fix: fail on errors in database migrations
  web/entrypoint.sh
Labels: size:S

#4253 chore: add tzdata package
  web/Dockerfile
Labels: size:XS

#4250 chore: add media env to v3preview docker compose
  docker-compose.v3preview.yml
  web/src/env.mjs
Labels: size:S

#4251 perf: improve prompt metrics performance
  packages/shared/src/server/repositories/scores.ts
Labels: feat-scores, size:XS

#4086 feat: support evals triggered via dataset run
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241114175010_job_executions_add_observation_dataset_item_cols/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/prisma/seed.ts
  packages/shared/src/features/evals/types.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/legacy/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/datasetRunItemUpsert.ts
  packages/shared/src/tableDefinitions/tracesTable.ts
  packages/shared/src/tableDefinitions/types.ts
  packages/shared/src/types.ts
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/ee/features/evals/components/evaluator-table.tsx
  web/src/ee/features/evals/server/addDatasetRunItemsToEvalQueue.ts
  web/src/ee/features/evals/server/router.ts
  web/src/features/feature-flags/available-flags.ts
  web/src/features/filters/components/multi-select.tsx
  web/src/pages/api/public/dataset-run-items.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/services/tableDefinitions.ts
  worker/src/__tests__/evalService.test.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/queues/evalQueue.ts
  worker/src/queues/workerManager.ts
Labels: feat-evals, size:XXL

#4257 fix(cloud): usage indicator only on hobby plan
  web/src/ee/features/billing/components/UsageTracker.tsx
Labels: size:XS

#4256 chore(ui): enable all feature flags for admins
  web/src/features/feature-flags/hooks/useIsFeatureEnabled.ts
Labels: ui, size:XS

#4265 feat: move traces.hasany to clickhouse
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/traces.ts
Labels: size:M

#4266 feat: configure to read from clickhouse only
  web/src/env.mjs
  web/src/server/utils/checkClickhouseAccess.ts
Labels: size:XS

#4267 fix: session id filter on session table
  web/src/components/table/use-cases/sessions.tsx
  web/src/server/api/routers/sessions.ts
Labels: size:XS

#4264 feat: read dataset fetures from clickhouse
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/prisma/seed.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/scores_converters.ts
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:XL

#4269 feat: move datasets results to logs only
  web/src/features/datasets/server/dataset-router.ts
  web/src/server/utils/checkClickhouseAccess.ts
Labels: feat-datasets, size:S

#4272 feat: serve datasets from clickhouse
  web/src/server/utils/checkClickhouseAccess.ts
Labels: feat-datasets, size:S

#4273 fix: fix dataset run items api
  web/src/features/datasets/server/dataset-router.ts
Labels: size:XS

#4274 fix: fix dataset id api
  web/src/features/datasets/server/dataset-router.ts
Labels: size:XS

#4275 fix: fix dataset runs api
  packages/shared/src/server/repositories/observations.ts
  web/src/features/datasets/server/dataset-router.ts
Labels: size:L

#4131 feat(ui): peek view on dataset run compare table
  web/src/components/trace/IOPreview.tsx
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/ui/drawer.tsx
  web/src/features/comments/CommentDrawerButton.tsx
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetCompareRunPeekView.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/scores/components/AnnotateDrawer.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/runs/[runId].tsx
Labels: ui, feat-datasets, size:XL

#4278 feat(datasets): add header to peek view
  web/src/components/layouts/peek-view.tsx
  web/src/features/datasets/components/DatasetCompareRunPeekView.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
Labels: feat-datasets, size:L

#4282 fix(dataset_compare): show latency only if not null
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
Labels: size:XS

#4289 feat(evals_on_datasets): remove feature flag
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/features/feature-flags/available-flags.ts
Labels: feat-evals, size:S

#4285 feat(media): add ui support
  fern/apis/server/definition/media.yml
  web/next.config.mjs
  web/public/generated/api/openapi.yml
  web/src/components/schemas/ChatMlSchema.ts
  web/src/components/trace/IOPreview.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/components/ui/LangfuseMediaView.tsx
  web/src/components/ui/MarkdownViewer.tsx
  web/src/components/ui/resizable-image.tsx
  web/src/features/media/validation.ts
  web/src/pages/api/public/media/[mediaId].ts
  web/src/pages/api/public/media/index.ts
  web/src/server/api/root.ts
  web/src/server/api/routers/media.ts
Labels: ui, size:XXL

#4288 perf: do not fetch models for UI
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/observations_converters.ts
  web/src/server/api/routers/generations/db/getAllGenerationsSqlQuery.ts
  web/src/server/api/routers/traces.ts
Labels: ui, size:L

#4292 feat: fetch sessions by id for public API
  packages/shared/src/server/repositories/traces.ts
  web/src/__tests__/async/sessions-api.servertest.ts
  web/src/__tests__/fixtures/tracing-factory.ts
  web/src/__tests__/server/api/tables/traces-ui.servertest.ts
  web/src/__tests__/server/repositories/clickhouse-helpers.ts
  web/src/__tests__/server/repositories/trace-repository.servertest.ts
  web/src/__tests__/sessions.servertest.ts
  web/src/pages/api/public/sessions/[sessionId].ts
  web/src/server/api/routers/sessions.ts
Labels: feat-sessions, size:L

#4300 docs: add sidebar notification for dataset comparison view
  web/src/components/sidebar-notifications.tsx
Labels: ui, size:S

#4287 chore: make migrations self-host replica compatible
  .env.dev.example
  .env.dev.legacy.example
  docker-compose.v3preview.yml
  packages/shared/clickhouse/migrations/clustered/0001_traces.down.sql
  packages/shared/clickhouse/migrations/clustered/0001_traces.up.sql
  packages/shared/clickhouse/migrations/clustered/0002_observations.down.sql
  packages/shared/clickhouse/migrations/clustered/0002_observations.up.sql
  packages/shared/clickhouse/migrations/clustered/0003_scores.down.sql
  packages/shared/clickhouse/migrations/clustered/0003_scores.up.sql
  packages/shared/clickhouse/migrations/clustered/0004_drop_observations_index.down.sql
  packages/shared/clickhouse/migrations/clustered/0004_drop_observations_index.up.sql
  packages/shared/clickhouse/migrations/clustered/0005_add_session_id_index.down.sql
  packages/shared/clickhouse/migrations/clustered/0005_add_session_id_index.up.sql
  packages/shared/clickhouse/migrations/unclustered/0001_traces.down.sql
  packages/shared/clickhouse/migrations/unclustered/0001_traces.up.sql
  packages/shared/clickhouse/migrations/unclustered/0002_observations.down.sql
  packages/shared/clickhouse/migrations/unclustered/0002_observations.up.sql
  packages/shared/clickhouse/migrations/unclustered/0003_scores.down.sql
  packages/shared/clickhouse/migrations/unclustered/0003_scores.up.sql
  packages/shared/clickhouse/migrations/unclustered/0004_drop_observations_index.down.sql
  packages/shared/clickhouse/migrations/unclustered/0004_drop_observations_index.up.sql
  packages/shared/clickhouse/migrations/unclustered/0005_add_session_id_index.down.sql
  packages/shared/clickhouse/migrations/unclustered/0005_add_session_id_index.up.sql
  packages/shared/clickhouse/scripts/down.sh
  packages/shared/clickhouse/scripts/up.sh
  packages/shared/package.json
  web/entrypoint.sh
Labels: size:L

#4308 chore: upgrade prisma to 5.22.0
  packages/shared/package.json
  pnpm-lock.yaml
  web/Dockerfile
  web/package.json
  worker/package.json
Labels: dependencies, size:S
