Repository langfuse/langfuse, pull requests merged in 2024-10, with the labels that each got.

#3547 fix(prisma): HMR support
  packages/shared/src/db.ts
Labels: lgtm

#3587 chore: upgrade sentry
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#3588 chore: upgrade vitest
  packages/shared/package.json
  pnpm-lock.yaml
  worker/package.json
Labels: dependencies, size:XS

#3564 FEAT: Gitlab Auth Provider
  .env.prod.example
  web/src/ee/features/multi-tenant-sso/types.ts
  web/src/ee/features/multi-tenant-sso/utils.ts
  web/src/env.mjs
  web/src/features/auth-credentials/components/ResetPasswordPage.tsx
  web/src/pages/auth/sign-in.tsx
  web/src/server/auth.ts
Labels: lgtm, size:M

#3594 chore: setup codeql manually
  .github/workflows/codeql.yml
Labels: size:M

#3595 chore: automerge dependabot patch PRs
  .github/workflows/dependabot-auto-merge.yml
Labels: dependencies, size:S

#3597 chore: fix dependabot automerge
  .github/workflows/dependabot-auto-merge.yml
Labels: size:XS

#3599 chore: upgrade mermaid-js
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#3600 chore: upgrade svelte for ai sdk
  .github/workflows/codeql.yml
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#3601 chore: upgrade tailwind and kysely codegen
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:XS

#3614 chore: fix auto merging
  .github/workflows/dependabot-auto-merge.yml
Labels: size:XS

#3616 chore: remove auto merge
  .github/workflows/dependabot-auto-merge.yml
Labels: size:S

#3619 chore: correlate logs with traces
  packages/shared/package.json
  packages/shared/src/server/logger.ts
  pnpm-lock.yaml
  web/package.json
Labels: feat-log-levels, size:M

#3620 chore: update GHA checkout and setup-node actions
  .github/workflows/ci.yml.template
  .github/workflows/licencecheck.yml
  .github/workflows/pipeline.yml
Labels: size:M

#3603 chore: upgrade next
  .env.dev.example
  .github/workflows/pipeline.yml
  ee/package.json
  packages/config-eslint/package.json
  packages/shared/src/server/services/email/organizationInvitation/sendMembershipInvitationEmail.ts
  pnpm-lock.yaml
  web/package.json
  web/src/__tests__/rate-limit.servertest.ts
  web/src/env.mjs
Labels: dependencies, lgtm, size:L

#3633 chore: upgrade webpack
  pnpm-lock.yaml
Labels: dependencies, size:XS

#3636 chore: reduce log level
  web/src/components/publish-object-switch.tsx
  worker/src/features/evaluation/eval-service.ts
Labels: size:XS

#3622 chore: remove explicit context propagation for queues
  packages/shared/src/server/instrumentation/index.ts
  web/src/pages/api/public/ingestion.ts
  web/src/server/api/routers/batchExport.ts
  worker/src/queues/batchExportQueue.ts
  worker/src/queues/cloudUsageMeteringQueue.ts
  worker/src/queues/evalQueue.ts
  worker/src/queues/ingestionFlushQueueExecutor.ts
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:XL

#3640 revert: next upgrade due to incompatibility issues
  ee/package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#3644 chore: update bullmq instrumentation
  pnpm-lock.yaml
  web/package.json
  web/src/observability.config.ts
  worker/package.json
  worker/src/instrumentation.ts
Labels: dependencies, size:XS

#3537 chore: use s3 event store to avoid event data in redis
  .env.dev.example
  .github/workflows/pipeline.yml
  docker-compose.dev.yml
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
  packages/shared/src/server/ingestion/legacy/index.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/services/S3StorageService.ts
  web/src/__tests__/generation-exports.servertest.ts
  web/src/env.mjs
  web/src/pages/api/public/ingestion.ts
  web/src/server/api/routers/generations/exportQuery/index.ts
  worker/src/env.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:XL

#3649 chore: update metric name for eval exec queue length
  web/src/pages/api/public/ingestion.ts
  worker/src/queues/evalQueue.ts
Labels: size:XS

#3621 Properly split tags when passed as a string
  web/src/pages/api/public/metrics/daily.ts
  web/src/pages/api/public/traces/index.ts
Labels: bug, size:XS

#3653 feat: invalidate API keys via cloud admin api
  web/src/pages/api/admin/api-keys/index.ts
Labels: feat-api, size:M

#3654 chore: add orgid and projectid to ingestion event metric
  web/src/pages/api/public/ingestion.ts
Labels: size:XS

#3664 chore: remove metrics by users datadog
  web/src/pages/api/public/ingestion.ts
Labels: size:XS

#3665 chore: add projectid to ingestion logs
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:S

#3666 feat: front-end cloud admin flag for clickhouse
  web/src/components/layouts/ClickhouseAdminToggle.tsx
  web/src/components/layouts/layout.tsx
  web/src/pages/support.tsx
Labels: ui, size:M

#3651 fix: add Gitlab Issuer and Account.created_at col
  .env.prod.example
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241009042557_auth_add_created_at_for_gitlab/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/ee/features/multi-tenant-sso/types.ts
  web/src/env.mjs
  web/src/server/auth.ts
Labels: lgtm, size:S

#3667 feat: add crisp events in posthog
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/support-chat/chat.tsx
Labels: size:S

#3670 fix(ui): disable sign-in and sso buttons while email/pw are empty
  web/src/pages/auth/sign-in.tsx
Labels: feat-auth, size:S

#3672 fix: encode all links to objects with user-provided ids
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/pages/project/[projectId]/traces/[traceId].tsx
  web/src/pages/project/[projectId]/users.tsx
  web/src/pages/project/[projectId]/users/[userId].tsx
Labels: feat-datasets, feat-users, size:M

#3677 fix: adjust queue wait time metrics
  worker/src/queues/evalQueue.ts
  worker/src/queues/ingestionFlushQueueExecutor.ts
Labels: size:S

#3680 fix: do not retry when api key is missing for evals and normalise wait time metric
  packages/shared/src/server/queues.ts
  worker/src/__tests__/eval-service.test.ts
  worker/src/features/evaluation/eval-service.ts
  worker/src/queues/evalQueue.ts
Labels: bug, size:M

#3643 chore: upgrade nextjs to 14.2.14
  ee/package.json
  ee/src/env.ts
  packages/shared/src/env.ts
  packages/shared/src/index.ts
  packages/shared/src/utils/environment.ts
  pnpm-lock.yaml
  web/package.json
  web/src/env.mjs
  worker/src/env.ts
Labels: dependencies, size:L

#3499 feat(annotation): add annotation queue in feature flagged beta release
  .codespellrc
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241009110720_scores_add_nullable_queue_id_column/migration.sql
  packages/shared/prisma/migrations/20241009113245_add_annotation_queue/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/prisma/seed.ts
  packages/shared/src/features/annotation/types.ts
  web/src/components/layouts/routes.tsx
  web/src/components/layouts/status-badge.tsx
  web/src/components/table/data-table-multi-select-actions/trace-table-multi-select-action.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/index.tsx
  web/src/ee/features/billing/components/SupportOrUpgradePage.tsx
  web/src/features/audit-logs/auditLog.ts
  web/src/features/datasets/components/NewDatasetItemFromObservationButton.tsx
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/feature-flags/available-flags.ts
  web/src/features/notifications/SuccessNotification.tsx
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/features/scores/components/AnnotateDrawer.tsx
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/features/scores/components/AnnotationQueueItemPage.tsx
  web/src/features/scores/components/AnnotationQueueItemsTable.tsx
  web/src/features/scores/components/AnnotationQueuesItem.tsx
  web/src/features/scores/components/AnnotationQueuesTable.tsx
  web/src/features/scores/components/CreateNewAnnotationQueueItem.tsx
  web/src/features/scores/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/features/scores/components/DeleteAnnotationQueueButton.tsx
  web/src/pages/project/[projectId]/annotation-queues.tsx
  web/src/pages/project/[projectId]/annotation-queues/[queueId]/index.tsx
  web/src/pages/project/[projectId]/annotation-queues/[queueId]/items/[itemId].tsx
  web/src/pages/project/[projectId]/annotation-queues/[queueId]/items/index.tsx
  web/src/server/api/root.ts
  web/src/server/api/routers/annotationQueueItems.ts
  web/src/server/api/routers/annotationQueues.ts
  web/src/server/api/routers/scores.ts
Labels: ui, feat-scores, size:XXL

#3687 chore: allow updating annotation queue name
  web/src/server/api/routers/annotationQueues.ts
Labels: size:XS

#3691 feat: add posthog event for tracing_check_active
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/setup/components/SetupPage.tsx
  web/src/features/setup/components/SetupTracingButton.tsx
Labels: size:M

#3692 Revert "chore(deps): bump react-hook-form from 7.51.5 to 7.53.0"
  pnpm-lock.yaml
  web/package.json
  web/src/features/public-api/components/CreateLLMApiKeyDialog.tsx
Labels: dependencies, size:XS

#3694 fix(ui): md-view, ordered lists with many items
  web/src/components/ui/MarkdownViewer.tsx
Labels: ui, size:XS

#3693 fix: show add to annotation queue only when flag is set
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/features/feature-flags/components/FeatureFlagToggle.tsx
Labels: ui-other, size:M

#3700 chore: move span tagging to top of ingestion processing
  web/src/pages/api/public/ingestion.ts
Labels: size:M

#3701 style: adjust prompt icons, move edit/new version to action button, and always show prompt controls for current version
  web/src/components/layouts/routes.tsx
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/prompts/components/SetPromptVersionLabels/index.tsx
  web/src/features/prompts/components/delete-prompt-version.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/components/prompt-history.tsx
  web/src/features/prompts/components/prompts-table.tsx
Labels: feat-prompt-management, size:L

#3702 chore: bring log line back
  web/src/features/public-api/server/apiAuth.ts
Labels: size:S

#3710 chore: normalize ingestion span attributes
  web/src/pages/api/public/ingestion.ts
Labels: size:XS

#3712 chore: enable annotation queue on cloud:hobby and remove feature flags
  packages/shared/prisma/seed.ts
  web/src/components/layouts/routes.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemPage.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemsTable.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueuesItem.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueuesTable.tsx
  web/src/ee/features/annotation-queues/components/CreateNewAnnotationQueueItem.tsx
  web/src/ee/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/ee/features/annotation-queues/components/DeleteAnnotationQueueButton.tsx
  web/src/ee/features/annotation-queues/pages/AnnotationQueueItems.tsx
  web/src/ee/features/annotation-queues/pages/AnnotationQueues.tsx
  web/src/ee/features/annotation-queues/server/annotationQueueItems.ts
  web/src/ee/features/annotation-queues/server/annotationQueues.ts
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/feature-flags/available-flags.ts
  web/src/features/scores/components/AnnotationQueuesItem.tsx
  web/src/pages/project/[projectId]/annotation-queues.tsx
  web/src/pages/project/[projectId]/annotation-queues/[queueId]/index.tsx
  web/src/pages/project/[projectId]/annotation-queues/[queueId]/items/[itemId].tsx
  web/src/pages/project/[projectId]/annotation-queues/[queueId]/items/index.tsx
  web/src/server/api/root.ts
Labels: size:XL

#3711 feat(playground+evals): add bedrock support
  packages/shared/package.json
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241010120245_llm_keys_add_config/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/features/evals/types.ts
  packages/shared/src/index.ts
  packages/shared/src/interfaces/customLLMProviderConfigSchemas.ts
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  pnpm-lock.yaml
  web/src/ee/features/evals/components/template-form.tsx
  web/src/ee/features/evals/server/router.ts
  web/src/ee/features/playground/page/hooks/useModelParams.ts
  web/src/ee/features/playground/server/chatCompletionHandler.ts
  web/src/features/llm-api-key/server/router.ts
  web/src/features/llm-api-key/types.ts
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
  worker/src/features/evaluation/eval-service.ts
Labels: feat-evals, feat-playground, size:L

#3721 fix: fail open on rate limit errors
  web/src/pages/api/public/ingestion.ts
Labels: lgtm, size:S

#3722 feat(ui): add toggle for color coding of metrics on trace tree
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/index.tsx
Labels: ui, size:S

#3719 chore: migrate clickhouse ingestion to S3 based events
  .env.prod.example
  packages/shared/src/env.ts
  packages/shared/src/server/clickhouse.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/IngestionUtils.ts
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
  packages/shared/src/server/ingestion/legacy/enqueueIngestionEvents.ts
  packages/shared/src/server/ingestion/legacy/index.ts
  packages/shared/src/server/ingestion/modelMatch.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/batchExport.ts
  packages/shared/src/server/redis/ingestionFlushQueue.ts
  packages/shared/src/server/redis/ingestionQueue.ts
  packages/shared/src/server/redis/legacyIngestion.ts
  packages/shared/src/server/redis/traceUpsert.ts
  packages/shared/src/server/services/S3StorageService.ts
  web/src/env.mjs
  web/src/pages/api/public/ingestion.ts
  worker/src/__tests__/redis-consumer.test.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/queues/ingestionFlushQueueExecutor.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/queues/legacyIngestionQueue.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.unit.test.ts
Labels: size:XL

#3734 chore: authenticate with docker hub for CI
  .github/workflows/pipeline.yml
Labels: size:M

#3739 chore: add otel trace sampling support
  pnpm-lock.yaml
  web/src/env.mjs
  web/src/observability.config.ts
  worker/package.json
  worker/src/env.ts
  worker/src/instrumentation.ts
Labels: feat-sampling, size:XS

#3742 fix(models): start_date type to datetime in fern
  fern/apis/server/definition/models.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
Labels: size:XS

#3743 fix: show number of observations in trace table
  web/src/components/table/use-cases/traces.tsx
  web/src/server/api/routers/traces.ts
Labels: bug, size:XS

#3733 chore: group events on S3 by clickhouse entity
  packages/shared/src/server/clickhouse.ts
  web/src/pages/api/public/ingestion.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:S

#3741 chore: upgrade json path
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:S

#3740 feat: add select all / deselect all button to all tables columns visibility picker
  web/src/components/table/data-table-column-visibility-filter.tsx
  web/src/components/ui/dropdown-menu.tsx
Labels: ui, size:M

#3747 fix: add default minimum width for dynamic score columns, allow column reordering for prompts metrics table
  web/src/components/table/data-table.tsx
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: size:M

#3749 fix(llm-api-keys): add exact bedrock permission needed
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:XS

#3750 fix: loading state of annotation queue dropdown
  web/src/ee/features/annotation-queues/components/CreateNewAnnotationQueueItem.tsx
Labels: size:XS

#3751 fix(user_table): reset `orderBy` state on tab navigation
  web/src/pages/project/[projectId]/users/[userId].tsx
Labels: size:XS

#3753 style(ui): standardize table header line height across selection states
  web/src/components/table/use-cases/traces.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemsTable.tsx
Labels: ui, size:M

#3754 fix(self-host): LANGFUSE_INIT_USER_EMAIL lowercased for headless initialization
  web/src/initialize.ts
Labels: bug, size:XS

#3758 chore: support more decimal digits for cost in session view
  web/src/components/session/index.tsx
Labels: feat-cost-tracking, feat-sessions, size:XS

#3762 chore: remove trace sampler on worker
  pnpm-lock.yaml
  worker/package.json
  worker/src/env.ts
  worker/src/instrumentation.ts
Labels: size:XS

#3763 chore: support consistent empty and loading states in dashboard
  web/src/components/NoDataOrLoading.tsx
  web/src/features/dashboard/components/ChartScores.tsx
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/NoData.tsx
  web/src/features/dashboard/components/ScoresTable.tsx
  web/src/features/dashboard/components/TabsComponent.tsx
  web/src/features/dashboard/components/TracesBarListChart.tsx
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/components/UserChart.tsx
  web/src/features/dashboard/components/cards/DashboardTable.tsx
  web/src/features/dashboard/components/score-analytics/CategoricalScoreChart.tsx
  web/src/features/dashboard/components/score-analytics/NumericScoreHistogram.tsx
  web/src/features/dashboard/components/score-analytics/NumericScoreTimeSeriesChart.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
Labels: feat-dashboard, size:L

#3774 fix(ui): transition from uncontrolled to controlled component, add expected drawer title
  web/src/components/layouts/doc-popup.tsx
  web/src/components/layouts/header.tsx
  web/src/components/ui/dialog.tsx
  web/src/components/ui/drawer.tsx
  web/src/features/comments/CommentDrawerButton.tsx
  web/src/features/scores/components/AnnotateDrawer.tsx
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/features/scores/components/CreateScoreConfigButton.tsx
Labels: ui, size:L

#3771 feat(api): add queueId query param to GET /scores
  fern/apis/server/definition/commons.yml
  fern/apis/server/definition/score.yml
  packages/shared/src/features/scores/scoreTypes.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/scores.servertest.ts
  web/src/pages/api/public/scores/index.ts
Labels: feat-api, feat-scores, size:L

#3759 chore(prompts): config data type to JSON
  packages/shared/prisma/migrations/20241015110145_prompts_config_to_JSON/migration.sql
  packages/shared/prisma/schema.prisma
Labels: size:L

#3770 chore: batch events by eventBodyId for reduces S3 interactions
  packages/shared/src/server/redis/legacyIngestion.ts
  web/src/pages/api/public/ingestion.ts
Labels: feat-api, size:L

#3638 chore: improve clickhouse schema
  packages/shared/clickhouse/migrations/0001_traces.up.sql
  packages/shared/clickhouse/migrations/0002_observations.up.sql
  packages/shared/clickhouse/migrations/0003_scores.up.sql
  packages/shared/clickhouse/migrations/0004_observations_wide.down.sql
  packages/shared/clickhouse/migrations/0004_observations_wide.up.sql
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/package.json
  packages/shared/src/server/definitions.ts
  pnpm-lock.yaml
  worker/src/services/IngestionService/index.ts
Labels: lgtm, size:L

#3784 fix(evals): put reasoning key before score
  worker/src/features/evaluation/eval-service.ts
Labels: size:XS

#3383 feat(api): POST /comments GET /comments GET /comments/${commentId}
  fern/apis/server/definition/comments.yml
  fern/apis/server/definition/commons.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/comments.servertest.ts
  web/src/__tests__/test-utils.ts
  web/src/features/comments/validateCommentReferenceObject.ts
  web/src/features/public-api/types/comments.ts
  web/src/pages/api/public/comments/[commentId].ts
  web/src/pages/api/public/comments/index.ts
  web/src/server/api/routers/comments.ts
Labels: feat-api, feat-comments, size:XXL

#3732 chore(refactor): calculate queue metrics in WorkerManager
  .env.dev.example
  .env.local.example
  docker-compose.build.yml
  packages/shared/src/server/ingestion/legacy/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/batchExport.ts
  packages/shared/src/server/redis/traceUpsert.ts
  pnpm-lock.yaml
  web/src/__tests__/query-builder.servertest.ts
  web/src/env.mjs
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/components/ScoresTable.tsx
  web/src/features/dashboard/components/hooks.ts
  web/src/features/dashboard/lib/score-analytics-utils.ts
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/server/api/routers/batchExport.ts
  web/src/server/api/services/WorkerClient.ts
  web/src/server/api/services/queryBuilder.ts
  worker/package.json
  worker/src/__tests__/eval-service.test.ts
  worker/src/__tests__/redis-consumer.test.ts
  worker/src/api/index.ts
  worker/src/app.ts
  worker/src/ee/cloudUsageMetering/handleCloudUsageMeteringJob.ts
  worker/src/env.ts
  worker/src/features/batchExport/enqueueBatchExportJobs.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/queues/cloudUsageMeteringQueue.ts
  worker/src/queues/evalQueue.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/queues/legacyIngestionQueue.ts
  worker/src/queues/repeatQueue.ts
  worker/src/queues/workerManager.ts
Labels: lgtm, size:XL

#3787 fix: don't use accessible title for queue item
  web/src/features/scores/components/AnnotateDrawerContent.tsx
Labels: size:M

#3790 chore: fix queue metric names
  worker/src/queues/workerManager.ts
Labels: size:S

#3785 chore: reconnect redis on errors
  packages/shared/src/server/redis/batchExport.ts
  packages/shared/src/server/redis/ingestionQueue.ts
  packages/shared/src/server/redis/legacyIngestion.ts
  packages/shared/src/server/redis/redis.ts
  packages/shared/src/server/redis/traceUpsert.ts
  worker/src/queues/cloudUsageMeteringQueue.ts
  worker/src/queues/evalQueue.ts
  worker/src/queues/workerManager.ts
Labels: size:M

#3791 chore: add error listeners on queues
  packages/shared/src/server/redis/batchExport.ts
  packages/shared/src/server/redis/ingestionQueue.ts
  packages/shared/src/server/redis/legacyIngestion.ts
  packages/shared/src/server/redis/redis.ts
  packages/shared/src/server/redis/traceUpsert.ts
  worker/src/queues/cloudUsageMeteringQueue.ts
  worker/src/queues/evalQueue.ts
Labels: size:M

#3793 fix(tables): serialization issue in score column visibility
  web/src/features/scores/lib/aggregateScores.ts
Labels: size:XS

#3788 feat(ui): render plain string as markdown by default on single trace/observation page
  web/src/components/schemas/MarkdownSchema.ts
  web/src/components/trace/IOPreview.tsx
  web/src/components/ui/MarkdownViewer.tsx
Labels: ui, size:S

#3792 feat(ui): support comments on annotation queue view
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemPage.tsx
  web/src/features/scores/components/AnnotateDrawerContent.tsx
Labels: ui, feat-comments, size:L

#3805 fix: only error eval execution for unexpected cases
  worker/src/queues/evalQueue.ts
Labels: size:S

#3804 chore: set ingestion delay to zero
  web/src/env.mjs
Labels: size:XS

#3808 chore: add traces wide table
  packages/shared/clickhouse/migrations/0005_traces_wide.down.sql
  packages/shared/clickhouse/migrations/0005_traces_wide.up.sql
Labels: size:L

#3825 fix: use trace/observation createdAt for health endpoint
  web/src/pages/api/public/health.ts
Labels: bug, lgtm, size:XS

#3826 feat: support DnD reordering of playground messages
  web/src/components/ChatMessages/ChatMessageComponent.tsx
  web/src/components/ChatMessages/index.tsx
  web/src/components/ChatMessages/types.ts
  web/src/ee/features/playground/page/context/index.tsx
  web/src/features/prompts/components/NewPromptForm/PromptChatMessages.tsx
  web/src/features/prompts/components/NewPromptForm/index.tsx
Labels: feat-playground, size:L

#3827 bug: UI prompt edit changes go away when tab switching
  web/src/features/prompts/components/prompt-new.tsx
Labels: feat-prompt-management, size:XS

#3828 chore: publish custom metrics to CloudWatch
  packages/shared/package.json
  packages/shared/src/env.ts
  packages/shared/src/server/instrumentation/index.ts
  pnpm-lock.yaml
Labels: size:M

#3830 chore: add tokenisation metrics
  worker/src/features/tokenisation/usage.ts
Labels: size:S

#3843 feat(api): add `traceTags` query param to GET /scores
  fern/apis/server/definition/score.yml
  packages/shared/src/features/scores/scoreTypes.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/scores.servertest.ts
  web/src/pages/api/public/scores/index.ts
Labels: feat-api, feat-scores, size:L

#3846 fix: local postgres query logging
  packages/shared/src/db.ts
Labels: bug, size:M

#3847 chore: add prod-eu deployment option
  .github/workflows/deploy.yml
Labels: size:XS

#3806 chore: remove prettier config
  ee/prettierrc.json
  packages/shared/prettierrc.json
Labels: lgtm, size:XS

#3851 fix(ui): table pagination distinguish between no data and loading states
  web/src/components/table/data-table-pagination.tsx
  web/src/components/table/data-table.tsx
Labels: ui, size:S

#3853 feat: improve clickhouse seeder
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/package.json
  packages/shared/scripts/load-seed.ts
  packages/shared/scripts/prepareClickhouse.ts
Labels: size:L

#3860 feat: format logs
  packages/shared/scripts/prepareClickhouse.ts
Labels: size:S

#3852 fix: don't throw unauthorized errors when viewing a public trace
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
  web/src/features/auth/hooks.ts
  web/src/features/datasets/components/NewDatasetItemFromObservationButton.tsx
Labels: bug, size:M

#3864 style: unify dataset buttons/badge with langfuse design system, add UI access check on archive dataset item
  web/src/features/datasets/components/DatasetActionButton.tsx
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/NewDatasetItemButton.tsx
Labels: ui, feat-datasets, size:M

#3865 feat: add new claude model
  packages/shared/prisma/migrations/20241022110145_add_claude_sonnet_35/migration.sql
Labels: size:S

#3867 chore: add clickhouse writer attributes
  worker/src/services/ClickhouseWriter/index.ts
Labels: size:S

#3878 feat: remove io from wide tables
  packages/shared/clickhouse/migrations/0004_observations_wide.up.sql
  packages/shared/clickhouse/migrations/0005_traces_wide.up.sql
Labels: size:S

#3880 perf: improve CH primary keys and order by
  packages/shared/clickhouse/migrations/0001_traces.up.sql
  packages/shared/clickhouse/migrations/0002_observations.up.sql
  packages/shared/clickhouse/migrations/0003_scores.up.sql
  packages/shared/clickhouse/migrations/0004_observations_wide.down.sql
  packages/shared/clickhouse/migrations/0004_observations_wide.up.sql
  packages/shared/clickhouse/migrations/0005_traces_wide.down.sql
  packages/shared/clickhouse/migrations/0005_traces_wide.up.sql
Labels: size:M

#3881 feat: adjust clickhouse writer
  worker/src/env.ts
Labels: size:XS

#3883 fix: improve ingestion pipeline by id query
  worker/src/services/IngestionService/index.ts
Labels: bug, size:XS

#3894 fix(models): update sonnet model name
  packages/shared/prisma/migrations/20241023110145_update_claude_sonnet_35/migration.sql
Labels: size:XS

#3887 feat: add is_deleted to clickhouse
  packages/shared/clickhouse/migrations/0001_traces.up.sql
  packages/shared/clickhouse/migrations/0002_observations.up.sql
  packages/shared/clickhouse/migrations/0003_scores.up.sql
  packages/shared/clickhouse/migrations/0004_observations_wide.up.sql
  packages/shared/clickhouse/migrations/0005_traces_wide.up.sql
  packages/shared/src/server/definitions.ts
  worker/src/services/IngestionService/index.ts
Labels: size:M

#3897 fix(evals): show eval filters in eval-configs table
  web/src/ee/features/evals/components/eval-config-table.tsx
  web/src/features/filters/components/filter-builder.tsx
Labels: size:S

#3898 feat(cloud): add event usage metering
  worker/src/ee/cloudUsageMetering/handleCloudUsageMeteringJob.ts
  worker/src/queues/cloudUsageMeteringQueue.ts
Labels: size:M

#3811 feat(cost): make cost tracking flexible
  packages/shared/clickhouse/migrations/0002_observations.up.sql
  packages/shared/clickhouse/migrations/0004_observations_wide.up.sql
  packages/shared/clickhouse/migrations/0005_traces_wide.up.sql
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20241024100928_add_prices_table/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/definitions.ts
  web/src/__tests__/model-definitions.servertest.ts
  web/src/components/table/use-cases/models.tsx
  web/src/pages/api/public/models/index.ts
  web/src/server/api/repositories/clickhouse.ts
  web/src/server/api/routers/models.ts
  worker/src/__tests__/utils.ts
  worker/src/app.ts
  worker/src/constants/default-model-prices.json
  worker/src/initialize.ts
  worker/src/scripts/createDefaultModelPricesJson.ts
  worker/src/scripts/upsertDefaultModelPrices.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
  worker/src/services/IngestionService/tests/calculateTokenCost.unit.test.ts
  worker/src/services/IngestionService/utils.ts
  worker/tsconfig.json
Labels: feat-cost-tracking, size:XXL

#3903 fix(models): allow for time tolerance in updateat diff
  worker/src/scripts/upsertDefaultModelPrices.ts
Labels: size:S

#3896 feat(evals): allow creating template from eval config form
  web/src/ee/features/evals/components/eval-config-form.tsx
  web/src/ee/features/evals/components/template-form.tsx
Labels: feat-evals, size:L

#3914 chore: faster healthcheck of minio in dev docker compose
  docker-compose.dev.yml
Labels: size:XS

#3849 chore: remove prod-eu-temp deploy environment
  .github/workflows/deploy.yml
Labels: size:XS

#3809 chore: validate clickhouse data quality
  pnpm-lock.yaml
  worker/package.json
  worker/src/scripts/verifyClickhouseRecords/README.md
  worker/src/scripts/verifyClickhouseRecords/index.ts
Labels: dependencies, size:L

#3934 chore: add is_deleted column to clickhouse seeder
  packages/shared/scripts/prepareClickhouse.ts
Labels: size:S

#3937 chore: remove hasCreateEvent check in ingestion pipeline
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:L

#3938 fix: populate default `metadata` when adding observation as dataset item
  web/src/components/trace/ObservationPreview.tsx
Labels: size:XS

#3939 feat: better handling of eval retries
  pnpm-lock.yaml
  worker/package.json
  worker/src/features/evaluation/evalService.ts
  worker/src/queues/evalQueue.ts
Labels: feat-evals, size:L

#3942 fix: treat api call failures for eval executions the same way as parsing errors.
  worker/src/features/evaluation/evalService.ts
Labels: size:M

#3945 chore: `pnpm dx` pulls latest infra containers, waits for healthcheck, prunes old volumes
  docker-compose.dev.yml
  package.json
Labels: size:S

#3946 chore: adjust eval execution retries
  worker/src/features/evaluation/evalService.ts
Labels: feat-evals, size:XS

#3947 chore: add bullmq to external package
  web/next.config.mjs
  web/src/instrumentation.ts
Labels: dependencies, size:XS

#3951 chore: add additional requirements for background migrations
  worker/src/backgroundMigrations/README.md
Labels: lgtm, size:XS

#3950 chore: add external packages to next config
  web/next.config.mjs
Labels: dependencies, lgtm, size:XS

#3916 style(evals): add table metadata view for eval config detail
  web/src/components/table/TableWithMetadataWrapper.tsx
  web/src/ee/features/annotation-queues/pages/AnnotationQueueItems.tsx
  web/src/ee/features/evals/components/evaluator-detail.tsx
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/ee/features/evals/components/evaluator-table.tsx
Labels: feat-evals, size:L

#3944 refactor: `full-screen-page` to drop magic in height calculation
  web/src/components/layouts/full-screen-page.tsx
  web/src/components/layouts/layout.tsx
  web/src/components/trace/index.tsx
  web/src/features/prompts/components/prompts-table.tsx
  web/src/pages/project/[projectId]/prompts/index.tsx
Labels: lgtm, size:M

#3955 fix(models): upsert prices on model drift;
  packages/shared/prisma/migrations/20241029130802_prices_drop_excess_index/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/server/api/routers/models.ts
  worker/src/scripts/upsertDefaultModelPrices.ts
Labels: lgtm, size:M

#3958 Revert "chore(deps): bump react-hook-form from 7.51.5 to 7.53.0 (#3917)"
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, lgtm, size:XS

#3959 chore: global error handling for `trpc` routes
  web/src/features/notifications/ErrorNotification.tsx
  web/src/features/notifications/showErrorToast.tsx
  web/src/server/api/trpc.ts
  web/src/utils/trpcErrorToast.tsx
Labels: size:M

#3962 feat: add feature filters
  packages/shared/src/server/clickhouse/schema.ts
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
Labels: size:L

#3919 feat(evals): option to update ref eval configs when creating new version
  pnpm-lock.yaml
  web/package.json
  web/src/components/ui/radio-group.tsx
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/ee/features/evals/components/template-form.tsx
  web/src/ee/features/evals/server/router.ts
  web/src/ee/features/evals/types.ts
Labels: feat-evals, size:L

#3967 chore: remove zod parsing from worker
  worker/src/queues/ingestionQueue.ts
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:M

#3968 chore: remove remaining zod parses in worker pipeline
  packages/shared/src/server/ingestion/legacy/index.ts
Labels: size:XS

#3960 chore: update traces and observations tables to use map type
  packages/shared/clickhouse/migrations/0000_flags.down.sql
  packages/shared/clickhouse/migrations/0000_flags.up.sql
  packages/shared/clickhouse/migrations/0001_traces.up.sql
  packages/shared/clickhouse/migrations/0002_observations.up.sql
  packages/shared/clickhouse/migrations/0003_scores.up.sql
  packages/shared/scripts/prepareClickhouse.ts
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateScoresFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateTracesFromPostgresToClickhouse.ts
Labels: feat-metadata, size:L

#3810 feat: read traces and observations from clickhouse
  .vscode/settings.json
  packages/shared/scripts/load-seed.ts
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/index.ts
  packages/shared/src/server/clickhouse.ts
  packages/shared/src/server/clickhouse/client.ts
  packages/shared/src/server/clickhouse/schema-utils.ts
  packages/shared/src/server/clickhouse/schema.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/queries/createTracesQuery.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/index.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  packages/shared/src/tableDefinitions/tracesTable.ts
  packages/shared/src/tableDefinitions/types.ts
  pnpm-lock.yaml
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/scores/hooks/useIndividualScoreColumns.ts
  web/src/server/api/routers/generations/getAllQueries.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
  web/src/server/utils/checkClickhouseAccess.ts
  worker/src/services/IngestionService/index.ts
Labels: size:XXL

#3969 feat: add clickhouse support for traces filter options endpoint
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/components/table/use-cases/traces.tsx
  web/src/server/api/routers/generations/getAllQueries.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
  web/src/server/utils/checkClickhouseAccess.ts
Labels: size:L

#3978 chore: join postgres state into Clickhouse results and add event_ts
  packages/shared/src/server/definitions.ts
  packages/shared/src/utils/json.ts
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateScoresFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateTracesFromPostgresToClickhouse.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
  worker/src/services/IngestionService/tests/calculateTokenCost.unit.test.ts
  worker/src/services/IngestionService/utils.ts
Labels: size:XL

#3973 feat: add additional traces table filter
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-filter/factory.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  packages/shared/src/tableDefinitions/types.ts
Labels: feat-scores, lgtm, size:L

#3983 chore: add fallback to event timestamp again, log warning
  worker/src/services/IngestionService/index.ts
Labels: size:M

#3984 feat: log all project_ids with missing domain id
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
Labels: feat-log-levels, size:M

#3987 chore: correct number parsing from postgres in clickhouse merge
  packages/shared/src/server/definitions.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:S

#3991 fix: fix zod schema
  web/src/server/api/trpc.ts
Labels: bug, size:XS

#3992 chore: ensure model parameters are cast correctly in clickhouse ingestion
  packages/shared/src/server/definitions.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:XS

#3974 feat: support traces.countAll api with clickhouse
  packages/shared/src/server/queries/clickhouse-filter/clickhouse-filter.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/components/table/use-cases/traces.tsx
  web/src/server/api/routers/traces.ts
Labels: feat-api, size:L

#3993 revert: revert clickhouse trace check
  web/src/server/api/trpc.ts
Labels: size:M
