Repository langfuse/langfuse, pull requests merged in 2025-04, with the labels that each got.

#6294 chore: migrate score charts to new query builder
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/dashboard/components/ChartScores.tsx
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/UserChart.tsx
  web/src/features/dashboard/components/score-analytics/CategoricalScoreChart.tsx
  web/src/features/dashboard/components/score-analytics/NumericScoreTimeSeriesChart.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/query/dataModel.ts
  web/src/features/query/server/queryBuilder.ts
  web/src/pages/project/[projectId]/index.tsx
Labels: feat-dashboard, feat-scores, size:XL

#6300 chore: add batch export env variables to docker-compose.yml
  docker-compose.yml
Labels: size:XS, auto-merge

#6292 feat(playground): persist selected model
  web/src/ee/features/playground/page/hooks/useModelParams.ts
Labels: feat-playground, size:M, auto-merge

#5982 fix(ui): TableWithMetadataWrapper uses contain-layout on its root div so that EvaluatorDetail overflow issue is mitigated
  web/src/ee/features/evals/components/evaluator-detail.tsx
Labels: ui, lgtm, size:XS, auto-merge

#6304 chore: pin dev clickhouse version to 24.3
  docker-compose.dev-azure.yml
  docker-compose.dev.yml
  packages/shared/src/env.ts
  packages/shared/src/server/clickhouse/client.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
Labels: dependencies, size:M

#6307 perf: reduce input validation for dataset items
  web/src/features/public-api/types/datasets.ts
Labels: feat-datasets, size:XS, auto-merge

#6303 chore: remove obsolete dashboard queries
  packages/shared/src/server/repositories/dashboards.ts
  web/src/__tests__/queryBuilderDashboards.servertest.ts
  web/src/features/dashboard/server/dashboard-router.ts
Labels: size:XXL, auto-merge

#6306 feat(prompts): add protected labels
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250401122159_add_prompt_protected_labels_table/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/components/layouts/status-badge.tsx
  web/src/features/audit-logs/auditLog.ts
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/prompts/components/ProtectedLabelsSettings.tsx
  web/src/features/prompts/components/SetPromptVersionLabels/index.tsx
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/features/prompts/server/utils/checkHasProtectedLabels.ts
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/features/rbac/utils/checkProjectAccess.ts
  web/src/pages/project/[projectId]/settings/index.tsx
Labels: feat-prompt-management, lgtm, size:XL

#6314 feat(playground): add tool parsing from Langchain generations
  web/src/components/ChatMessages/ChatMessageComponent.tsx
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: feat-playground, size:M, auto-merge

#6315 perf: reduce search interval for trace existence check
  packages/shared/src/server/repositories/traces.ts
  worker/src/__tests__/evalService.test.ts
Labels: size:XS, auto-merge

#6326 feat(playground): allow uppercase in tool / schema names
  web/src/ee/features/playground/page/components/CreateOrEditLLMSchemaDialog.tsx
  web/src/ee/features/playground/page/components/CreateOrEditLLMToolDialog.tsx
  web/src/features/llm-schemas/validation.ts
  web/src/features/llm-tools/validation.ts
Labels: feat-playground, size:M, auto-merge

#6296 feat(dataset-runs): improve UI/UX of runs and compare page
  web/src/components/layouts/peek-view.tsx
  web/src/components/scores-table-cell.tsx
  web/src/components/table/data-table.tsx
  web/src/components/table/peek.tsx
  web/src/components/table/peek/hooks/useDatasetComparePeekState.ts
  web/src/components/table/peek/hooks/usePeekData.ts
  web/src/components/table/peek/hooks/usePeekView.ts
  web/src/components/table/peek/hooks/useTracePeekNavigation.ts
  web/src/components/table/peek/hooks/useTracePeekState.ts
  web/src/components/table/peek/peek-dataset-compare-detail.tsx
  web/src/components/table/peek/peek-trace-detail.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/ui/side-panel.tsx
  web/src/features/dashboard/lib/score-analytics-utils.ts
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetAnalytics.tsx
  web/src/features/datasets/components/DatasetCompareRunPeekView.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunAggregateColumnHelpers.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/scores/components/ScoreChart.tsx
  web/src/features/scores/components/TimeseriesChart.tsx
  web/src/features/scores/components/multi-select-key-values.tsx
  web/src/features/scores/types.ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
  web/src/utils/numbers.ts
Labels: ui, feat-datasets, size:XXL, auto-merge

#6320 feat(auth): scope cookies to path for custom BASE_PATH deployments
  web/src/server/utils/cookies.ts
Labels: feat-auth, lgtm, size:XS, auto-merge

#6327 fix: blob storage export UI consistency
  web/src/pages/project/[projectId]/settings/integrations/blobstorage.tsx
Labels: ui, size:S, auto-merge

#6328 chore(ui): minor peek ui improvements
  web/src/components/table/peek/peek-trace-detail.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
Labels: ui, size:S, auto-merge

#6329 style(ui): reduce text size of trace/observation name on detail
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
Labels: ui, size:XS, auto-merge

#6337 fix(auth): block duplicate membership invites that lead to sign in issues
  packages/shared/prisma/migrations/20250403153555_membership_invitations_no_duplicates/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/features/rbac/server/membersRouter.ts
Labels: size:M, auto-merge

#6338 fix: include tag filtering support on dashboard
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/query/dashboardUiTableToViewMapping.ts
  web/src/features/query/dataModel.ts
  web/src/features/query/types.ts
Labels: size:L, auto-merge

#6345 fix: improve parsing of tags for otel endpoint
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#6355 security: upgrade nextjs 14.2.26
  ee/package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS, auto-merge

#6356 fix: fix model table provided_model_name
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/hooks.ts
Labels: size:S, auto-merge

#6357 chore: upgrade tiktoken
  pnpm-lock.yaml
  worker/package.json
Labels: dependencies, size:XS, auto-merge

#6359 chore: upgrade playwright tests
  .github/workflows/pipeline.yml
  .gitignore
  web/package.json
  web/src/__e2e__/create-project.spec.ts
  web/src/components/layouts/page-header.tsx
Labels: size:L, auto-merge

#6253 chore: add traces domain layer
  packages/shared/src/domain.ts
  packages/shared/src/index.ts
  packages/shared/src/server/repositories/traces_converters.ts
  packages/shared/src/server/repositories/types.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
  web/src/pages/api/public/sessions/[sessionId].ts
  web/src/pages/api/public/traces/[traceId].ts
  web/src/pages/api/public/traces/index.ts
Labels: size:L, auto-merge

#6353 chore: refactor observations domain
  packages/shared/src/domain.ts
  packages/shared/src/observationsTable.ts
  packages/shared/src/server/queries/createGenerationsQuery.ts
  packages/shared/src/server/queries/index.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/types.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  packages/shared/src/tableDefinitions/tracesTable.ts
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
  web/src/__tests__/async/scores-api.servertest.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/token-usage-badge.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
  web/src/components/trace/lib/helpers.ts
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/datasets/components/NewDatasetItemFromExistingObject.tsx
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/types/observations.ts
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
  web/src/pages/api/public/observations/[observationId].ts
  web/src/pages/api/public/observations/index.ts
  web/src/pages/api/public/traces/[traceId].ts
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/traces.ts
  worker/src/__tests__/traceDeletion.test.ts
  worker/src/features/database-read-stream/types.ts
Labels: size:XL, auto-merge

#6360 chore: create scores domain
  packages/shared/src/domain/index.ts
  packages/shared/src/domain/observations.ts
  packages/shared/src/domain/scores.ts
  packages/shared/src/domain/traces.ts
  packages/shared/src/features/scores/scoreTypes.ts
  packages/shared/src/features/scores/types.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/ingestion/validateAndInflateScore.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/scores_converters.ts
  packages/shared/src/server/repositories/types.ts
  web/src/server/api/routers/scores.ts
  worker/src/ee/evaluation/evalService.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
Labels: feat-scores, size:L, auto-merge

#6363 fix: update dashboard column accesses after query builder updates
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/UserChart.tsx
Labels: feat-dashboard, size:M, auto-merge

#6365 fix: flaky playwright
  web/src/__e2e__/create-project.spec.ts
Labels: lgtm, size:XS, auto-merge

#6364 fix(playground): handle undefined content with toolCalls
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: size:XS, auto-merge

#6371 chore: Increase delete queue processing observability
  worker/src/queues/projectDelete.ts
Labels: size:S, auto-merge

#6373 chore: improve project deletion logs
  worker/src/queues/projectDelete.ts
Labels: size:XS, auto-merge

#6375 perf: Increase batch export timeouts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/__tests__/async/traces-ui-table.servertest.ts
  web/src/server/api/routers/generations/db/getAllGenerationsSqlQuery.ts
  web/src/server/api/routers/traces.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
Labels: size:L, auto-merge

#6378 perf: retry failed S3 deletions
  packages/shared/src/server/services/StorageService.ts
Labels: lgtm, size:S, auto-merge

#6046 feat: add metadata field to scores
  fern/apis/client/definition/score.yml
  fern/apis/server/definition/commons.yml
  fern/apis/server/definition/ingestion.yml
  fern/apis/server/definition/score.yml
  packages/shared/clickhouse/migrations/clustered/0010_add_metadata_column_on_scores.down.sql
  packages/shared/clickhouse/migrations/clustered/0010_add_metadata_column_on_scores.up.sql
  packages/shared/clickhouse/migrations/unclustered/0010_add_metadata_column_on_scores.down.sql
  packages/shared/clickhouse/migrations/unclustered/0010_add_metadata_column_on_scores.up.sql
  packages/shared/prisma/seed.ts
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/domain/scores.ts
  packages/shared/src/domain/traces.ts
  packages/shared/src/features/scores/scoreTypes.ts
  packages/shared/src/features/scores/types.ts
  packages/shared/src/index.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/scores_converters.ts
  packages/shared/src/server/repositories/traces_converters.ts
  packages/shared/src/server/test-utils/tracing-factory.ts
  packages/shared/src/server/utils/metadata_conversion.ts
  web/public/generated/api-client/openapi.yml
  web/public/generated/api/openapi.yml
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
  web/src/__tests__/async/scores-api.servertest.ts
  web/src/__tests__/async/scores-trpc.servertest.ts
  web/src/components/grouped-score-badge.tsx
  web/src/components/scores-table-cell.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/ee/features/evals/components/eval-log.tsx
  web/src/features/datasets/server/service.ts
  web/src/features/public-api/server/scores.ts
  web/src/features/scores/components/ScoreDetailColumnHelpers.tsx
  web/src/features/scores/lib/aggregateScores.ts
  web/src/features/scores/lib/getDefaultScoreData.ts
  web/src/hooks/use-element-visibility.tsx
  web/src/pages/api/public/traces/[traceId].ts
  web/src/server/api/routers/generations/db/getAllGenerationsSqlQuery.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
  worker/src/services/IngestionService/index.ts
Labels: feat-scores, feat-metadata, size:XL

#6384 fix(scores/trpc): byid on deleted score resulted in 5xx error instead of 404
  web/src/server/api/routers/scores.ts
Labels: bug, size:XS, auto-merge

#6385 perf(batch-exports): make page size configurable and set to 500
  worker/src/env.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
Labels: size:S

#6391 fix(prompt-ui): internal type on review chat prompt
  web/src/features/prompts/components/NewPromptForm/ReviewPromptDialog.tsx
Labels: size:XS

#6397 chore: remove beta flag from blob storage integration
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/integrations/blobstorage.tsx
Labels: size:XS, auto-merge

#6398 feat(run-compare): add detail navigation
  web/src/components/scores-table-cell.tsx
  web/src/components/table/peek.tsx
  web/src/components/table/peek/hooks/useDatasetComparePeekNavigation.ts
  web/src/components/table/peek/hooks/usePeekView.ts
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
Labels: feat-datasets, size:M, auto-merge

#6399 fix: update column mapping for categorical score charts
  web/src/features/dashboard/components/score-analytics/CategoricalScoreChart.tsx
Labels: size:XS, auto-merge

#6376 feat(dashboards): add beta preview for customizable dashboards
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250409154352_add_dashboard_data_model/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/prisma/seed.ts
  packages/shared/src/errors/ConflictError.ts
  packages/shared/src/errors/index.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/services/DashboardService/DashboardService.ts
  packages/shared/src/server/services/DashboardService/index.ts
  packages/shared/src/server/services/DashboardService/types.ts
  web/src/components/layouts/routes.tsx
  web/src/features/dashboard/components/DashboardTable.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/features/widgets/chart-library/Chart.tsx
  web/src/features/widgets/chart-library/HorizontalBarChart.tsx
  web/src/features/widgets/chart-library/LineChartTimeSeries.tsx
  web/src/features/widgets/chart-library/PieChart.tsx
  web/src/features/widgets/chart-library/VerticalBarChart.tsx
  web/src/features/widgets/chart-library/VerticalBarChartTimeSeries.tsx
  web/src/features/widgets/chart-library/utils.ts
  web/src/features/widgets/components/DashboardWidget.tsx
  web/src/features/widgets/components/SelectWidgetDialog.tsx
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/features/widgets/components/WidgetTable.tsx
  web/src/features/widgets/index.ts
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
  web/src/pages/project/[projectId]/dashboards/index.tsx
  web/src/pages/project/[projectId]/dashboards/new.tsx
  web/src/pages/project/[projectId]/index.tsx
  web/src/pages/project/[projectId]/widgets/[widgetId]/index.tsx
  web/src/pages/project/[projectId]/widgets/index.tsx
  web/src/pages/project/[projectId]/widgets/new.tsx
  web/src/server/api/root.ts
  web/src/server/api/routers/dashboardWidgets.ts
Labels: feat-dashboard, size:XXL

#6406 build: update end to end tests after dashboard change
  web/src/__e2e__/create-project.spec.ts
Labels: size:XS, auto-merge

#6403 style(compare-runs): remove duplicate run column selector
  web/src/components/table/data-table-column-visibility-filter.tsx
  web/src/features/datasets/components/DatasetRunAggregateColumnHelpers.tsx
Labels: ui, size:L, auto-merge

#6407 fix: access all replicas to create dataset score metrics
  web/src/features/datasets/server/service.ts
Labels: size:M, auto-merge

#6408 chore: add dummy route that accepts all otel metrics calls
  web/src/pages/api/public/otel/v1/metrics/index.ts
Labels: size:S, auto-merge

#6413 fix(dashboards): support all dashboard filters across views
  web/src/features/query/dashboardUiTableToViewMapping.ts
  web/src/features/query/dataModel.ts
Labels: size:M, auto-merge

#6414 chore: disable error log checks in playwright tests
  web/src/__e2e__/create-project.spec.ts
Labels: size:M, auto-merge

#6416 Revert "fix: access all replicas to create dataset score metrics (#6407)
  web/src/features/datasets/server/service.ts
Labels: size:M

#6418 fix: allow sessions filter on widgets
  web/src/features/query/dashboardUiTableToViewMapping.ts
Labels: size:S, auto-merge

#6419 fix: avoid write after end errors on otel metrics endpoint
  web/src/pages/api/public/otel/v1/metrics/index.ts
Labels: bug, size:XS, auto-merge

#6400 feat(compare-runs): Allow for variable row height on compare view
  web/src/components/table/data-table-row-height-switch.tsx
  web/src/components/table/data-table.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
Labels: feat-datasets, size:M, auto-merge

#6433 feat(cloud): switch from crisp to plain for in-app chat support
  .env.prod.example
  .github/workflows/_deploy_ecs_service.yml
  pnpm-lock.yaml
  web/Dockerfile
  web/next.config.mjs
  web/package.json
  web/src/components/nav/support-menu-dropdown.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/env.mjs
  web/src/features/notifications/ErrorNotification.tsx
  web/src/features/projects/components/NewProjectForm.tsx
  web/src/features/setup/components/SetupPage.tsx
  web/src/features/support-chat/PlainChat.tsx
  web/src/features/support-chat/chat.tsx
  web/src/features/support-chat/createSupportEmailHash.ts
  web/src/features/support-chat/index.tsx
  web/src/pages/_app.tsx
  web/src/pages/auth/sign-in.tsx
  web/src/server/auth.ts
  web/types/next-auth.d.ts
Labels: size:XL

#6430 feat: add new organization routes
  fern/apis/organizations/definition/api.yml
  fern/apis/organizations/definition/commons.yml
  fern/apis/organizations/definition/organizations.yml
  fern/apis/organizations/generators.yml
  web/public/generated/organizations-api/openapi.yml
  web/public/generated/organizations-postman/collection.json
  web/src/__tests__/async/organizations-api.servertest.ts
  web/src/pages/api/admin/organizations/[organizationId].ts
  web/src/pages/api/admin/organizations/apiKey.ts
  web/src/pages/api/admin/organizations/index.ts
Labels: feat-api, size:XXL, auto-merge

#6437 feat: allow org api key management via admin api
  fern/apis/organizations/definition/organizations.yml
  packages/shared/src/server/auth/apiKeys.ts
  web/public/generated/organizations-api/openapi.yml
  web/public/generated/organizations-postman/collection.json
  web/src/__tests__/async/organizations-api.servertest.ts
  web/src/features/public-api/server/apiAuth.ts
  web/src/features/public-api/server/projectApiKeyRouter.ts
  web/src/initialize.ts
  web/src/pages/api/admin/organizations/[organizationId]/apiKeys/[apiKeyId].ts
  web/src/pages/api/admin/organizations/[organizationId]/apiKeys/index.ts
  web/src/pages/api/admin/organizations/[organizationId]/index.ts
  web/src/pages/api/admin/organizations/index.ts
Labels: feat-api, size:XL, auto-merge

#6438 feat: allow the creation and deletion of projects using an org api key
  fern/apis/server/definition/projects.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/projects-api.servertest.ts
  web/src/pages/api/public/projects.ts
  web/src/pages/api/public/projects/[projectId]/index.ts
  web/src/pages/api/public/projects/index.ts
Labels: feat-api, size:XL, auto-merge

#6439 feat: create outline of SCIM Users support
  fern/apis/server/definition/scim.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/scim-api.servertest.ts
  web/src/pages/api/public/scim/ResourceTypes.ts
  web/src/pages/api/public/scim/Schemas.ts
  web/src/pages/api/public/scim/ServiceProviderConfig.ts
  web/src/pages/api/public/scim/Users/[id].ts
  web/src/pages/api/public/scim/Users/index.ts
Labels: feat-users, size:XXL, auto-merge

#6449 feat: add endpoints to manage project and organization memberships
  fern/apis/server/definition/memberships.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/memberships-api.servertest.ts
  web/src/pages/api/public/organizations/memberships/index.ts
  web/src/pages/api/public/projects/[projectId]/memberships/index.ts
Labels: feat-api, size:XXL, auto-merge

#6454 chore: add reference to full Langfuse API spec
  fern/apis/organizations/definition/api.yml
  web/public/generated/organizations-api/openapi.yml
  web/public/generated/organizations-postman/collection.json
Labels: feat-api, size:S, auto-merge

#6455 chore: expand project and org name limit to 60 chars
  web/src/__tests__/async/organizations-api.servertest.ts
  web/src/features/auth/lib/projectNameSchema.ts
  web/src/features/organizations/components/ProjectOverview.tsx
  web/src/features/organizations/utils/organizationNameSchema.ts
  web/src/pages/api/public/projects/index.ts
Labels: size:S, auto-merge

#6453 fix(users): adjust pagination calculation for user retrieval
  web/src/server/api/routers/users.ts
Labels: bug, size:XS

#6457 feat: allow management of project api keys via API
  fern/apis/server/definition/projects.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/projects-api.servertest.ts
  web/src/pages/api/admin/organizations/[organizationId]/apiKeys/index.ts
  web/src/pages/api/admin/organizations/apiKey.ts
  web/src/pages/api/public/projects/[projectId]/apiKeys/[apiKeyId].ts
  web/src/pages/api/public/projects/[projectId]/apiKeys/index.ts
Labels: feat-api, size:XXL, auto-merge

#6459 chore(cost-tracking): add support for openai 4.1 models
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:M, auto-merge

#6462 chore: refactor admin-api handling into ee folder
  .github/workflows/pipeline.yml
  web/src/ee/features/admin-api/organizations/apiKeys/apiKeyById.ts
  web/src/ee/features/admin-api/organizations/apiKeys/index.ts
  web/src/ee/features/admin-api/organizations/index.ts
  web/src/ee/features/admin-api/organizations/organizationById.ts
  web/src/ee/features/admin-api/public/organizations/memberships.ts
  web/src/ee/features/admin-api/public/projects/createProject.ts
  web/src/ee/features/admin-api/public/projects/projectById/apiKeys/apiKeyById.ts
  web/src/ee/features/admin-api/public/projects/projectById/apiKeys/index.ts
  web/src/ee/features/admin-api/public/projects/projectById/index.ts
  web/src/ee/features/admin-api/public/projects/projectById/memberships/index.ts
  web/src/features/entitlements/constants/entitlements.ts
  web/src/pages/api/admin/organizations/[organizationId]/apiKeys/[apiKeyId].ts
  web/src/pages/api/admin/organizations/[organizationId]/apiKeys/index.ts
  web/src/pages/api/admin/organizations/[organizationId]/index.ts
  web/src/pages/api/admin/organizations/index.ts
  web/src/pages/api/public/organizations/memberships/index.ts
  web/src/pages/api/public/projects/[projectId]/apiKeys/[apiKeyId].ts
  web/src/pages/api/public/projects/[projectId]/apiKeys/index.ts
  web/src/pages/api/public/projects/[projectId]/index.ts
  web/src/pages/api/public/projects/[projectId]/memberships/index.ts
  web/src/pages/api/public/projects/index.ts
Labels: size:XXL, auto-merge

#6465 chore: improve logging for project deletion queue
  worker/src/queues/projectDelete.ts
Labels: size:XS, auto-merge

#6467 chore: more error logging improvements for project deletions
  packages/shared/src/server/services/StorageService.ts
Labels: size:XS, auto-merge

#6471 fix: plain not available on some page loads
  web/src/features/support-chat/PlainChat.tsx
Labels: size:XS

#6472 fix: window not available at build time
  web/src/components/nav/support-menu-dropdown.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/features/notifications/ErrorNotification.tsx
  web/src/features/support-chat/PlainChat.tsx
Labels: ui, size:S

#6475 fix: preserve new lines when displaying score comments on single trace view
  web/src/components/grouped-score-badge.tsx
Labels: size:XS, auto-merge

#6476 chore: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size:XS, auto-merge

#6481 perf(datasets): split metrics and core data into two endpoints
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:L, auto-merge

#6491 chore(cost-tracking): add support for openai o3 and o4-mini models
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:M, auto-merge

#6492 chore: configure global posthog processing rate limit
  worker/src/app.ts
Labels: size:XS, auto-merge

#6493 chore: add query tags to health check queries
  web/src/pages/api/public/health.ts
Labels: size:S, auto-merge

#6496 fix(llm-keys): ensure default openai model supports all model params
  packages/shared/src/server/llm/types.ts
Labels: bug, size:S

#6497 fix: parse negative integer signs on otel timestamps
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: bug, size:M, auto-merge

#6498 fix(tables): rename usage column to tokens column
  packages/shared/src/observationsTable.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  packages/shared/src/tableDefinitions/tracesTable.ts
Labels: size:S, auto-merge

#6503 chore(ui-forms): ensure name uniqueness enforced on form-level also
  web/src/ee/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/ee/features/experiments/components/CreateExperimentsForm.tsx
  web/src/ee/features/experiments/hooks/useExperimentNameValidation.tsx
  web/src/features/datasets/components/DatasetForm.tsx
  web/src/hooks/useUniqueNameValidation.tsx
Labels: ui, size:L, auto-merge

#6511 feat(dashboard): allow filtering by observation name
  web/src/features/query/dashboardUiTableToViewMapping.ts
  web/src/features/query/dataModel.ts
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
Labels: feat-dashboard, size:M, auto-merge

#6537 chore: confirm pagination behaviour for scores-api
  packages/shared/src/features/scores/scoreTypes.ts
  web/src/__tests__/async/scores-api.servertest.ts
Labels: size:M, auto-merge

#6538 fix: handle data retention on clustered clickhouse deployments
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  worker/src/ee/dataRetention/handleDataRetentionProcessingJob.ts
Labels: size:S, auto-merge

#6524 feat: allow optional metadata param on org / project CRUD API
  fern/apis/organizations/definition/organizations.yml
  fern/apis/server/definition/projects.yml
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250420120553_add_organization_and_project_metadata/migration.sql
  packages/shared/prisma/schema.prisma
  web/public/generated/api/openapi.yml
  web/public/generated/organizations-api/openapi.yml
  web/public/generated/organizations-postman/collection.json
  web/public/generated/postman/collection.json
  web/src/__tests__/async/organizations-api.servertest.ts
  web/src/__tests__/async/projects-api.servertest.ts
  web/src/ee/features/admin-api/organizations/index.ts
  web/src/ee/features/admin-api/organizations/organizationById.ts
  web/src/ee/features/admin-api/public/projects/createProject.ts
  web/src/ee/features/admin-api/public/projects/projectById/index.ts
  web/src/pages/api/public/projects/index.ts
  web/src/pages/organization/[organizationId]/settings/index.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/server/auth.ts
  web/types/next-auth.d.ts
Labels: feat-metadata, size:L, auto-merge

#6541 chore: make custom dashboards available for self-hosters
  web/src/features/entitlements/constants/entitlements.ts
Labels: feat-dashboard, size:XS, auto-merge

#6544 fix(llm-keys): drop top_p from test call
  packages/shared/src/server/llm/types.ts
  web/src/features/llm-api-key/server/router.ts
Labels: size:XS, auto-merge

#6542 chore(model-costs): support alias for all models
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:M, auto-merge

#6547 chore(prompts): throw `400` if prompt name type mismatched
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: feat-prompt-management, size:S, auto-merge

#6534 chore: migrate event_log table to new blob storage table
  packages/shared/clickhouse/migrations/clustered/0011_add_blob_storage_file_log.down.sql
  packages/shared/clickhouse/migrations/clustered/0011_add_blob_storage_file_log.up.sql
  packages/shared/clickhouse/migrations/unclustered/0011_add_blob_storage_file_log.down.sql
  packages/shared/clickhouse/migrations/unclustered/0011_add_blob_storage_file_log.up.sql
  packages/shared/prisma/migrations/20250517173700_add_event_log_migration_background_migration.sql/migration.sql
  packages/shared/src/server/repositories/blobStorageLog.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/index.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
  worker/src/__tests__/dataRetentionProcessing.test.ts
  worker/src/__tests__/projectDeletionProcessing.test.ts
  worker/src/__tests__/scoreDeletion.test.ts
  worker/src/__tests__/traceDeletion.test.ts
  worker/src/backgroundMigrations/migrateEventLogToBlobStorageRefTable.ts
  worker/src/ee/dataRetention/handleDataRetentionProcessingJob.ts
  worker/src/features/scores/processClickhouseScoreDelete.ts
  worker/src/features/traces/processClickhouseTraceDelete.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/queues/projectDelete.ts
  worker/src/scripts/refill-ingestion-events.ts
  worker/src/services/ClickhouseWriter/index.ts
Labels: size:XL

#6552 chore(observations): show model name in table column
  web/src/components/table/use-cases/observations.tsx
Labels: size:XS, auto-merge

#6533 perf: soft delete event logs clickhouse
  package.json
  packages/shared/src/env.ts
  packages/shared/src/server/data-deletion/ingestionFileDeletion.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/repositories/blobStorageLog.ts
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/s3/index.ts
  turbo.json
  worker/src/ee/dataRetention/handleDataRetentionProcessingJob.ts
  worker/src/features/scores/processClickhouseScoreDelete.ts
  worker/src/features/traces/processClickhouseTraceDelete.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/queues/projectDelete.ts
Labels: size:XL, auto-merge

#6545 fix: use source entity environment for annotation scores
  packages/shared/src/server/repositories/traces.ts
  web/src/__tests__/async/sessions-trpc.servertest.ts
  web/src/components/session/index.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemPage.tsx
  web/src/features/scores/components/AnnotateDrawer.tsx
  web/src/features/scores/components/AnnotateDrawerContent.tsx
Labels: lgtm, size:S, auto-merge

#6484 feat(scores): support categorical filters across tables
  packages/shared/src/index.ts
  packages/shared/src/interfaces/filters.ts
  packages/shared/src/observationsTable.ts
  packages/shared/src/server/filterToPrisma.ts
  packages/shared/src/server/queries/clickhouse-sql/clickhouse-filter.ts
  packages/shared/src/server/queries/clickhouse-sql/factory.ts
  packages/shared/src/server/queries/index.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  packages/shared/src/tableDefinitions/sessionsView.ts
  packages/shared/src/tableDefinitions/tracesTable.ts
  packages/shared/src/tableDefinitions/typeHelpers.ts
  packages/shared/src/tableDefinitions/types.ts
  web/src/components/table/use-cases/traces.tsx
  web/src/features/filters/components/filter-builder.tsx
  web/src/features/filters/hooks/useFilterState.ts
  web/src/features/public-api/server/filter-builder.ts
  web/src/server/api/definitions/promptsTable.ts
  web/src/server/api/definitions/scoresTable.ts
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/traces.ts
Labels: feat-scores, size:XL, auto-merge

#6549 perf: include timestamp on trace retrieval on sessions and datasetrunitemstable
  web/src/components/session/index.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
Labels: feat-datasets, feat-sessions, size:S, auto-merge

#6575 chore: improve user identification in observability
  packages/shared/src/server/instrumentation/index.ts
  web/src/features/public-api/server/apiAuth.ts
Labels: size:L, auto-merge

#6583 fix(ui): add deprecated col mapping on traces table for cached filter states
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
Labels: ui, size:S, auto-merge

#6555 perf: race byId queries for traces and observations
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:L, auto-merge

#6584 perf: refactor clickhouseClient creation to singletons
  packages/shared/src/server/clickhouse/client.ts
  packages/shared/src/server/repositories/clickhouse.ts
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/datasets/server/service.ts
  web/src/utils/shutdown.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/services/ClickhouseWriter/index.ts
  worker/src/services/IngestionService/index.ts
  worker/src/utils/shutdown.ts
Labels: size:L, auto-merge

#6592 perf(public-api-traces): raise early error if observations are too large
  packages/shared/src/server/repositories/observations.ts
  web/src/__tests__/async/traces-api.servertest.ts
Labels: feat-api, lgtm, size:M, auto-merge

#6593 perf: reduce optimistic lookback for byid queries
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:XS, auto-merge

#6604 perf(api-traces): increase byId size limit to 5MB
  packages/shared/src/server/repositories/observations.ts
Labels: size:XS

#6607 test(trace-api): fix observations too large test
  web/src/__tests__/async/traces-api.servertest.ts
Labels: size:XS

#6608 feat: add support for score name filters on dashboard
  web/src/features/query/dashboardUiTableToViewMapping.ts
  web/src/features/query/dataModel.ts
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
Labels: feat-dashboard, size:M, auto-merge

#6613 build: prepare deployment for HIPAA compatibility
  .github/workflows/deploy.yml
  packages/shared/src/server/clickhouse/client.ts
  packages/shared/src/server/services/email/organizationInvitation/sendMembershipInvitationEmail.ts
  web/src/components/EnvLabel.tsx
  web/src/env.mjs
  web/src/features/auth/components/AuthCloudRegionSwitch.tsx
Labels: feat-auth, size:M, auto-merge

#6611 fix(api-prompts): use middleware to send response when updating labels
  web/src/features/prompts/server/handlers/promptVersionHandler.ts
Labels: size:M, auto-merge

#6621 feat: add dlx retry queue and service
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/dlxRetryQueue.ts
  packages/shared/src/server/redis/getQueue.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/services/dlx/dlxRetryService.ts
Labels: size:L, auto-merge

#6625 chore(ui): add support for input_text and output_text in markdown rendering
  web/src/components/schemas/ChatMlSchema.ts
Labels: ui, size:XS, auto-merge

#6629 fix: wait for clickhouse mutations to succeed
  packages/shared/clickhouse/migrations/clustered/0012_add_session_id_column_scores.down.sql
  packages/shared/clickhouse/migrations/clustered/0012_add_session_id_column_scores.up.sql
  packages/shared/clickhouse/migrations/clustered/0013_drop_scores_trace_id_index.down.sql
  packages/shared/clickhouse/migrations/clustered/0013_drop_scores_trace_id_index.up.sql
  packages/shared/clickhouse/migrations/clustered/0014_scores_modify_nullable_trace_id_column.down.sql
  packages/shared/clickhouse/migrations/clustered/0014_scores_modify_nullable_trace_id_column.up.sql
  packages/shared/clickhouse/migrations/clustered/0015_add_scores_trace_index.down.sql
  packages/shared/clickhouse/migrations/clustered/0015_add_scores_trace_index.up.sql
  packages/shared/clickhouse/migrations/clustered/0016_add_scores_session_index.down.sql
  packages/shared/clickhouse/migrations/clustered/0016_add_scores_session_index.up.sql
  packages/shared/clickhouse/migrations/unclustered/0012_add_session_id_column_scores.down.sql
  packages/shared/clickhouse/migrations/unclustered/0012_add_session_id_column_scores.up.sql
  packages/shared/clickhouse/migrations/unclustered/0013_drop_scores_trace_id_index.down.sql
  packages/shared/clickhouse/migrations/unclustered/0013_drop_scores_trace_id_index.up.sql
  packages/shared/clickhouse/migrations/unclustered/0014_scores_modify_nullable_trace_id_column.down.sql
  packages/shared/clickhouse/migrations/unclustered/0014_scores_modify_nullable_trace_id_column.up.sql
  packages/shared/clickhouse/migrations/unclustered/0015_add_scores_trace_index.down.sql
  packages/shared/clickhouse/migrations/unclustered/0015_add_scores_trace_index.up.sql
  packages/shared/clickhouse/migrations/unclustered/0016_add_scores_session_index.down.sql
  packages/shared/clickhouse/migrations/unclustered/0016_add_scores_session_index.up.sql
Labels: bug, size:M

#6631 chore(markdown): introduce type guards for markdown rendering
  web/src/components/schemas/ChatMlSchema.ts
  web/src/components/ui/MarkdownViewer.tsx
Labels: ui, size:S, auto-merge

#6635 chore: increase trace id delete observability
  worker/src/queues/traceDelete.ts
Labels: size:S

#6645 feat(datasets): search by name on table
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:M, auto-merge

#6651 chore: add copy ID button to trace/observation preview
  web/src/components/trace/CopyIdsPopover.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
Labels: ui, size:L, auto-merge
