Repository langfuse/langfuse, pull requests merged in 2025-02, with the labels that each got.

#5323 fix: handle multiple number types in otel parser
  web/src/features/otel/server/index.ts
Labels: bug, size:S, auto-merge

#5333 chore(media-api): add instrumentation
  web/src/pages/api/public/media/index.ts
Labels: size:L

#5334 fix: fix observation frontend exception
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/datasets/components/NewDatasetItemFromObservationButton.tsx
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/traces.ts
Labels: bug, size:M, auto-merge

#5335 chore(models): updated price for o1-mini
  worker/src/constants/default-model-prices.json
Labels: size:S, auto-merge

#5336 chore(media): add retries on media record write
  web/src/pages/api/public/media/index.ts
Labels: size:M

#5338 fix: add bedrock throttling exception to retries for evals
  worker/src/features/utilities.ts
Labels: size:XS, auto-merge

#5341 fix(score-analytics): display categorical data in dashboard
  web/src/features/dashboard/lib/score-analytics-utils.ts
Labels: feat-dashboard, size:XS, auto-merge

#5266 chore: upgrade prisma to version 6
  packages/shared/package.json
  pnpm-lock.yaml
  web/Dockerfile
  web/package.json
  worker/package.json
Labels: dependencies, size:S, auto-merge

#5346 fix(filter-ui): support mouse wheel scroll behaviour on desktop and mobile
  web/src/features/filters/components/filter-builder.tsx
Labels: ui, size:S, auto-merge

#5351 chore: add cmd_k_menu:opened event for main menu "go to..." button
  web/src/components/layouts/routes.tsx
  web/src/features/command-k-menu/CommandMenu.tsx
Labels: size:S, auto-merge

#5357 fix(playground): allow o3
  packages/shared/package.json
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  pnpm-lock.yaml
Labels: size:S, auto-merge

#5359 feat(ui): add local iso date with utc on hover and ms precision on traces
  web/src/components/LocalIsoDate.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/prompts/components/prompts-table.tsx
Labels: ui, size:L, auto-merge

#5362 fix: instantiate the ratelimit redis client on first use to avoid connection errors
  web/src/features/public-api/server/RateLimitService.ts
Labels: bug, size:S, auto-merge

#5366 fix: fix flaky dataset test
  web/src/__tests__/async/dataset-service.servertest.ts
Labels: bug, size:XS, auto-merge

#5364 chore: decrease ingestion queue delay outside of date boundaries
  packages/shared/src/server/ingestion/processEventBatch.ts
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: lgtm, size:M, auto-merge

#5370 chore: fix flaky traces-api test
  web/src/__tests__/async/traces-api.servertest.ts
Labels: size:XS, auto-merge

#5380 fix(ui): input changes lost on focus in dataset item edit
  web/src/features/datasets/components/EditDatasetItem.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items/[itemId].tsx
Labels: ui, size:M, auto-merge

#5350 fix(dataset-evals): reference `job.observationId` rather than `sourceObservationId`
  worker/src/ee/evaluation/evalService.ts
Labels: bug, size:S, auto-merge

#5384 fix: model aggregation for daily metrics
  web/src/__tests__/async/daily-metrics-api.servertest.ts
  web/src/features/public-api/server/dailyMetrics.ts
Labels: bug, size:M, auto-merge

#5381 chore: optionally log s3 event bucket uploads in postgres
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250204180200_add_event_log_table/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/utils/eventLog.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
  worker/src/ee/evaluation/evalService.ts
Labels: size:L, auto-merge

#5387 perf: do not load all models by default in the dashboards
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/server/repositories/dashboards.ts
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/ModelSelector.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/hooks.ts
Labels: feat-dashboard, size:L, auto-merge

#5388 chore: remove unused imports
  worker/src/ee/evaluation/evalService.ts
Labels: size:S, auto-merge

#5386 fix(ui-markdown): fallback to json view if markdown parsing is unsucessful
  pnpm-lock.yaml
  web/package.json
  web/src/components/ui/MarkdownViewer.tsx
Labels: ui, dependencies, size:L, auto-merge

#5389 fix: return empty results in dashboard if from is larger than to
  web/src/features/dashboard/server/dashboard-router.ts
Labels: size:S, auto-merge

#5403 feat(model): add playground and eval support for Gemini 2.0 Flash, Gemini 2.0 Flash-Lite, and Gemini 2.0 Pro
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: feat-evals, feat-playground, size:M, auto-merge

#5406 fix: improve working for eval jsonpath selector
  web/src/ee/features/evals/components/evaluator-form.tsx
Labels: size:XS, auto-merge

#5355 ISSUE-5354: Add custom gid and uid support
  web/Dockerfile
  worker/Dockerfile
Labels: size:S

#5405 chore: fetch file list for worker processing from s3 event log
  worker/src/env.ts
  worker/src/queues/ingestionQueue.ts
Labels: size:M, auto-merge

#5407 chore: deduplicate postgres event list by bucketPath
  worker/src/queues/ingestionQueue.ts
Labels: size:XS, auto-merge

#5409 security: upgrade jsonpath-plus
  pnpm-lock.yaml
  worker/package.json
  worker/src/ee/evaluation/evalService.ts
Labels: dependencies, size:XS, auto-merge

#5415 fix: do not run snyk in merge groups
  .github/workflows/snyk.yml
Labels: size:XS, auto-merge

#5420 fix(gemini): pricing units
  worker/src/constants/default-model-prices.json
Labels: size:S, auto-merge

#5314 feat(tables): add select all interface to tables
  packages/shared/src/features/batchAction/types.ts
  packages/shared/src/index.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/batchActionQueue.ts
  packages/shared/src/server/redis/getQueue.ts
  web/src/components/table/data-table-multi-select-actions/data-table-select-all-banner.tsx
  web/src/components/table/data-table-multi-select-actions/trace-table-multi-select-action.tsx
  web/src/components/table/data-table-toolbar.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/useSessionStorage.tsx
  web/src/ee/features/annotation-queues/server/annotationQueueItems.ts
  web/src/features/audit-logs/auditLog.ts
  web/src/features/table/components/TableActionDialog.tsx
  web/src/features/table/components/TableActionMenu.tsx
  web/src/features/table/components/TableActionTargetOptions.tsx
  web/src/features/table/components/TableSelectionManager.tsx
  web/src/features/table/components/targetOptionsQueryMap.tsx
  web/src/features/table/hooks/useSelectAll.ts
  web/src/features/table/server/createBatchActionJob.ts
  web/src/features/table/server/helpers.ts
  web/src/features/table/server/tableRouter.ts
  web/src/features/table/types.ts
  web/src/server/api/root.ts
  web/src/server/api/routers/traces.ts
  worker/src/__tests__/batchAction.test.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/features/batchAction/handleBatchActionJob.ts
  worker/src/features/batchAction/processAddToQueue.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
  worker/src/features/traces/processClickhouseTraceDelete.ts
  worker/src/features/traces/processPostgresTraceDelete.ts
  worker/src/queues/batchActionQueue.ts
  worker/src/queues/traceDelete.ts
Labels: ui, size:XXL, auto-merge

#5422 feat: map additional properties for otel llm spans
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#5430 perf: improve performance for trace.id trpc route
  web/src/__tests__/async/traces-trpc.servertest.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
Labels: size:L, auto-merge

#5431 perf: improve trpc session.id performance
  packages/shared/src/server/repositories/observations.ts
  web/src/__tests__/async/sessions-trpc.servertest.ts
  web/src/server/api/routers/sessions.ts
Labels: size:L, auto-merge

#5437 perf: skip processing of already seen events in worker
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/queues.ts
  worker/src/env.ts
  worker/src/queues/ingestionQueue.ts
Labels: size:M, auto-merge

#5444 fix(model-prices): gemini 2 vertex AI prices
  worker/src/constants/default-model-prices.json
Labels: size:S, auto-merge

#5445 security: upgrade jsonpath-plus
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS, auto-merge

#5449 feat(otel): add input/output and name on traces
  web/src/features/otel/server/index.ts
Labels: size:S, auto-merge

#5448 fix: fix cost calculation discrepancies in dashboards
  packages/shared/src/server/repositories/dashboards.ts
  web/src/__tests__/async/repositories/dashboard-repository.servertest.ts
  web/src/__tests__/test-utils.ts
  web/src/features/dashboard/components/ModelUsageChart.tsx
Labels: bug, size:L, auto-merge

#5461 chore: enable tracing on all platforms
  web/src/observability.config.ts
Labels: size:L, auto-merge

#5460 feat(otel): map traceloop.entity.input/output to input/output
  .github/workflows/snyk.yml
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#5466 chore(datasets): reduce max payload size in csv upload
  web/src/features/datasets/components/PreviewCsvImport.tsx
Labels: size:XS, auto-merge

#5353 fix(dataset-upsert): filter on dataset evals triggered in trace-upsert queue
  worker/src/ee/evaluation/evalService.ts
Labels: size:S, auto-merge

#5474 fix: add clickhouse final for traces grouped by name dashboard
  packages/shared/src/server/repositories/traces.ts
Labels: size:XS, auto-merge

#5471 chore: remove event_log table
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250211102600_drop_event_log_table/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/utils/eventLog.ts
  worker/src/ee/evaluation/evalService.ts
  worker/src/env.ts
  worker/src/queues/ingestionQueue.ts
Labels: size:L, auto-merge

#5472 chore: drop postgres events table
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250211123300_drop_events_table/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/__tests__/test-utils.ts
  worker/src/__tests__/utils.ts
Labels: size:M, auto-merge

#5446 docs: new readme
  README.md
  careers
  demo_thumbnail.jpg
Labels: lgtm, size:L, auto-merge

#5475 security: upgrade json path
  ee/package.json
  package.json
  pnpm-lock.yaml
  worker/package.json
Labels: dependencies, size:XS

#5478 security: upgrade clickhouse migration package
  .github/workflows/pipeline.yml
  web/Dockerfile
Labels: dependencies, size:S

#5477 security: upgrade sentry 8.52.0
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#5482 fix: map token filters for ui table to fitting clickhouse types
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  web/src/__tests__/async/traces-ui-table.servertest.ts
Labels: ui, size:S, auto-merge

#5476 feat: log all created s3 event files in clickhouse
  packages/shared/clickhouse/migrations/clustered/0007_add_event_log.down.sql
  packages/shared/clickhouse/migrations/clustered/0007_add_event_log.up.sql
  packages/shared/clickhouse/migrations/unclustered/0007_add_event_log.down.sql
  packages/shared/clickhouse/migrations/unclustered/0007_add_event_log.up.sql
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/eventLog.ts
  packages/shared/src/server/repositories/index.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/services/ClickhouseWriter/index.ts
  worker/src/services/IngestionService/index.ts
Labels: feat-log-levels, size:L, auto-merge

#5484 chore: link to docs for batch export config errors
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:XS, auto-merge

#5495 chore: hide trace deletion button on cloud until enabled again
  web/src/components/table/use-cases/traces.tsx
Labels: ui, size:M, auto-merge

#5499 chore: add additional attributes to ingestion spans
  packages/shared/src/server/ingestion/processEventBatch.ts
Labels: size:S, auto-merge

#5501 chore: propagate otel trace context to clickhouse spans
  packages/shared/src/server/clickhouse/client.ts
  worker/src/services/ClickhouseWriter/ClickhouseWriter.unit.test.ts
  worker/src/services/ClickhouseWriter/index.ts
Labels: size:M, auto-merge

#5504 fix: delete media and event files from S3 on project delete
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/eventLog.ts
  worker/src/__tests__/dataRetentionProcessing.test.ts
  worker/src/__tests__/projectDeletionProcessing.test.ts
  worker/src/queues/projectDelete.ts
Labels: size:L, auto-merge

#5506 chore: upgrade dd-trace-js
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:S

#5509 fix: delete event files from s3 after retention period end
  packages/shared/src/server/repositories/eventLog.ts
  worker/src/__tests__/dataRetentionProcessing.test.ts
  worker/src/ee/dataRetention/handleDataRetentionProcessingJob.ts
Labels: size:L, auto-merge

#5512 perf(exports): increase max row limit to 1M
  worker/src/env.ts
Labels: size:XS

#5513 chore: revert changes to session storage hook from #5314
  web/src/components/useSessionStorage.tsx
Labels: size:M, auto-merge

#5521 fix(datasets): broken link in compare view
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: size:XS, auto-merge

#5524 chore: re-enable sentry; reverts #5505
  pnpm-lock.yaml
  web/next.config.mjs
  web/package.json
  web/sentry.client.config.ts
  web/src/components/error-page.tsx
  web/src/components/ui/resizable-image.tsx
  web/src/pages/_app.tsx
  web/src/pages/auth/sign-in.tsx
  web/src/utils/api.ts
Labels: size:L, auto-merge

#5527 chore: reduce authed request logging to debug
  web/src/features/public-api/server/createAuthedAPIRoute.ts
Labels: size:XS, auto-merge

#5528 chore: delay project delete queue to allow for remaining events to be processed
  packages/shared/src/server/redis/projectDelete.ts
Labels: size:XS, auto-merge

#5531 perf(tables): truncate large I/O content preview in tables
  web/src/components/ui/CodeJsonViewer.tsx
Labels: ui, size:M, auto-merge

#5530 fix(env): standardize AZURE_AD auth environment variables and add all to .env.prod.example
  .env.prod.example
  web/src/env.mjs
  web/src/server/auth.ts
Labels: size:M, auto-merge

#5532 fix(batch-exports): handle retries on stalled jobs for killed workers
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: bug, size:XS, auto-merge

#5533 fix(model-prices): move gemini prices to Google AI values
  worker/src/constants/default-model-prices.json
Labels: size:XS, auto-merge

#5534 fix(prompts-api): handle unique constraint errors
  web/src/features/prompts/server/handlers/promptsHandler.ts
Labels: bug, lgtm, size:S, auto-merge

#5535 chore: add clickhouse tags to queries
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/package.json
  packages/shared/prisma/seed.ts
  packages/shared/scripts/load-seed.ts
  packages/shared/src/features/evals/types.ts
  packages/shared/src/server/clickhouse/client.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/eventLog.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/features/datasets/server/service.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/services/ClickhouseWriter/index.ts
Labels: feat-tags, size:XL, auto-merge

#5539 chore: increase static page generation timeout nextjs
  web/next.config.mjs
Labels: size:XS, auto-merge

#5538 chore: add clickhouse tags to queries (#5535)
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/package.json
  packages/shared/prisma/seed.ts
  packages/shared/scripts/load-seed.ts
  packages/shared/src/features/evals/types.ts
  packages/shared/src/server/clickhouse/client.ts
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/eventLog.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/features/datasets/server/service.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/services/ClickhouseWriter/index.ts
Labels: feat-dashboard, feat-tags, size:XL, auto-merge

#5393 chore(debt): Add TLS Support for Redis
  .gitignore
  docker-compose.build.yml
  docker-compose.yml
  packages/shared/src/env.ts
  packages/shared/src/server/redis/redis.ts
Labels: size:S

#5550 chore: enhance ingestion api documentation
  fern/apis/server/definition/ingestion.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
Labels: size:L, auto-merge

#5545 chore: Update README.ja.md
  README.ja.md
Labels: docs, size:S, auto-merge

#5551 style(header): adjust minor paddings and relative scroll behaviour
  web/src/components/layouts/container-page.tsx
  web/src/components/layouts/page.tsx
Labels: ui, size:S, auto-merge

#5511 feat(trace-ui): add graph view
  Untitled
  pnpm-lock.yaml
  web/next.config.mjs
  web/package.json
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/index.tsx
  web/src/features/trace-graph-view/components/TraceGraphCanvas.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
  web/src/features/trace-graph-view/types.ts
  web/src/features/trace-graph-view/utils/isLanggraphTrace.ts
  web/src/server/api/routers/traces.ts
Labels: ui, size:L, auto-merge

#5553 fix: change numeric type parsing for sessions table filters
  packages/shared/src/tableDefinitions/mapSessionTable.ts
  web/src/__tests__/async/sessions-trpc.servertest.ts
Labels: size:M, auto-merge

#5555 fix(header): breakpoint header behaviour
  web/src/components/layouts/page-header.tsx
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: ui, size:S, auto-merge

#5557 security: upgrade dompurify
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#5558 security: upgrade release-it
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#5570 security: upgrade dompurify v2
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS, auto-merge

#5584 fix: accept further content type formats on otel endpoint
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: bug, size:M, auto-merge

#5590 style(page-header): optimise for mobile view
  web/src/components/LangfuseLogo.tsx
  web/src/components/deleteButton.tsx
  web/src/components/layouts/page-header.tsx
  web/src/components/nav/app-sidebar.tsx
  web/src/components/ui/sidebar.tsx
  web/src/features/datasets/components/DatasetActionButton.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/datasets/components/DeleteDatasetRunButton.tsx
  web/src/features/datasets/components/DuplicateDatasetButton.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/runs/[runId].tsx
Labels: ui, size:L, auto-merge

#5591 security: upgrade jsonpath plus
  pnpm-lock.yaml
  worker/package.json
Labels: dependencies, size:XS, auto-merge

#5593 chore(page-header): add new `tabsComponent`
  web/src/components/layouts/page-header.tsx
  web/src/ee/features/evals/components/eval-log.tsx
  web/src/ee/features/evals/components/eval-templates-table.tsx
  web/src/ee/features/evals/components/evaluator-table.tsx
  web/src/ee/features/evals/pages/evaluators.tsx
  web/src/ee/features/evals/pages/templates.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/EditDatasetItem.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
  web/src/pages/project/[projectId]/evals/log.tsx
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: feat-datasets, feat-evals, size:L, auto-merge

#5595 security: upgrade jsonpath plus v2
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:S, auto-merge

#5596 style(traces): style traces delete button in more menu in table
  web/src/components/deleteButton.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/index.tsx
Labels: ui, size:M, auto-merge

#5598 chore: remove the unnecessary file
  Untitled
Labels: size:XS, auto-merge

#5599 perf(sessions): display only first 10 users; show rest in paginated popover
  web/src/components/session/index.tsx
  web/src/components/trace/index.tsx
Labels: ui, feat-sessions, size:L, auto-merge

#5609 feat: parse mlflow attributes on otel spans
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#5614 feat: map langfuse data model to further otel attributes
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#5615 chore: remove superfluous container_name overwrites
  docker-compose.build.yml
  docker-compose.dev-azure.yml
  docker-compose.dev.yml
  docker-compose.yml
Labels: size:S, auto-merge

#5617 build: notify slack on failed deployment
  .github/workflows/pipeline.yml
Labels: size:XS

#5620 build: increase nextjs static page generation timeout
  web/next.config.mjs
Labels: size:M

#5634 fix: fix dompurify state dependency
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#5594 fix: re-enable trace deletion and remove trace S3 files
  packages/shared/src/server/repositories/eventLog.ts
  web/src/__tests__/async/traces-trpc.servertest.ts
  web/src/components/deleteButton.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/entitlements/constants/entitlements.ts
  web/src/server/api/routers/traces.ts
  worker/src/__tests__/dataRetentionProcessing.test.ts
  worker/src/__tests__/traceDeletion.test.ts
  worker/src/app.ts
  worker/src/features/batchAction/handleBatchActionJob.ts
  worker/src/features/traces/processClickhouseTraceDelete.ts
  worker/src/queues/traceDelete.ts
Labels: size:XL, auto-merge

#5630 perf: only validate response schema on dev servers
  web/src/features/public-api/server/createAuthedAPIRoute.ts
Labels: feat-api, size:XS, auto-merge

#5639 chore(prompts): support developer message
  packages/shared/src/server/llm/types.ts
  web/src/components/ChatMessages/ChatMessageComponent.tsx
  web/src/components/ChatMessages/index.tsx
Labels: size:M, auto-merge

#5650 chore: replace logger.warning with logger.warn
  worker/src/features/batchExport/handleBatchExportJob.ts
  worker/src/queues/projectDelete.ts
Labels: size:XS, auto-merge

#5656 chore: add environment column to trace_sessions
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250220141500_add_environment_to_trace_sessions/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/__tests__/async/sessions-trpc.servertest.ts
Labels: size:S, auto-merge

#5660 perf: limit concurrency for eval job creations
  worker/src/app.ts
  worker/src/env.ts
  worker/src/features/batchAction/handleBatchActionJob.ts
Labels: feat-evals, size:S, auto-merge

#5663 fix: do not return all executions for eval config list trpc
  web/src/__tests__/async/evals-trpc.servertest.ts
  web/src/ee/features/evals/components/evaluator-table.tsx
  web/src/ee/features/evals/server/router.ts
Labels: size:L, auto-merge

#5665 perf: reduce eval create queue concurrency
  worker/src/env.ts
Labels: size:XS, auto-merge

#5675 fix: do not allow to deactivate eval configs which are only on existing objects
  .github/workflows/pipeline.yml
  web/src/__tests__/async/evals-trpc.servertest.ts
  web/src/ee/features/evals/components/evaluator-detail.tsx
  web/src/ee/features/evals/server/router.ts
Labels: size:L, auto-merge

#5678 style(ui): improvements to prompt details screen
  web/src/components/ChatMessages/index.tsx
  web/src/components/layouts/header.tsx
  web/src/components/layouts/page-header.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/components/prompt-history.tsx
  web/src/features/tag/components/TagMananger.tsx
Labels: ui, feat-prompt-management, size:L, auto-merge

#5661 chore(llmCompletion): support system/developer messages for o3
  packages/shared/src/server/llm/fetchLLMCompletion.ts
Labels: size:S, auto-merge

#5700 fix(public-api): list observations with name filter
  web/src/features/public-api/server/observations.ts
Labels: bug, size:XS, auto-merge

#5709 feat(models): add claude-3-7-sonnet-20250219
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: size:M, auto-merge

#5710 fix: support gzip encoding on otel endpoint
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: bug, size:S, auto-merge

#5711 feat(playground+evals): add Google AI Studio support
  packages/shared/package.json
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  pnpm-lock.yaml
  web/src/ee/features/playground/page/hooks/useModelParams.ts
Labels: feat-evals, feat-playground, size:M

#5717 Revert "fix: return nulls for left-joins for correct session durations (#5697)"
  packages/shared/src/server/clickhouse/client.ts
  web/src/__tests__/async/sessions-ui-table.servertest.ts
Labels: size:M

#5723 chore: track distribution of ingested event body size
  packages/shared/src/server/ingestion/processEventBatch.ts
Labels: size:XS, auto-merge

#5726 fix: exclude clickhouse default date from session duration calc
  packages/shared/src/server/services/sessions-ui-table-service.ts
  web/src/__tests__/async/sessions-ui-table.servertest.ts
Labels: bug, size:M, auto-merge

#5671 feat: process environment in ingestion pipeline
  packages/shared/src/features/annotation/types.ts
  packages/shared/src/features/scores/scoreTypes.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/scores_converters.ts
  packages/shared/src/server/repositories/traces_converters.ts
  packages/shared/src/server/repositories/types.ts
  packages/shared/src/server/test-utils/tracing-factory.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
  web/src/features/otel/server/index.ts
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/server/scores.ts
  web/src/features/public-api/server/traces.ts
  web/src/features/public-api/types/observations.ts
  web/src/features/public-api/types/traces.ts
  web/src/server/api/routers/scores.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:L, auto-merge

#5724 feat(api): add environment property to traces, scores, obs
  fern/apis/server/definition/commons.yml
  web/public/generated/api/openapi.yml
Labels: feat-api, size:M

#5727 fix: show retention settings for self-hosters
  web/src/pages/project/[projectId]/settings/index.tsx
Labels: size:XS, auto-merge

#5706 feat(ui): add onboarding screens for core features
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/trace-sessions.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/components/onboarding/AnnotationQueuesOnboarding.tsx
  web/src/components/onboarding/DatasetsOnboarding.tsx
  web/src/components/onboarding/EvaluatorsOnboarding.tsx
  web/src/components/onboarding/PromptsOnboarding.tsx
  web/src/components/onboarding/ScoresOnboarding.tsx
  web/src/components/onboarding/SessionsOnboarding.tsx
  web/src/components/onboarding/TracesOnboarding.tsx
  web/src/components/onboarding/UsersOnboarding.tsx
  web/src/components/ui/alert.tsx
  web/src/components/ui/splash-screen.tsx
  web/src/ee/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/ee/features/annotation-queues/pages/AnnotationQueues.tsx
  web/src/ee/features/annotation-queues/server/annotationQueues.ts
  web/src/ee/features/billing/components/SupportOrUpgradePage.tsx
  web/src/ee/features/evals/pages/evaluators.tsx
  web/src/ee/features/evals/server/router.ts
  web/src/features/datasets/components/DatasetActionButton.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/pages/project/[projectId]/datasets.tsx
  web/src/pages/project/[projectId]/observations.tsx
  web/src/pages/project/[projectId]/prompts/index.tsx
  web/src/pages/project/[projectId]/scores.tsx
  web/src/pages/project/[projectId]/sessions.tsx
  web/src/pages/project/[projectId]/traces.tsx
  web/src/pages/project/[projectId]/users.tsx
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/users.ts
Labels: ui, size:XXL, auto-merge

#5728 fix: fallback to "default" for missing environment
  packages/shared/src/features/annotation/types.ts
  packages/shared/src/features/scores/scoreTypes.ts
  packages/shared/src/server/repositories/definitions.ts
  web/src/features/public-api/types/observations.ts
  web/src/features/public-api/types/traces.ts
Labels: size:S, auto-merge

#5729 style(prompts): always show edit label button for prompt versions
  web/src/features/prompts/components/SetPromptVersionLabels/index.tsx
Labels: feat-prompt-management, size:S, auto-merge

#5730 chore(ui): minor improvements to onboarding pages
  web/src/components/onboarding/AnnotationQueuesOnboarding.tsx
  web/src/ee/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/ee/features/annotation-queues/pages/AnnotationQueues.tsx
Labels: ui, size:S, auto-merge

#5731 chore(ui): move "configure tracing" to the right in dashboard header
  web/src/pages/project/[projectId]/index.tsx
Labels: ui, size:XS, auto-merge

#5735 fix(api): add environment to ingestion spec
  fern/apis/server/definition/ingestion.yml
  web/public/generated/api/openapi.yml
Labels: size:S

#5737 chore(llm-keys): update bedrock form description
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:XS

#5740 fix(ui): overlapping variables for chat prompt
  web/src/features/prompts/components/prompt-detail.tsx
Labels: ui, size:S, auto-merge

#5744 chore: improved domain handling and early return in signupApiHandler
  web/src/features/auth-credentials/server/signupApiHandler.ts
Labels: size:XS, auto-merge

#5749 feat: map environment to score within eval service
  packages/shared/src/server/repositories/observations.ts
  worker/src/__tests__/evalService.test.ts
  worker/src/ee/evaluation/evalService.ts
Labels: feat-evals, size:L, auto-merge

#5753 fix(model-prices): bedrock claude sonnet 3-7 version
  worker/src/constants/default-model-prices.json
Labels: size:XS

#5760 fix: standardize way to get sso blocked domains
  web/src/features/auth-credentials/server/signupApiHandler.ts
  web/src/server/auth.ts
Labels: lgtm, size:S, auto-merge

#5762 chore: move dashboard button to the right, unify eval headers
  web/src/ee/features/evals/pages/templates.tsx
  web/src/pages/project/[projectId]/evals/log.tsx
  web/src/pages/project/[projectId]/users/[userId].tsx
Labels: ui, size:S, auto-merge

#5761 fix: always return 422 for signup error handler
  web/src/features/auth-credentials/server/signupApiHandler.ts
Labels: size:S, auto-merge

#5772 feat(models): add openai gpt-4.5-preview
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: size:M, auto-merge

#5777 feat: simplify otel input/output and accept string token values
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:L, auto-merge

#5779 chore: add env.HOSTNAME support for worker container
  worker/src/env.ts
  worker/src/index.ts
Labels: size:XS, auto-merge

#5778 fix(ui): overlap on dataset runs screen
  web/src/components/layouts/page-header.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
Labels: ui, size:S, auto-merge

#5780 chore: skip tracing for LLM Api key routes
  web/src/features/llm-api-key/server/router.ts
  web/src/server/api/trpc.ts
Labels: size:XS, auto-merge

#5718 feat(traces): redesign single trace UI
  web/src/components/ItemBadge.tsx
  web/src/components/LocalIsoDate.tsx
  web/src/components/grouped-score-badge.tsx
  web/src/components/layouts/page-header.tsx
  web/src/components/publish-object-switch.tsx
  web/src/components/session/index.tsx
  web/src/components/table/data-table.tsx
  web/src/components/token-usage-badge.tsx
  web/src/components/trace/BreakdownToolTip.tsx
  web/src/components/trace/IOPreview.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/ScoresPreview.tsx
  web/src/components/trace/TracePage.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
  web/src/components/trace/lib/helpers.ts
  web/src/components/ui/badge.tsx
  web/src/ee/features/annotation-queues/components/AnnotationQueueItemPage.tsx
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/auth/hooks.ts
  web/src/features/comments/CommentCountIcon.tsx
  web/src/features/datasets/components/DatasetCompareRunPeekView.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/trace-graph-view/components/TraceGraphCanvas.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
  web/src/pages/project/[projectId]/traces/[traceId].tsx
  web/src/styles/globals.css
Labels: ui, size:XXL, auto-merge

#5784 style(page-header): margins
  web/src/components/layouts/page-header.tsx
Labels: ui, size:XS, auto-merge

#5781 feat: add environment properties on api routes
  fern/apis/server/definition/commons.yml
  fern/apis/server/definition/ingestion.yml
  fern/apis/server/definition/metrics.yml
  fern/apis/server/definition/observations.yml
  fern/apis/server/definition/score.yml
  fern/apis/server/definition/sessions.yml
  fern/apis/server/definition/trace.yml
  packages/shared/src/features/scores/scoreTypes.ts
  packages/shared/src/server/queries/clickhouse-sql/clickhouse-filter.ts
  packages/shared/src/server/repositories/scores.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/daily-metrics-api.servertest.ts
  web/src/__tests__/async/observation-api.servertest.ts
  web/src/__tests__/async/scores-api.servertest.ts
  web/src/__tests__/async/sessions-api.servertest.ts
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/server/dailyMetrics.ts
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/server/scores.ts
  web/src/features/public-api/server/traces.ts
  web/src/features/public-api/types/metrics.ts
  web/src/features/public-api/types/observations.ts
  web/src/features/public-api/types/sessions.ts
  web/src/features/public-api/types/traces.ts
  web/src/pages/api/public/metrics/daily.ts
  web/src/pages/api/public/observations/index.ts
  web/src/pages/api/public/scores/index.ts
  web/src/pages/api/public/sessions/[sessionId].ts
  web/src/pages/api/public/sessions/index.ts
  web/src/pages/api/public/traces/index.ts
Labels: feat-api, size:XXL, auto-merge
