Repository langfuse/langfuse, pull requests merged in 2025-10, with the labels that each got.

#9455 fix(otel): completion start time parsing to handle JSON stringified values
  packages/shared/src/server/otel/OtelIngestionProcessor.ts
  packages/shared/src/server/otel/utils.ts
Labels: bug, size:S, auto-merge

#9459 fix: change tRPC error code for ClickHouse errors
  web/src/server/api/trpc.ts
  web/src/utils/trpcErrorToast.tsx
Labels: bug, size:XS, auto-merge

#9463 fix(llm-schema-dialog): remove unnecessary event handler
  web/src/features/playground/page/components/CreateOrEditLLMSchemaDialog.tsx
Labels: feat-prompt-management, size:S, auto-merge

#9151 chore: clear up unused entities in clickhouse
  packages/shared/clickhouse/migrations/clustered/0027_drop_project_environments_mvs.down.sql
  packages/shared/clickhouse/migrations/clustered/0027_drop_project_environments_mvs.up.sql
  packages/shared/clickhouse/migrations/clustered/0028_drop_traces_null_mvs.down.sql
  packages/shared/clickhouse/migrations/clustered/0028_drop_traces_null_mvs.up.sql
  packages/shared/clickhouse/migrations/clustered/0029_drop_traces_null_and_amt_tables.down.sql
  packages/shared/clickhouse/migrations/clustered/0029_drop_traces_null_and_amt_tables.up.sql
  packages/shared/clickhouse/migrations/unclustered/0027_drop_project_environments_mvs.down.sql
  packages/shared/clickhouse/migrations/unclustered/0027_drop_project_environments_mvs.up.sql
  packages/shared/clickhouse/migrations/unclustered/0028_drop_traces_null_mvs.down.sql
  packages/shared/clickhouse/migrations/unclustered/0028_drop_traces_null_mvs.up.sql
  packages/shared/clickhouse/migrations/unclustered/0029_drop_traces_null_and_amt_tables.down.sql
  packages/shared/clickhouse/migrations/unclustered/0029_drop_traces_null_and_amt_tables.up.sql
Labels: size:XL, auto-merge

#9468 fix: show input/output/total columns in traces table correctly
  web/src/components/table/use-cases/observations.tsx
Labels: bug, size:M, auto-merge

#9456 test(otel): add test for completion start time parsing
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
Labels: size:S, auto-merge

#9477 fix(billing): fix react rule of hooks violation
  web/src/ee/features/billing/components/BillingDiscountView.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/features/organizations/hooks.ts
  web/src/features/projects/hooks.ts
Labels: bug, size:M

#9139 feat(agent-graph): cycle through observations by clicking graph nodes…
  web/src/features/trace-graph-view/buildGraphCanvasData.ts
  web/src/features/trace-graph-view/components/TraceGraphCanvas.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
Labels: ui, size:L, auto-merge

#9496 chore(ui): Rename table view button to "saved views"
  web/src/components/table/table-view-presets/components/data-table-view-presets-drawer.tsx
Labels: ui, size:XS, auto-merge

#9497 chore: remove redundant AI feature sentence
  web/src/features/organizations/components/AIFeatureSwitch.tsx
Labels: ui, size:S, auto-merge

#9538 fix(billing): correctly name column in backfill-cycle-anchor background migration
  worker/src/backgroundMigrations/backfillBillingCycleAnchors.ts
Labels: bug, size:XS

#9493 refactor(fetchLLMCompletion): simplify interface
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/getInternalTracingHandler.ts
  packages/shared/src/server/llm/testModelCall.ts
  packages/shared/src/server/llm/types.ts
  web/src/features/llm-api-key/server/router.ts
  web/src/features/natural-language-filters/server/router.ts
  web/src/features/playground/server/chatCompletionHandler.ts
  worker/src/__tests__/llmConnections.test.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/features/experiments/experimentServiceClickhouse.ts
  worker/src/features/experiments/utils.ts
  worker/src/features/utils/utilities.ts
Labels: feat-api, feat-playground, size:XL, auto-merge

#9491 feat(dataset-compare-view-ui): make cell more digestable
  packages/shared/src/features/scores/interfaces/ui/types.ts
  web/src/components/scores-table-cell.tsx
  web/src/components/table/data-table.tsx
  web/src/components/table/peek.tsx
  web/src/components/table/peek/peek-dataset-compare-detail.tsx
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunAggregateColumnHelpers.tsx
  web/src/features/datasets/contexts/DatasetCompareFieldsContext.tsx
  web/src/features/datasets/contexts/DatasetCompareMetricsContext.tsx
  web/src/features/datasets/hooks/useDatasetRunAggregateColumns.ts
  web/src/features/scores/components/ScoreRow.tsx
  web/src/features/scores/types.ts
Labels: feat-datasets, feat-scores, size:XXL, auto-merge

#9547 fix(billing): enhance free tier usage emails with pricing, reset dates, and CRM integration
  .env.dev.example
  .env.prod.example
  packages/shared/src/server/services/email/usageThresholdSuspension/UsageThresholdSuspensionEmailTemplate.tsx
  packages/shared/src/server/services/email/usageThresholdSuspension/sendUsageThresholdSuspensionEmail.ts
  packages/shared/src/server/services/email/usageThresholdWarning/UsageThresholdWarningEmailTemplate.tsx
  packages/shared/src/server/services/email/usageThresholdWarning/sendUsageThresholdWarningEmail.ts
  packages/shared/src/server/utils/billingCycleHelpers.ts
  web/src/__tests__/billingCycleHelpers.servertest.ts
  worker/src/ee/usageThresholds/thresholdProcessing.ts
  worker/src/env.ts
  worker/src/scripts/send-test-threshold-emails.ts
Labels: size:L, auto-merge

#9560 chore: use simpler to install CH client + doc update
  CONTRIBUTING.md
  packages/shared/clickhouse/scripts/dev-tables.sh
Labels: size:S

#9562 fix(ui): "New Version" instead of "New" on main prompt mgmt CTA button
  web/src/features/prompts/components/prompt-detail.tsx
Labels: size:XS

#9563 feat(trace-ui): add log view with all observations concatenated
  web/src/components/trace/TraceLogView.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/index.tsx
  web/src/components/ui/PrettyJsonView.tsx
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
Labels: feat-log-levels, size:XL, auto-merge

#9561 feat: introduce sidebar filtering UI
  web/src/__tests__/filter-query-encoding-decoding.clienttest.ts
  web/src/components/table/data-table-ai-filters.tsx
  web/src/components/table/data-table-controls.tsx
  web/src/components/table/data-table-toolbar.tsx
  web/src/components/table/key-value-filter-builder.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/ui/slider.tsx
  web/src/features/datasets/components/DatasetRunAggregateColumnHelpers.tsx
  web/src/features/evals/components/evaluator-table.tsx
  web/src/features/evals/components/inner-evaluator-form.tsx
  web/src/features/filters/components/filter-builder.tsx
  web/src/features/filters/config/evaluators-config.ts
  web/src/features/filters/config/observations-config.ts
  web/src/features/filters/config/prompts-config.ts
  web/src/features/filters/config/scores-config.ts
  web/src/features/filters/config/sessions-config.ts
  web/src/features/filters/config/traces-config.ts
  web/src/features/filters/hooks/useSidebarFilterState.tsx
  web/src/features/filters/lib/filter-config.ts
  web/src/features/filters/lib/filter-query-encoding.ts
  web/src/features/prompts/components/prompts-table.tsx
  web/src/hooks/use-environment-filter.tsx
  web/src/pages/project/[projectId]/index.tsx
  web/src/server/api/routers/traces.ts
Labels: ui, size:XXL, auto-merge

#9576 fix(graph): cause freeze through infinite loop
  web/src/__tests__/buildStepData.clienttest.ts
  web/src/features/trace-graph-view/buildStepData.ts
Labels: bug, size:L

#9548 chore: ingest otel events into new events table (dev)
  packages/shared/clickhouse/scripts/dev-tables.sh
  packages/shared/src/server/otel/OtelIngestionProcessor.ts
  packages/shared/src/server/repositories/definitions.ts
  worker/src/env.ts
  worker/src/queues/otelIngestionQueue.ts
  worker/src/services/ClickhouseWriter/index.ts
  worker/src/services/IngestionService/index.ts
Labels: size:XL, auto-merge

#9577 fix: restore missing sessions view filters
  packages/shared/src/server/repositories/trace-sessions.ts
  packages/shared/src/tableDefinitions/sessionsView.ts
  web/src/components/table/use-cases/sessions.tsx
  web/src/features/filters/config/sessions-config.ts
  web/src/server/api/routers/sessions.ts
Labels: size:L, auto-merge

#9583 fix: score filter UI issues
  web/src/__tests__/filter-query-encoding-decoding.clienttest.ts
  web/src/components/table/key-value-filter-builder.tsx
  web/src/features/filters/lib/filter-query-encoding.ts
Labels: bug, size:M

#9589 chore: add filter options for sessions and remove traces final
  packages/shared/package.json
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/traces.ts
Labels: feat-sessions, size:L, auto-merge

#9492 feat: Enable advanced filtering in public API traces endpoint (LFE-3810)
  fern/apis/server/definition/trace.yml
  packages/shared/src/server/index.ts
  packages/shared/src/server/repositories/traces.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/server/traces.ts
  web/src/features/public-api/types/traces.ts
  web/src/pages/api/public/traces/index.ts
Labels: feat-api, size:L, auto-merge

#9551 feat(billing): add configurable spend alerts for paid cloud plans
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20251006173445_add_cloud_spend_alerts/migration.sql
  packages/shared/prisma/migrations/20251006173446_optimize_cloud_spend_alerts_add_index/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/interfaces/cloudConfigSchema.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/cloudSpendAlertQueue.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/services/email/billingAlert/sendBillingAlertEmail.ts
  packages/shared/src/server/services/email/cloudSpendAlert/CloudSpendAlertEmailTemplate.tsx
  packages/shared/src/server/services/email/cloudSpendAlert/sendCloudSpendAlertEmail.ts
  web/src/ee/features/billing/README.md
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/ee/features/billing/components/SpendAlerts/DeleteSpendAlertDialog.tsx
  web/src/ee/features/billing/components/SpendAlerts/SpendAlertDialog.tsx
  web/src/ee/features/billing/components/SpendAlerts/SpendAlertsSection.tsx
  web/src/ee/features/billing/components/SpendAlerts/SpendAlertsTable.tsx
  web/src/ee/features/billing/components/UsageAlerts.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
  web/src/ee/features/billing/server/spendAlertRouter.ts
  web/src/ee/features/billing/server/stripeBillingService.ts
  web/src/ee/features/billing/server/stripeWebhookHandler.ts
  web/src/ee/features/billing/server/usageAlertService.ts
  web/src/features/audit-logs/auditLog.ts
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/server/api/root.ts
  worker/src/app.ts
  worker/src/ee/cloudSpendAlerts/handleCloudSpendAlertJob.ts
  worker/src/ee/cloudUsageMetering/handleCloudUsageMeteringJob.ts
  worker/src/env.ts
  worker/src/queues/cloudSpendAlertQueue.ts
  worker/src/scripts/send-test-spend-alert-emails.ts
Labels: ui, size:XXL, auto-merge, feat-billing

#9592 revert: filter sidebar
  packages/shared/src/server/repositories/trace-sessions.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/sessionsView.ts
  web/src/__tests__/filter-query-encoding-decoding.clienttest.ts
  web/src/components/table/data-table-ai-filters.tsx
  web/src/components/table/data-table-controls.tsx
  web/src/components/table/data-table-toolbar.tsx
  web/src/components/table/key-value-filter-builder.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/ui/slider.tsx
  web/src/features/datasets/components/DatasetRunAggregateColumnHelpers.tsx
  web/src/features/evals/components/evaluator-table.tsx
  web/src/features/evals/components/inner-evaluator-form.tsx
  web/src/features/filters/components/filter-builder.tsx
  web/src/features/filters/config/evaluators-config.ts
  web/src/features/filters/config/observations-config.ts
  web/src/features/filters/config/prompts-config.ts
  web/src/features/filters/config/scores-config.ts
  web/src/features/filters/config/sessions-config.ts
  web/src/features/filters/config/traces-config.ts
  web/src/features/filters/hooks/useSidebarFilterState.tsx
  web/src/features/filters/lib/filter-config.ts
  web/src/features/filters/lib/filter-query-encoding.ts
  web/src/features/prompts/components/prompts-table.tsx
  web/src/hooks/use-environment-filter.tsx
  web/src/pages/project/[projectId]/index.tsx
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
Labels: feat-datasets, feat-evals, feat-scores, feat-sessions, size:XXL, auto-merge

#9595 chore: disable write of eventRaw column in new events table
  packages/shared/src/server/otel/OtelIngestionProcessor.ts
  worker/src/services/IngestionService/index.ts
Labels: size:XS, auto-merge

#9598 fix(trace-ui): keep expand/collapse state across trace peeks
  web/src/components/trace/JsonExpansionContext.tsx
  web/src/components/trace/TraceLogView.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/index.tsx
  web/src/components/ui/PrettyJsonView.tsx
Labels: ui, size:L

#9597 Bug fix: Self-hosted hitting `cloudBilling.getUsage`
  web/src/ee/features/billing/utils/isCloudBilling.ts
Labels: bug, size:XS

#9600 feat(ui): add cloudregion to project/org information in settings
  web/src/pages/organization/[organizationId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/index.tsx
Labels: ui, size:XS, auto-merge

#9605 chore(playground): make action icon buttons clearer
  web/src/features/playground/page/components/MultiWindowPlayground.tsx
  web/src/features/playground/page/components/SaveToPromptButton.tsx
Labels: size:L, auto-merge
