Repository langfuse/langfuse, pull requests merged in 2025-08, with the labels that each got.

#8207 feat(dataset-run-items): reads router
  packages/shared/src/server/repositories/dataset-run-items.ts
  packages/shared/src/server/repositories/scores.ts
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:XL, auto-merge

#8255 build: setup slack alerts on failing CI
  .github/workflows/pipeline.yml
Labels: size:XS

#8264 chore: remove unused sessions query
  packages/shared/src/server/queries/createSessionsAllQuery.ts
  packages/shared/src/server/queries/index.ts
Labels: size:M

#8211 fix(layout): highlight nav items when viewing child routes
  web/src/components/layouts/layout.tsx
Labels: ui, size:S, auto-merge

#8249 chore: migrate additional queries to traces amts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/server/scores.ts
  worker/src/services/IngestionService/README.md
Labels: size:L

#8269 ci: debug docker build issues
  .github/workflows/pipeline.yml
Labels: bug, size:XS

#8274 chore: limit batch sizes of trace deletions
  worker/src/env.ts
  worker/src/queues/traceDelete.ts
Labels: size:S, auto-merge

#8276 Revert "refactor: break up SlackService and move to web/worker packages"
  packages/shared/package.json
  packages/shared/src/server/index.ts
  packages/shared/src/server/services/SlackService.ts
  pnpm-lock.yaml
  web/src/__tests__/async/slack-integration.servertest.ts
  web/src/features/slack/server/oauth-handlers.ts
  web/src/features/slack/server/router.ts
  worker/src/__tests__/slack-processor.test.ts
  worker/src/queues/webhooks.ts
  worker/src/services/SlackService.ts
Labels: size:L, auto-merge

#8283 chore: only show 10 traces for evals
  web/src/components/table/use-cases/traces.tsx
  web/src/features/evals/components/inner-evaluator-form.tsx
Labels: size:S, auto-merge

#8059 feat(llm-connections): remove atla integration
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  web/src/features/playground/page/hooks/useModelParams.ts
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:M, auto-merge

#8285 feat(peek-evaluator-config): add edit mode functionality
  web/src/components/table/peek/peek-evaluator-config-detail.tsx
Labels: feat-evals, size:M, auto-merge

#8267 fix(dataset-run-items): include run metadata for runs without dataset_run_items
  packages/shared/src/server/repositories/dataset-run-items.ts
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:L, auto-merge

#8095 chore: add fern JS SDK generator
  .gitignore
  fern/apis/server/generators.yml
  generated/.gitignore
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-api, size:M, auto-merge

#8288 chore: add experiment tags to clickhouse queries
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/server/scores.ts
  web/src/features/public-api/server/traces.ts
Labels: size:M, auto-merge

#8292 fix(dataset-run-items): fix pagination for consistent ordering across sources
  packages/shared/src/server/repositories/dataset-run-items.ts
  packages/shared/src/tableDefinitions/mapDatasetRunItemsTable.ts
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: bug, size:M, auto-merge

#8301 feat(llm-api-keys): add public api methods
  fern/apis/server/definition/llm-connections.yml
  packages/shared/src/utils/zod.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/llm-connections-api.servertest.ts
  web/src/features/public-api/server/createAuthedProjectAPIRoute.ts
  web/src/features/public-api/types/llm-connections.ts
  web/src/pages/api/public/llm-connections/index.ts
Labels: feat-api, size:XXL, auto-merge

#8315 fix(pagination): allow limit zero again
  packages/shared/src/utils/zod.ts
  web/src/__tests__/async/llm-connections-api.servertest.ts
Labels: bug, size:S, auto-merge

#8322 feat(models): add claude-opus-4-1-20250805
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: feat-datasets, size:S, auto-merge

#8324 chore: refactor IOTableCell
  web/src/components/table/use-cases/models.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/score-configs.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/components/ui/IOTableCell.tsx
  web/src/ee/features/audit-log-viewer/AuditLogsTable.tsx
  web/src/features/automations/components/AutomationExecutionsTable.tsx
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/evals/components/eval-log.tsx
Labels: ui, size:L, auto-merge

#8327 docs: improve api reference for llm-connections api
  fern/apis/server/definition/llm-connections.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
Labels: size:S

#8328 perf: increase clickhouse timeouts for blob storage exports
  packages/shared/src/env.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:S, auto-merge

#8337 chore(evaluator-form): prevent form submission on Enter key press; hide controls in preview
  web/src/components/table/use-cases/traces.tsx
  web/src/features/evals/components/inner-evaluator-form.tsx
Labels: size:S, auto-merge

#8308 chore: move dashboard queries to new AMTs
  packages/shared/src/server/test-utils/clickhouse-helpers.ts
  web/src/__tests__/dashboard-router-pivot-table.servertest.ts
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/__tests__/queryBuilderDashboards.servertest.ts
  web/src/__tests__/queryBuilderSQLI.servertest.ts
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/query/server/queryExecutor.ts
  web/src/pages/api/public/metrics/index.ts
Labels: feat-dashboard, size:XL, auto-merge

#8347 feat(otel): add parsing for Vercel AI SDK
  web/src/components/trace/BreakdownToolTip.tsx
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: feat-api, size:L, auto-merge

#8325 feat(annotation): support assigning users to queues
  fern/apis/server/definition/annotation-queues.yml
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250806100613_add_annotation_queue_assignment_table/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/features/annotation/types.ts
  packages/shared/src/tableDefinitions/types.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/annotation-queue-assignments-api.servertest.ts
  web/src/__tests__/async/generateUserProjectRolesQuery.servertest.ts
  web/src/components/table/data-table.tsx
  web/src/components/ui/multi-select-combobox.tsx
  web/src/features/annotation-queues/components/AnnotationQueuesTable.tsx
  web/src/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/features/annotation-queues/components/UserAssignmentSection.tsx
  web/src/features/annotation-queues/hooks/useSelectedUsers.ts
  web/src/features/annotation-queues/hooks/useUserSearch.ts
  web/src/features/annotation-queues/server/annotationQueueAssignments.ts
  web/src/features/annotation-queues/server/annotationQueues.ts
  web/src/features/audit-logs/auditLog.ts
  web/src/features/public-api/types/annotation-queues.ts
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/features/rbac/server/membersRouter.ts
  web/src/features/rbac/utils/userProjectRole.ts
  web/src/pages/api/public/annotation-queues/[queueId]/assignments.ts
  web/src/server/api/definitions/usersTable.ts
  web/src/server/api/root.ts
  web/src/server/auth.ts
Labels: feat-users, size:XXL

#8364 perf: truncate IO in table overviews and skip internal JSON parse on TRPC
  packages/shared/src/server/index.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/repositories/traces_converters.ts
  packages/shared/src/server/utils/rendering.ts
  web/src/__tests__/async/traces-trpc.servertest.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/server/traces.ts
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
Labels: feat-api, size:L, auto-merge

#8373 fix: check projectMembers:read for trpc members.byProjectId
  web/src/features/rbac/server/membersRouter.ts
Labels: feat-rbac, size:XS, auto-merge

#8378 chore: add openai 5 models
  worker/src/constants/default-model-prices.json
Labels: size:M

#8385 fix(auth): honor NEXT_PUBLIC_BASE_PATH in password reset verification
  web/src/features/auth-credentials/components/ResetPasswordButton.tsx
Labels: size:XS, auto-merge

#8397 chore: remove explicit axios dependency
  ee/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#8402 chore: upgrade slack dependency
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:S, auto-merge

#8399 chore: adjust devcontainer setup to install deps via dockerfile
  .devcontainer.json
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
Labels: dependencies, size:S, auto-merge

#8405 chore: remove trace null deletions
  packages/shared/src/server/repositories/traces.ts
Labels: size:S

#8298 chore: skip S3 list and legacy trace insert based on env flag
  worker/src/env.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/services/IngestionService/index.ts
Labels: size:L, auto-merge

#8396 perf: allow sharding for trace upsert queue
  .env.dev-redis-cluster.example
  packages/shared/src/env.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/redis/traceUpsert.ts
  web/src/__tests__/test-utils.ts
  web/src/pages/api/admin/bullmq/index.ts
  worker/src/__tests__/redisConsumer.test.ts
  worker/src/app.ts
  worker/src/queues/workerManager.ts
  worker/src/services/IngestionService/index.ts
Labels: size:L, auto-merge

#8416 chore(datasets-csv-upload): no longer nest column values if single valid json object
  web/src/features/datasets/lib/csvHelpers.ts
Labels: size:XS, auto-merge

#8419 feat(scores-exports): add author to score exports
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
Labels: feat-scores, size:M, auto-merge

#8438 chore: skip unavailable shards in traces AMT background migration
  worker/src/backgroundMigrations/migrateTracesToTracesAMTs.ts
Labels: size:XS, auto-merge

#8442 fix(model-prices): gpt-5 prices with model date
  packages/shared/src/server/ingestion/modelMatch.ts
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
  worker/src/scripts/upsertDefaultModelPrices.ts
Labels: lgtm, size:L, auto-merge

#8445 fix(dashboards): patch invalid tags filter
  web/src/__tests__/async/metrics-api.servertest.ts
  web/src/features/query/server/queryBuilder.ts
Labels: bug, size:L, auto-merge

#8451 chore: migrate remaining analytics and export queries to traces AMTs
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/features/public-api/server/dailyMetrics.ts
  web/src/features/public-api/server/traces.ts
  worker/src/services/IngestionService/README.md
Labels: feat-scores, size:L, auto-merge

#8454 chore: drop "remove tag" capability from UI
  web/src/features/tag/components/TagInput.tsx
Labels: ui, size:S, auto-merge

#8455 refactor: update create org form validation
  web/src/features/organizations/components/NewOrganizationForm.tsx
  web/src/features/organizations/utils/organizationNameSchema.ts
Labels: ui, size:M, auto-merge

#8459 Revert "perf: stream new records to clickhouse in writer (#8421)"
  worker/src/services/ClickhouseWriter/ClickhouseWriter.unit.test.ts
  worker/src/services/ClickhouseWriter/index.ts
Labels: bug, size:S, auto-merge

#8444 chore: add edit button to dataset items dot menu
  web/src/features/datasets/components/DatasetActionButton.tsx
  web/src/features/datasets/components/DatasetItemsTable.tsx
Labels: feat-datasets, size:M, auto-merge

#7932 feat: Add HTTPS proxy support for LLM API calls
  packages/shared/src/env.ts
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  worker/src/__tests__/proxyAgent.test.ts
Labels: feat-api, size:M

#8466 fix(evals): update trace deletion logic to remove job executions directly
  worker/src/features/traces/processPostgresTraceDelete.ts
Labels: size:S, auto-merge

#8458 chore: limit traces to trace AMT migration to only write into traces_all_amt
  worker/src/backgroundMigrations/migrateTracesToTracesAMTs.ts
Labels: size:L, auto-merge

#8488 chore: allow whitelisting which AMTs can be used
  packages/shared/src/env.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:S, auto-merge

#8489 perf: skip FINAL for traces all route without metrics
  web/src/features/public-api/server/traces.ts
Labels: feat-api, size:XS, auto-merge

#8490 chore: skip body validation for bullmq GET requests
  web/src/pages/api/admin/bullmq/index.ts
Labels: size:S, auto-merge

#8491 fix(evals): redirect and pull data for latest template version post template edit
  web/src/features/evals/components/eval-template-detail.tsx
  web/src/features/evals/components/evaluator-selector.tsx
Labels: bug, size:M, auto-merge

#8494 fix(dataset-runs): implement optimistic concurrency handling for dataset run creation in POST /dataset-run-items
  web/src/features/public-api/server/dataset-runs.ts
Labels: size:S, auto-merge

#8497 chore(dataset-run-items): sunset dual-write phase; do not fall back on PG in CH execution path
  packages/shared/src/server/dataset-run-items/datasetExecution.ts
  packages/shared/src/server/llm/testModelCall.ts
Labels: feat-datasets, size:M, auto-merge

#8513 chore: add projectId to eval processing spans
  worker/src/features/evaluation/evalService.ts
Labels: size:S, auto-merge

#8519 fix(dataset-run-items): set trace creation default to PG for self-hosters
  worker/src/__tests__/experimentsService.test.ts
  worker/src/env.ts
Labels: bug, size:S, auto-merge

#8531 chore(dataset-run-items-rmt): add table with suffix, add background migration from postgres to clickhouse
  packages/shared/clickhouse/migrations/clustered/0024_dataset_run_items.down.sql
  packages/shared/clickhouse/migrations/clustered/0024_dataset_run_items.up.sql
  packages/shared/clickhouse/migrations/unclustered/0024_dataset_run_items.down.sql
  packages/shared/clickhouse/migrations/unclustered/0024_dataset_run_items.up.sql
  packages/shared/prisma/migrations/20250814090100_remove_dataset_run_items_pg_to_ch_background_migration/migration.sql
  packages/shared/prisma/migrations/20250814100100_add_dataset_run_items_rmt_pg_to_ch_background_migration copy/migration.sql
  worker/src/backgroundMigrations/migrateDatasetRunItemsFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateDatasetRunItemsFromPostgresToClickhouseRmt.ts
Labels: size:L, auto-merge

#8537 fix(dataset-run-items): pg table read
  web/src/features/datasets/server/dataset-router.ts
Labels: bug, size:XS, auto-merge

#8507 feat(traces): add more observation types
  CLAUDE.md
  CONTRIBUTING.md
  fern/apis/server/definition/ingestion.yml
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/schema.prisma
  packages/shared/scripts/seeder/utils/clickhouse-seed-constants.ts
  packages/shared/scripts/seeder/utils/data-generators.ts
  packages/shared/src/domain/observations.ts
  packages/shared/src/features/evals/types.ts
  packages/shared/src/server/clickhouse/schemaUtils.ts
  packages/shared/src/server/ingestion/types.ts
  web/public/generated/api/openapi.yml
  web/src/__tests__/async/ingestion-api.servertest.ts
  web/src/__tests__/async/observation-api.servertest.ts
  web/src/__tests__/async/observations-api.servertest.ts
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/components/ItemBadge.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/UserChart.tsx
  web/src/features/dashboard/components/hooks.ts
  web/src/features/otel/server/OtelIngestionProcessor.ts
  web/src/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/public-api/types/observations.ts
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/utils/types.ts
  worker/src/services/IngestionService/index.ts
Labels: feat-datasets, size:XXL, auto-merge

#8540 fix(dataset-run-items): CH execution for dataset-level evals
  packages/shared/src/server/repositories/dataset-run-items.ts
  packages/shared/src/tableDefinitions/mapDatasetRunItemsTable.ts
  web/src/features/datasets/server/dataset-router.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
  worker/src/features/evaluation/evalService.ts
Labels: bug, size:L, auto-merge

#8545 chore(datasets-ui): prefix I/O with "Trace" on runs table in items detail view
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
Labels: size:XS, auto-merge

#8546 fix(ui): hide separator of demo badge when sidebar is collapsed & make envlabel dismissable onClick
  web/src/components/EnvLabel.tsx
  web/src/components/nav/app-sidebar.tsx
Labels: ui, size:S

#8547 chore: update in-product docs links
  web/src/features/public-api/components/QuickstartExamples.tsx
Labels: size:XS, auto-merge

#8553 feat: add membership deletion API endpoints
  fern/apis/server/definition/organizations.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/memberships-api.servertest.ts
  web/src/ee/features/admin-api/server/memberships.ts
  web/src/ee/features/admin-api/server/projects/projectById/memberships/index.ts
  web/src/pages/api/public/organizations/memberships/index.ts
  web/src/pages/api/public/projects/[projectId]/memberships/index.ts
Labels: feat-api, size:L, auto-merge

#8560 chore: upgrade clickhouse-js to 1.12.1
  packages/shared/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#8591 fix(trace-detail): better contrast for selected span
  web/src/components/trace/TraceTree.tsx
Labels: ui, size:XS, auto-merge

#8582 chore(dataset-api-servertest): introduce awaits for async operations and increase timeouts
  .env.dev-azure.example
  .env.dev-redis-cluster.example
  .env.dev.example
  web/src/__tests__/async/datasets-api.servertest.ts
Labels: size:L

#8564 fix: make test data not error UI
  web/src/__tests__/async/ingestion-api.servertest.ts
Labels: bug, size:S, auto-merge

#8608 feat(ui): improved demo app menu buttons and link from home to projectid/traces
  web/src/components/nav/app-sidebar.tsx
  web/src/components/ui/sidebar.tsx
  web/src/features/organizations/components/ProjectOverview.tsx
Labels: ui, size:M, auto-merge

#8628 fix: Coerce SLACK_FETCH_LIMIT to number
  packages/shared/src/env.ts
Labels: bug, size:XS, auto-merge

#8629 fix: calculate correct traces table count
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
  web/src/__tests__/async/traces-trpc.servertest.ts
Labels: bug, size:M

#8595 chore(dataset-run-items): run experiment service test
  worker/src/__tests__/experimentsService.test.ts
Labels: size:XXL, auto-merge

#8631 chore: add debugging logs for otel timestamp parsing errors
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: feat-log-levels, size:M, auto-merge

#8615 perf: split batch to be processed on string length errors in CH writer
  worker/src/services/ClickhouseWriter/ClickhouseWriter.unit.test.ts
  worker/src/services/ClickhouseWriter/index.ts
Labels: size:L, auto-merge

#8647 perf: use uniq instead of count for prompt metrics call
  packages/shared/src/server/repositories/observations.ts
Labels: feat-prompt-management, size:XS, auto-merge

#8661 perf: avoid final modified for traces.countAll via uniq
  packages/shared/src/server/services/traces-ui-table-service.ts
Labels: size:XS

#8670 feat(tracing): map vercel AI sdk observation types
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/ObservationTypeMapper.ts
Labels: feat-api, size:M, auto-merge

#8666 fix(annotation): verify existing CH score data type prior to upsert
  packages/shared/src/server/repositories/scores.ts
  web/src/server/api/routers/scores.ts
Labels: bug, size:XS, auto-merge

#8673 chore: add TERM env to cursor dockerfile
  .cursor/Dockerfile
Labels: size:XS

#8627 feat(dataset-items-ui): allow filtering by metadata keys
  packages/shared/src/tableDefinitions/datasetItemsTable.ts
  packages/shared/src/tableDefinitions/index.ts
  packages/shared/src/types.ts
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/UploadDatasetCsvButton.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/datasets/server/service.ts
  web/src/features/filters/hooks/useFilterState.ts
Labels: feat-datasets, size:L, auto-merge

#8683 fix(otel): override span observation types if generation-like attributes present
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: bug, size:M, auto-merge

#8688 chore: re-enable focus-refetching for data tables
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
Labels: ui, size:S, auto-merge

#8722 chore(datasets): fix flaky test
  web/src/__tests__/async/dataset-service.servertest.ts
Labels: size:L, auto-merge

#8724 chore(datasets): default to reading/writing CH
  packages/shared/src/env.ts
  worker/src/env.ts
Labels: size:XS, auto-merge

#8730 feat(otel): parse vercel ai SDK ai.usage.*
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: feat-api, size:S, auto-merge

#8733 chore(dataset-run-items-seeder): remove PG dataset run item creation path
  packages/shared/scripts/seeder/seed-postgres.ts
  packages/shared/scripts/seeder/utils/data-generators.ts
  packages/shared/scripts/seeder/utils/seeder-orchestrator.ts
  web/src/__tests__/async/dataset-service.servertest.ts
Labels: size:M, auto-merge

#8737 fix: cursor bg agent clock scew (skip check)
  .cursor/Dockerfile
Labels: bug, size:XS

#8738 test(datasets): skip flaky dataset runs test in CI
  web/src/__tests__/async/dataset-service.servertest.ts
Labels: feat-datasets, size:XS, auto-merge

#8744 fix(runs-compare): infinite re-renders on data table
  web/src/components/table/peek.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
Labels: bug, size:M

#8749 fix: make chain coloring unique
  web/src/components/ItemBadge.tsx
Labels: size:XS

#8734 chore: upgrade to node 24
  .github/workflows/pipeline.yml
  .nvmrc
  ee/package.json
  ee/tsconfig.json
  package.json
  packages/config-typescript/nextjs.json
  packages/shared/package.json
  packages/shared/tsconfig.json
  pnpm-lock.yaml
  web/Dockerfile
  web/package.json
  worker/Dockerfile
  worker/package.json
  worker/tsconfig.json
Labels: dependencies, size:L

#8760 chore: fix log comments
  worker/src/services/ClickhouseWriter/index.ts
Labels: size:XS

#8764 chore(cloud): show label that demo is not available only on HIPAA data region
  web/src/features/auth/components/AuthCloudRegionSwitch.tsx
Labels: feat-auth, size:XS, auto-merge

#8753 fix(traces-api): include excluded fields in response with empty values
  fern/apis/server/definition/trace.yml
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/server/traces.ts
Labels: size:M, auto-merge

#8771 chore(datasets): enhance description display in table UI
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DatasetsTable.tsx
Labels: size:S, auto-merge

#8772 chore(peek): navigation event to create browser history entry
  web/src/components/table/peek/hooks/useDatasetComparePeekState.ts
  web/src/components/table/peek/hooks/useObservationPeekState.ts
  web/src/components/table/peek/hooks/usePeekState.ts
  web/src/components/table/peek/hooks/useTracePeekState.ts
Labels: ui, size:XS, auto-merge

#8777 fix(evalQueue): update timeout error handling to match case sensitivity (#8752)
  worker/src/queues/evalQueue.ts
Labels: bug, size:XS, auto-merge

#8797 chore: bump plain sdk 5.10.3
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS, auto-merge

#8802 chore: fix eval attribute assignment
  worker/src/queues/evalQueue.ts
Labels: size:XS, auto-merge

#8818 fix(ui): docs link for remote dataset run
  web/src/features/experiments/components/CreateExperimentsForm.tsx
Labels: size:XS

#8822 fix(agent-graphs): infinite recursion on graph render
  web/src/__tests__/buildStepData.clienttest.ts
  web/src/features/trace-graph-view/buildStepData.ts
Labels: bug, size:M, auto-merge
