Repository langfuse/langfuse, pull requests merged in 2025-07, with the labels that each got.

#7546 feat: add pivot table widget to self-service dashboards
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250625_add_pivot_table_charttype/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/server/services/DashboardService/types.ts
  web/src/__tests__/dashboard-router-pivot-table.servertest.ts
  web/src/__tests__/pivot-table-utils.servertest.ts
  web/src/__tests__/pivot-table.clienttest.tsx
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/query/types.ts
  web/src/features/widgets/chart-library/Chart.tsx
  web/src/features/widgets/chart-library/PivotTable.tsx
  web/src/features/widgets/chart-library/utils.ts
  web/src/features/widgets/components/DashboardWidget.tsx
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/features/widgets/index.ts
  web/src/features/widgets/utils.ts
  web/src/features/widgets/utils/pivot-table-utils.ts
  web/src/pages/project/[projectId]/widgets/[widgetId]/index.tsx
  web/src/pages/project/[projectId]/widgets/new.tsx
Labels: feat-dashboard, size:XXL

#7598 fix(prompts): don't allow placeholders and variable with same name on same prompt version
  web/src/__tests__/prompts.v2.servertest.ts
  web/src/features/playground/page/components/MessagePlaceholderComponent.tsx
  web/src/features/playground/page/components/PromptVariableComponent.tsx
  web/src/features/playground/page/hooks/useNamingConflicts.ts
  web/src/features/prompts/server/actions/createPrompt.ts
Labels: size:L, auto-merge

#7604 chore: fix typos
  .cursor/rules/frontend-features.mdc
  README.cn.md
  README.ja.md
  README.md
  web/src/components/nav/sidebar-notifications.tsx
  web/src/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/pages/auth/sign-in.tsx
Labels: size:S, auto-merge

#7603 feat(prompts): Add search bar to prompts table
  web/src/features/prompts/components/prompts-table.tsx
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: feat-prompt-management, size:L, auto-merge

#7611 refactor: pivot table dropdowns
  web/src/features/widgets/components/WidgetForm.tsx
Labels: ui, size:L

#7619 feat: add tags to search on prompts table
  web/src/features/prompts/components/prompts-table.tsx
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: feat-tags, size:S, auto-merge

#7615 feat(experiments) support for placeholders as message histories
  packages/shared/src/index.ts
  packages/shared/src/utils/prompts.ts
  web/src/features/experiments/components/CreateExperimentsForm.tsx
  web/src/features/experiments/hooks/useExperimentPromptData.ts
  web/src/features/experiments/server/router.ts
  worker/src/__tests__/experimentsService.test.ts
  worker/src/features/experiments/experimentService.ts
Labels: size:L, auto-merge

#7590 exp: write observation and score info to traces_mt
  worker/src/services/IngestionService/README.md
  worker/src/services/IngestionService/index.ts
Labels: size:L, auto-merge

#7628 chore: retry socket hang ups for CH queries
  packages/shared/src/env.ts
  packages/shared/src/server/repositories/clickhouse.ts
Labels: size:L, auto-merge

#7641 chore: improve cursor background agent configuration
  .cursor/Dockerfile
  .cursor/environment.json
  .cursor/rules/general-info.mdc
Labels: size:S

#7640 fix: loading state of csv import button
  web/src/features/datasets/components/PreviewCsvImport.tsx
Labels: bug, ui, size:S, auto-merge

#7647 chore: upgrade langfuse-langchain
  packages/shared/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#7650 fix(scores): update score validation logic to accept inclusive ranges for score config validation
  packages/shared/src/features/scores/interfaces/ingestion/validation.ts
  web/src/__tests__/async/scores-api-v1.servertest.ts
Labels: size:M, auto-merge

#7659 feat(llm-connections): add gemini 2.5 pro and flash GA
  packages/shared/src/server/llm/types.ts
Labels: size:S, auto-merge

#7649 perf: increase ingestion queue retry attempts
  packages/shared/src/server/redis/ingestionQueue.ts
  worker/src/queues/evalQueue.ts
Labels: lgtm, size:XS, auto-merge

#7666 feat(llm-connections): add gemini 2.5 flash lite and gemini 2.5 prices
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: size:M

#7668 feat(ui): Add trace download button, exports trace and observation metadata as json
  web/src/components/trace/index.tsx
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
Labels: ui, size:M, auto-merge

#7684 chore(sentry): restrict loggerLink to development environment only for less noise in sentry
  web/src/utils/api.ts
Labels: size:S, auto-merge

#7690 fix(dataset-run-items-api-spec): correct response type
  fern/apis/server/definition/dataset-run-items.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
Labels: size:S

#7671 chore(dx): unit tests run against their own db
  .env.test.example
  .gitignore
  CONTRIBUTING.md
  package.json
  packages/shared/package.json
  web/package.json
  web/src/__tests__/after-teardown.ts
  web/src/__tests__/test-utils.ts
Labels: size:L, auto-merge

#7698 chore: improve auto selection of automations page
  web/src/features/automations/components/automations.tsx
Labels: size:M, auto-merge

#7700 chore: fix timestamp ordering for amt table
  web/src/features/public-api/server/traces.ts
Labels: size:S, auto-merge

#7703 fix(cloud): update CSP to allow for file upload in support chat
  web/next.config.mjs
Labels: bug, size:XS

#7712 security: upgrade golang-migrate
  .claude/settings.local.json
  .cursor/Dockerfile
  .github/workflows/pipeline.yml
  web/Dockerfile
  worker/src/__tests__/webhooks.test.ts
Labels: dependencies, size:M, auto-merge

#7660 refactor(datasets-compare): implement context for managing selected resource metrics
  web/src/components/table/peek/peek-dataset-compare-detail.tsx
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunAggregateColumnHelpers.tsx
  web/src/features/datasets/contexts/DatasetCompareMetricsContext.tsx
  web/src/features/datasets/hooks/useDatasetRunAggregateColumns.ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: feat-datasets, size:L, auto-merge

#7692 chore(dx): prettier for all
  .husky/pre-commit
  .prettierignore
  CLAUDE.md
  CONTRIBUTING.md
  ee/package.json
  package.json
  packages/config-eslint/library.js
  packages/shared/package.json
  packages/shared/scripts/seeder/seed-postgres.ts
  packages/shared/src/db.ts
  packages/shared/src/encryption/signature.ts
  packages/shared/src/errors/BaseError.ts
  packages/shared/src/server/auth/customSsoProvider.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/llm/compileChatMessages.ts
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/queries/clickhouse-sql/clickhouse-filter.ts
  packages/shared/src/server/redis/batchExport.ts
  packages/shared/src/server/redis/blobStorageIntegrationProcessingQueue.ts
  packages/shared/src/server/redis/cloudUsageMeteringQueue.ts
  packages/shared/src/server/redis/coreDataS3ExportQueue.ts
  packages/shared/src/server/redis/createEvalQueue.ts
  packages/shared/src/server/redis/dataRetentionProcessingQueue.ts
  packages/shared/src/server/redis/dataRetentionQueue.ts
  packages/shared/src/server/redis/datasetRunItemUpsert.ts
  packages/shared/src/server/redis/dlqRetryQueue.ts
  packages/shared/src/server/redis/evalExecutionQueue.ts
  packages/shared/src/server/redis/experimentCreateQueue.ts
  packages/shared/src/server/redis/meteringDataPostgresExportQueue.ts
  packages/shared/src/server/redis/postHogIntegrationProcessingQueue.ts
  packages/shared/src/server/redis/postHogIntegrationQueue.ts
  packages/shared/src/server/redis/projectDelete.ts
  packages/shared/src/server/redis/redis.ts
  packages/shared/src/server/redis/scoreDelete.ts
  packages/shared/src/server/redis/traceDelete.ts
  packages/shared/src/server/redis/traceUpsert.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/StorageService.ts
  packages/shared/src/server/services/email/passwordReset/sendResetPasswordVerificationRequest.tsx
  packages/shared/src/server/utils/DatabaseReadStream.ts
  packages/shared/src/server/utils/transforms/stringify.ts
  packages/shared/src/server/utils/transforms/transformStreamToCsv.ts
  packages/shared/src/server/utils/transforms/transformStreamToJson.ts
  packages/shared/src/server/utils/transforms/transformStreamToJsonl.ts
  packages/shared/src/utils/objects.ts
  packages/shared/src/utils/prompts.ts
  pnpm-lock.yaml
  prettier.config.cjs
  web/package.json
  web/src/__tests__/async/prompts.v2.servertest.ts
  web/src/__tests__/prompts.v1.servertest.ts
  web/src/features/automations/components/automations.tsx
  worker/package.json
  worker/src/__tests__/experimentsService.test.ts
  worker/src/__tests__/signature.test.ts
  worker/src/queues/entityChangeQueue.ts
  worker/src/scripts/createDefaultModelPricesJson.ts
  worker/src/services/ClickhouseWriter/index.ts
  worker/src/utils/shutdown.ts
Labels: size:L, auto-merge

#7717 build: remove swap settings from pipeline config
  .github/workflows/pipeline.yml
Labels: size:S, auto-merge

#7728 chore: print response body webhook errors
  packages/shared/src/server/automations/webhooks.ts
Labels: size:XS, auto-merge

#7725 feat(dashboard): allow breakdown by month
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/query/dataModel.ts
  web/src/features/query/server/queryBuilder.ts
Labels: feat-dashboard, size:L, auto-merge

#7738 feat: Add gen_ai.conversation.id support
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: lgtm, size:L, auto-merge

#7761 chore: add backoff retries to clickhouse writer
  worker/src/services/ClickhouseWriter/index.ts
  worker/src/utils/shutdown.ts
Labels: size:M, auto-merge

#7759 chore(experimentService): extend logging
  worker/src/features/experiments/experimentService.ts
Labels: size:XS, auto-merge

#7762 chore: remove webhook button from single prompt page
  web/src/features/prompts/components/prompt-detail.tsx
Labels: ui, size:XS, auto-merge

#7770 chore(prompt-experiments): upgrade langfuse-langchain
  packages/shared/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#7771 fix(dashboard): allow score numeric value filter and metric
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/query/dataModel.ts
Labels: size:M, auto-merge

#7573 chore(prompt-experiments): set langfuse-native environment
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/pages/api/public/otel/v1/traces/index.ts
  worker/src/__tests__/experimentsService.test.ts
  worker/src/features/experiments/experimentService.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-prompt-management, size:XL, auto-merge

#7796 security: upgrade alpine image
  web/Dockerfile
  worker/Dockerfile
Labels: dependencies, size:XS, auto-merge

#7798 README: update language-specific README files
  README.cn.md
  README.ja.md
  README.kr.md
Labels: size:S, auto-merge

#7802 chore: add migration checks to confirm that required env variables are present
  packages/shared/clickhouse/scripts/up.sh
Labels: size:S, auto-merge

#7819 chore: set default webhook selector without setting the browser history
  web/src/features/automations/components/automations.tsx
Labels: size:M, auto-merge

#7820 fix: remove automations cud for members
  web/src/features/rbac/constants/projectAccessRights.ts
Labels: size:XS, auto-merge

#7815 chore: forbid html elements on names and descriptions via trpc routes
  packages/shared/src/features/annotation/types.ts
  packages/shared/src/features/prompts/validation.ts
  packages/shared/src/utils/zod.ts
  web/src/__tests__/async/prompts.v2.servertest.ts
  web/src/features/auth/lib/projectNameSchema.ts
  web/src/features/auth/lib/signupSchema.ts
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/organizations/utils/organizationNameSchema.ts
  web/src/features/projects/server/projectsRouter.ts
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/features/public-api/server/projectApiKeyRouter.ts
Labels: size:L, auto-merge

#7828 chore: remove local claude settings file
  .claude/settings.local.json
  .gitignore
Labels: size:S, auto-merge

#7842 chore: use --turbo always in web dev
  web/package.json
Labels: size:XS, auto-merge

#7845 ci: all-ci-passed also checks for cancelled status
  .github/workflows/pipeline.yml
Labels: size:XS, auto-merge

#7826 fix(auditlog): patch llmTool and llmSchema records in auditLog
  packages/shared/prisma/migrations/20250711134738_add_patch_llm_tool_schema_audit_logs_background_migration/migration.sql
  web/src/ee/features/admin-api/server/projects/projectById/index.ts
  web/src/features/audit-logs/auditLog.ts
  web/src/features/llm-schemas/server/router.ts
  web/src/features/llm-tools/server/router.ts
  web/src/features/projects/server/projectsRouter.ts
  worker/src/__tests__/patchLLMToolAndLLLMSchemaAuditLogs.test.ts
  worker/src/backgroundMigrations/patchLLMToolAndLLLMSchemaAuditLogs.ts
Labels: lgtm, size:L, auto-merge

#7827 fix(otel): keep hex ids in place in id parsing
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: bug, size:S, auto-merge

#7854 perf: enable API Key and Prompt caching in redis by default
  .github/workflows/pipeline.yml
  packages/shared/src/env.ts
  packages/shared/src/server/redis/redis.ts
  packages/shared/src/server/services/PromptService/index.ts
  web/jest.config.mjs
  web/src/__tests__/promptCache.servertest.ts
  web/src/env.mjs
  web/src/features/public-api/server/apiAuth.ts
Labels: feat-api, size:M, auto-merge

#7863 fix(playground): overflow on large description
  web/src/features/playground/page/components/PlaygroundTools/index.tsx
  web/src/features/playground/page/components/StructuredOutputSchemaSection.tsx
Labels: size:XS

#7864 fix: adjust trace session indexes for faster API accesses
  packages/shared/prisma/migrations/20250714151410_add_trace_session_combined_index/migration.sql
  packages/shared/prisma/migrations/20250714151410_remove_trace_session_created_at_idx/migration.sql
  packages/shared/prisma/migrations/20250714151410_remove_trace_session_project_id_idx/migration.sql
  packages/shared/prisma/migrations/20250714151410_remove_trace_session_updated_at_idx/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/pages/api/public/sessions/index.ts
Labels: feat-sessions, size:M, auto-merge

#7872 fix(otel): handle missing scope name gracefully
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: size:XS, auto-merge

#7884 chore: fix automations scrolling
  web/src/features/automations/components/AutomationSidebar.tsx
  web/src/features/automations/components/automations.tsx
Labels: ui, size:M, auto-merge

#7900 chore: expand logging for large entity truncation
  worker/src/services/ClickhouseWriter/ClickhouseWriter.unit.test.ts
  worker/src/services/ClickhouseWriter/index.ts
Labels: size:M, auto-merge

#7907 perf: import react-icons from one sub path
  web/src/pages/auth/sign-in.tsx
Labels: size:S, auto-merge

#7905 feat: add level filter param to observations api
  fern/apis/server/definition/observations.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/observations-api.servertest.ts
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/types/observations.ts
  web/src/pages/api/public/observations/index.ts
Labels: feat-api, size:L, auto-merge

#7918 feat(model-prices): match cross-region inference profile for claude via bedrock
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:S, auto-merge

#7924 fix: add timeouts to webhooks
  packages/shared/src/server/index.ts
  worker/src/__tests__/webhooks.test.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/queues/webhooks.ts
Labels: size:M

#7942 fix(ui): main menu icons clickable when collapsed
  web/src/components/ui/sidebar.tsx
Labels: ui, size:XS, auto-merge

#7944 chore: fix snyk tags
  .github/workflows/snyk.yml
Labels: size:S, auto-merge

#7970 chore: remove ineffective pnpm configs
  ee/package.json
  packages/shared/package.json
  web/package.json
Labels: dependencies, size:S, auto-merge

#7971 chore: package upgrade vitest
  packages/shared/package.json
  pnpm-lock.yaml
  worker/package.json
Labels: dependencies, size:XS, auto-merge

#7973 chore: full text search for prompts
  web/src/__tests__/async/prompts-trpc.servertest.ts
  web/src/features/prompts/components/prompts-table.tsx
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: feat-prompt-management, size:L, auto-merge

#7976 chore: remove unused tsx
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:XS, auto-merge

#7984 fix(prompts): commitMessage error handling in NewPromptForm
  web/src/features/prompts/components/NewPromptForm/index.tsx
  web/src/features/prompts/components/NewPromptForm/validation.ts
Labels: size:XS, auto-merge

#7958 Add option to add a key prefix for Redis
  packages/shared/src/env.ts
  packages/shared/src/server/redis/redis.ts
Labels: size:XS

#8004 fix: add select all to multi select dropdown
  web/src/features/filters/components/multi-select.tsx
Labels: ui, size:M, auto-merge

#8027 chore: migrate additional session routes to new AMTs
  packages/shared/src/server/repositories/traces.ts
  web/src/__tests__/async/sessions-trpc.servertest.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/sessions.ts
  worker/src/services/IngestionService/README.md
Labels: feat-sessions, size:L, auto-merge

#8033 chore: expose email_from_address and smtp_connection_url in docker-compose
  docker-compose.yml
Labels: size:XS, auto-merge

#8044 fix: fix snyk uploads
  .github/workflows/snyk.yml
Labels: bug, size:S, auto-merge

#8049 fix(otel): parse public attribute for traces
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: bug, size:XS

#8036 perf: replace prisma upsert with raw query
  worker/src/services/IngestionService/index.ts
Labels: size:M

#7661 feat: multi window playground
  web/src/components/ChatMessages/index.tsx
  web/src/components/ModelParameters/index.tsx
  web/src/features/playground/page/components/CollapsibleSection.tsx
  web/src/features/playground/page/components/ConfigurationDropdowns.tsx
  web/src/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/playground/page/components/MessagePlaceholders.tsx
  web/src/features/playground/page/components/Messages.tsx
  web/src/features/playground/page/components/MultiWindowPlayground.tsx
  web/src/features/playground/page/components/PlaygroundTools/index.tsx
  web/src/features/playground/page/components/ResetPlaygroundButton.tsx
  web/src/features/playground/page/components/SaveToPromptButton.tsx
  web/src/features/playground/page/components/StructuredOutputSchemaSection.tsx
  web/src/features/playground/page/components/Variables.tsx
  web/src/features/playground/page/context/index.tsx
  web/src/features/playground/page/hooks/useModelParams.ts
  web/src/features/playground/page/hooks/usePersistedWindowIds.ts
  web/src/features/playground/page/hooks/usePlaygroundCache.ts
  web/src/features/playground/page/hooks/usePlaygroundWindowSize.ts
  web/src/features/playground/page/hooks/useWindowCoordination.ts
  web/src/features/playground/page/index.tsx
  web/src/features/playground/page/playground.tsx
  web/src/features/playground/page/storage/keys.ts
  web/src/features/playground/page/storage/windowStorage.ts
  web/src/features/playground/page/types.ts
Labels: feat-playground, size:XXL, auto-merge

#8058 fix(datasets-table): don't table render json here
  web/src/components/grouped-score-badge.tsx
  web/src/components/scores-table-cell.tsx
  web/src/components/ui/CodeJsonViewer.tsx
Labels: size:S, auto-merge

#8053 perf: extend model cache duration and invalidate on model changes
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/modelMatch.ts
  web/src/pages/api/public/models/index.ts
  web/src/server/api/routers/models.ts
  worker/src/__tests__/modelMatch.test.ts
  worker/src/env.ts
  worker/src/services/IngestionService/index.ts
Labels: size:L

#8076 chore: remove trivy
  .github/workflows/trivy.yml
Labels: size:M, auto-merge

#8085 chore: remove delay for otel
  packages/shared/src/server/ingestion/processEventBatch.ts
Labels: size:XS

#8080 fix(playground): api key link should show llm connection
  web/src/components/ModelParameters/LLMApiKeyComponent.tsx
Labels: size:XS, auto-merge

#8056 chore: migrate remaining trace reads to AMT
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  worker/src/services/IngestionService/README.md
Labels: size:XL, auto-merge

#8092 chore: bump clickhouse client to 1.12.0
  packages/shared/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#8097 chore: Remove add window button and its imports
  web/src/features/playground/page/index.tsx
Labels: size:S, auto-merge

#8099 fix(trace-table): expanded state and make it fast!
  web/src/components/trace/IOPreview.tsx
  web/src/components/ui/PrettyJsonView.tsx
Labels: size:XL, auto-merge

#7959 fix: Unclustered migrations scripts should not have any 'ON CLUSTER' instructions
  packages/shared/clickhouse/migrations/unclustered/0006_add_user_id_index.down.sql
Labels: bug, lgtm, size:XS

#8106 fix(trace): show linebreaks in only text markdown view
  web/src/components/ui/MarkdownViewer.tsx
Labels: bug, size:XS, auto-merge

#8094 feat(experiments): support remote experiment trigger
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250724114251_add_webhooks_datasets/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/experiments/components/CreateExperimentsForm.tsx
  web/src/features/experiments/components/PromptExperimentsForm.tsx
  web/src/features/experiments/components/RemoteExperimentTriggerModal.tsx
  web/src/features/experiments/components/RemoteExperimentUpsertForm.tsx
  web/src/features/experiments/types.ts
  web/src/features/experiments/utils/format.ts
  web/src/features/public-api/types/datasets.ts
  web/src/pages/api/public/datasets.ts
  web/src/pages/api/public/datasets/[name]/index.ts
  web/src/pages/api/public/v2/datasets/[datasetName]/index.ts
  web/src/pages/api/public/v2/datasets/index.ts
Labels: feat-evals, size:XXL, auto-merge

#8108 fix: fix automation updates
  .devcontainer.json
  packages/shared/src/server/repositories/automation-repository.ts
Labels: size:M, auto-merge

#8115 fix(experiments): update loading condition in CreateExperimentsForm to check for datasetId
  web/src/features/experiments/components/CreateExperimentsForm.tsx
Labels: size:XS, auto-merge

#8116 chore: increase observability and delay of eval executions
  packages/shared/src/server/queues.ts
  web/src/features/experiments/server/router.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/features/utils/retry-handler.ts
  worker/src/queues/evalQueue.ts
  worker/src/queues/experimentQueue.ts
  worker/src/queues/utils/delays.ts
Labels: feat-evals, size:M, auto-merge

#8117 chore: fix eval event envelope timestmp
  worker/src/features/utils/retry-handler.ts
Labels: size:XS

#8118 chore: improve evals logging
  worker/src/features/utils/retry-handler.ts
Labels: size:XS

#8119 chore: fix date parsing for eval retries
  worker/src/features/utils/retry-handler.ts
  worker/src/queues/evalQueue.ts
Labels: size:S

#8122 fix(ingestion): cached model not found
  packages/shared/src/server/ingestion/modelMatch.ts
Labels: size:XS, auto-merge

#8132 chore: adjust sampling metric
  packages/shared/src/server/ingestion/processEventBatch.ts
Labels: size:S

#8134 fix(evaluator): update button label based on form mode
  web/src/features/evals/components/inner-evaluator-form.tsx
Labels: bug, size:XS, auto-merge

#8137 chore: ingest secondary ingestion queue data
  web/src/pages/api/admin/bullmq/index.ts
Labels: size:M, auto-merge

#8143 chore: remove ingestion via bullmq
  web/src/pages/api/admin/bullmq/index.ts
Labels: size:L

#8098 chore: improve webhook retries
  packages/shared/src/domain/automations.ts
  packages/shared/src/server/repositories/automation-repository.ts
  web/src/__tests__/async/automations-trpc.servertest.ts
  web/src/features/automations/server/router.ts
  web/src/features/automations/server/webhookHelpers.ts
  worker/package.json
  worker/src/__tests__/webhooks.test.ts
  worker/src/queues/webhooks.ts
Labels: size:L, auto-merge

#8074 feat(dataset-run-items): implement deletion for CH writes
  packages/shared/src/server/dataset-run-items/addToDeleteQueue.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/datasetDelete.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/repositories/dataset-run-items.ts
  packages/shared/src/server/repositories/index.ts
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DeleteDatasetRunButton.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/pages/api/public/datasets/[name]/runs/[runName].ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/runs/[runId].tsx
  worker/src/app.ts
  worker/src/env.ts
  worker/src/features/datasets/processClickhouseDatasetDelete.ts
  worker/src/queues/datasetDelete.ts
  worker/src/queues/projectDelete.ts
Labels: feat-datasets, size:L, auto-merge

#8164 fix(members-table): update table column visibility and order logic based on project context
  web/src/features/rbac/components/MembersTable.tsx
Labels: feat-rbac, size:S, auto-merge

#8165 fix: add queue prefix to webhook queue
  packages/shared/src/server/redis/webhookQueue.ts
Labels: size:XS, auto-merge

#8169 feat(annotation-queues): add support for batch adding sessions to annotation queues
  packages/shared/src/features/batchAction/types.ts
  packages/shared/src/server/queues.ts
  web/src/components/table/use-cases/sessions.tsx
  web/src/features/annotation-queues/server/annotationQueueItems.ts
  web/src/features/table/components/targetOptionsQueryMap.tsx
  worker/src/features/batchAction/handleBatchActionJob.ts
  worker/src/features/batchAction/processAddToQueue.ts
Labels: feat-sessions, size:L, auto-merge

#8177 fix(markdown-rendering): tighter rendering
  packages/shared/scripts/seeder/utils/markdown.txt
  web/src/components/ui/MarkdownViewer.tsx
Labels: ui, size:L, auto-merge

#8181 fix(markdown): don't break after list item number
  web/src/components/ui/MarkdownViewer.tsx
Labels: bug, size:S, auto-merge

#8187 fix(eval): trace filter preview enable dynamic sorting based on control visibility
  web/src/components/table/use-cases/traces.tsx
Labels: bug, size:M, auto-merge

#8174 fix: set explicit ES2021 target in tsconfig to support Unicode regex
  worker/tsconfig.json
Labels: bug, lgtm, size:XS, auto-merge

#8188 fix(playground): enable jumpt to playground for gemini
  packages/shared/src/server/llm/types.ts
  web/src/components/ChatMessages/ChatMessageComponent.tsx
  web/src/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: bug, size:M, auto-merge

#8073 Feat slack integration
  .env.dev.example
  packages/shared/package.json
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250717150100_add_slack_integration/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/domain/automations.ts
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/repositories/automation-repository.ts
  packages/shared/src/server/services/SlackService.ts
  pnpm-lock.yaml
  web/package.json
  web/public/icon1024.png
  web/src/__tests__/async/automations-trpc.servertest.ts
  web/src/__tests__/async/slack-integration.servertest.ts
  web/src/env.mjs
  web/src/features/audit-logs/auditLog.ts
  web/src/features/automations/components/AutomationButton.tsx
  web/src/features/automations/components/AutomationDetails.tsx
  web/src/features/automations/components/AutomationSidebar.tsx
  web/src/features/automations/components/actions/ActionHandlerRegistry.ts
  web/src/features/automations/components/actions/SlackActionForm.tsx
  web/src/features/automations/components/actions/SlackActionHandler.ts
  web/src/features/automations/components/actions/WebhookActionForm.tsx
  web/src/features/automations/components/actions/index.ts
  web/src/features/automations/components/automationForm.tsx
  web/src/features/automations/components/automations.tsx
  web/src/features/automations/server/router.ts
  web/src/features/automations/server/webhookHelpers.ts
  web/src/features/slack/README.md
  web/src/features/slack/app_manifest.json
  web/src/features/slack/components/ChannelSelector.tsx
  web/src/features/slack/components/SlackConnectButton.tsx
  web/src/features/slack/components/SlackConnectionCard.tsx
  web/src/features/slack/components/SlackDisconnectButton.tsx
  web/src/features/slack/components/SlackTestMessageButton.tsx
  web/src/features/slack/server/oauth-handlers.ts
  web/src/features/slack/server/router.ts
  web/src/pages/api/public/slack/install/index.ts
  web/src/pages/api/public/slack/oauth/index.ts
  web/src/pages/project/[projectId]/prompts/[[...folder]].tsx
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/integrations/slack.tsx
  web/src/server/api/root.ts
  worker/package.json
  worker/src/__tests__/promptVersionProcessor.test.ts
  worker/src/__tests__/slack-message-builder.test.ts
  worker/src/__tests__/slack-processor.test.ts
  worker/src/__tests__/webhooks.test.ts
  worker/src/features/entityChange/promptVersionProcessor.ts
  worker/src/features/slack/slackMessageBuilder.ts
  worker/src/queues/webhooks.ts
Labels: size:XXL

#7903 feat(cloud): add billing alerts
  packages/shared/src/interfaces/cloudConfigSchema.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/services/email/billingAlert/BillingAlertEmailTemplate.tsx
  packages/shared/src/server/services/email/billingAlert/sendBillingAlertEmail.ts
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/ee/features/billing/components/UsageAlerts.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
  web/src/ee/features/billing/server/stripeWebhookApiHandler.ts
  web/src/ee/features/billing/server/usageAlertService.ts
  web/src/features/entitlements/constants/entitlements.ts
Labels: feat-cost-tracking, size:XXL, auto-merge

#8191 fix(json-view): smart retain collapsed/expanded state of json table view
  CLAUDE.md
  web/src/components/table/utils/jsonExpansionUtils.ts
  web/src/components/trace/IOPreview.tsx
  web/src/components/trace/JsonExpansionContext.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/index.tsx
  web/src/components/ui/PrettyJsonView.tsx
Labels: size:XXL, auto-merge, feature

#8208 fix: slack channel search component
  web/src/features/slack/components/ChannelSelector.tsx
Labels: bug, size:XS

#8189 fix(llm-conenctions): drop system message from test call
  web/src/features/llm-api-key/server/router.ts
Labels: bug, size:XS, auto-merge

#8209 fix(json-table): render links clickable
  packages/shared/src/utils/zod.ts
  web/src/components/ui/PrettyJsonView.tsx
Labels: ui, size:M

#8179 feat(dataset-run-items): support reads for public APIs
  packages/shared/src/index.ts
  packages/shared/src/server/clickhouse/schema.ts
  packages/shared/src/server/repositories/dataset-run-items.ts
  packages/shared/src/tableDefinitions/index.ts
  packages/shared/src/tableDefinitions/mapDatasetRunItemsTable.ts
  web/src/features/public-api/server/dataset-run-items.ts
  web/src/features/public-api/types/datasets.ts
  web/src/pages/api/public/dataset-run-items.ts
  web/src/pages/api/public/datasets/[name]/runs/[runName].ts
Labels: feat-datasets, size:L, auto-merge

#8234 feat: allow redis username overwrites via env variables
  .env.prod.example
  packages/shared/src/env.ts
  packages/shared/src/server/redis/redis.ts
Labels: feat-auth, size:XS

#8215 chore: allow return from aggregatingmergetrees without experiments
  packages/shared/src/server/clickhouse/measureAndReturn.ts
Labels: size:XS, auto-merge

#8225 fix(json-view): tighter ChatML validation
  web/src/components/ui/PrettyJsonView.tsx
Labels: size:S, auto-merge

#8238 chore: patch docs for ingestion replay
  worker/src/scripts/replayIngestionEvents/README.md
  worker/src/scripts/replayIngestionEvents/s3-ingestion-event-replay.ts
Labels: size:S, auto-merge

#8236 feat: allow PUT operations on SCIM users endpoint
  web/src/__tests__/async/scim-api.servertest.ts
  web/src/pages/api/public/scim/Users/[id].ts
  web/src/pages/api/public/scim/Users/index.ts
Labels: feat-users, size:L, auto-merge

#8242 chore: correctly parse input and output on traces_mt ingestion
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:S

#8245 chore(dataset-run-items): add background migration for DRI
  packages/shared/prisma/migrations/20250731100100_add_dataset_run_items_pg_to_ch_background_migration/migration.sql
Labels: size:XS

#8228 fix(dataset-items): add placeholder text for new items
  web/src/features/datasets/components/NewDatasetItemForm.tsx
Labels: size:XS

#8247 refactor: break up SlackService and move to web/worker packages
  packages/shared/package.json
  packages/shared/src/server/index.ts
  pnpm-lock.yaml
  web/src/__tests__/async/slack-integration.servertest.ts
  web/src/features/slack/server/oauth-handlers.ts
  web/src/features/slack/server/router.ts
  web/src/server/services/SlackService.ts
  worker/src/__tests__/slack-processor.test.ts
  worker/src/queues/webhooks.ts
  worker/src/services/SlackService.ts
Labels: size:L, auto-merge

#8227 fix(json-view): truncate cell after 2k chacacters
  web/src/components/table/ValueCell.tsx
  web/src/components/ui/PrettyJsonView.tsx
Labels: bug, size:L, auto-merge
