Repository langfuse/langfuse, pull requests merged in 2025-06, with the labels that each got.

#7101 fix(default-model): allow set up flow to add LLM API key
  web/src/ee/features/evals/pages/default-evaluation-model.tsx
Labels: size:XS, auto-merge

#7103 fix(projects-api-docs): retentionDays to optional
  fern/apis/server/definition/projects.yml
  web/public/generated/api/openapi.yml
Labels: size:S

#7105 chore: sort dataset (run) items by `created_at` and `id`
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:XS, auto-merge

#7116 security: bump tar-fs, rollup version
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#7127 fix(otel): set trace io from root span
  web/src/features/otel/server/index.ts
Labels: size:XS, auto-merge

#7123 chore: add opt-out flag from queue length metric checks
  worker/src/env.ts
  worker/src/queues/workerManager.ts
Labels: size:M, auto-merge

#7130 chore: allow annotation queues on FOSS
  web/src/features/entitlements/constants/entitlements.ts
Labels: size:XS, auto-merge

#7135 feat: add support for new OTEL semantic event types
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:L, auto-merge

#7136 fix(ee): pro plan label
  packages/shared/src/features/entitlements/plans.ts
  web/src/components/VersionLabel.tsx
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/entitlements/server/getPlan.ts
  web/src/features/public-api/server/RateLimitService.ts
Labels: size:S, auto-merge

#7137 chore(evals): implement update confirmation for default evaluation model
  web/src/features/evals/pages/default-evaluation-model.tsx
Labels: size:L, auto-merge

#7153 chore: include LANGFUSE_USE_AZURE_BLOB in docker-compose options
  docker-compose.yml
Labels: size:XS, auto-merge

#7155 fix(otel): read resourceAttributes for release attribute
  web/src/features/otel/server/index.ts
Labels: size:XS, auto-merge

#7154 feat(dialog): add sticky header and footer
  web/src/components/table/table-view-presets/components/data-table-view-presets-drawer.tsx
  web/src/components/ui/command.tsx
  web/src/components/ui/dialog.tsx
  web/src/components/ui/input-command.tsx
  web/src/components/ui/popover.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/features/annotation-queues/components/DeleteAnnotationQueueButton.tsx
  web/src/features/auth/components/AuthCloudRegionSwitch.tsx
  web/src/features/dashboard/components/EditDashboardDialog.tsx
  web/src/features/dashboard/components/SelectDashboardDialog.tsx
  web/src/features/datasets/components/DatasetActionButton.tsx
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetForm.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DeleteDatasetRunButton.tsx
  web/src/features/datasets/components/NewDatasetItemButton.tsx
  web/src/features/datasets/components/NewDatasetItemForm.tsx
  web/src/features/datasets/components/PreviewCsvImport.tsx
  web/src/features/datasets/components/UploadDatasetCsv.tsx
  web/src/features/evals/components/eval-templates-table.tsx
  web/src/features/evals/components/evaluator-table.tsx
  web/src/features/evals/components/select-evaluator-list.tsx
  web/src/features/evals/components/template-form.tsx
  web/src/features/experiments/components/CreateExperimentsForm.tsx
  web/src/features/feedback/component/FeedbackButton.tsx
  web/src/features/organizations/components/DeleteOrganizationButton.tsx
  web/src/features/playground/page/components/CreateOrEditLLMSchemaDialog.tsx
  web/src/features/playground/page/components/CreateOrEditLLMToolDialog.tsx
  web/src/features/projects/components/DeleteProjectButton.tsx
  web/src/features/projects/components/TransferProjectButton.tsx
  web/src/features/prompts/components/NewPromptForm/ReviewPromptDialog.tsx
  web/src/features/prompts/components/PromptSelectionDialog.tsx
  web/src/features/prompts/components/PromptVersionDiffDialog.tsx
  web/src/features/prompts/components/duplicate-prompt.tsx
  web/src/features/public-api/components/ApiKeyList.tsx
  web/src/features/public-api/components/CreateApiKeyButton.tsx
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
  web/src/features/public-api/components/LLMApiKeyList.tsx
  web/src/features/rbac/components/CreateProjectMemberButton.tsx
  web/src/features/scores/components/CreateScoreConfigButton.tsx
  web/src/features/table/components/TableActionDialog.tsx
  web/src/features/widgets/components/SelectWidgetDialog.tsx
Labels: ui, size:XXL, auto-merge

#7126 perf(traces-table): improve performance
  web/src/components/table/data-table.tsx
  web/src/components/table/peek.tsx
  web/src/components/table/peek/hooks/usePeekData.ts
  web/src/components/table/peek/hooks/usePeekView.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
Labels: size:XL

#7161 chore(datasets): simplify DatasetAnalytics component interaction and integrate local storage for chart metrics
  web/src/features/datasets/components/DatasetAnalytics.tsx
  web/src/features/scores/components/multi-select-key-values.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: size:L, auto-merge

#7178 chore: upgrade langchain
  packages/shared/package.json
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:S, auto-merge

#7209 chore: refactor chart display names into single util
  web/src/features/widgets/chart-library/utils.ts
  web/src/features/widgets/components/SelectWidgetDialog.tsx
  web/src/features/widgets/components/WidgetTable.tsx
Labels: size:M, auto-merge

#7163 fix(datasets): prevent delete modal from closing on mouse navigation event
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
Labels: bug, size:S

#7215 fix(graph-view): handle missing __start__ node for langgraph>=0.4
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
Labels: size:S

#7222 feat(models): add o3-pro for cost tracking
  worker/src/constants/default-model-prices.json
Labels: feat-playground, feat-cost-tracking, size:M, auto-merge

#7223 chore(models): adjust price of o3 to reflected updated openai pricing
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:S, auto-merge

#7227 fix(ui): enable clipboard copying for self-hosted instances
  web/src/components/publish-object-switch.tsx
  web/src/components/table/table-view-presets/hooks/useViewMutations.ts
  web/src/components/trace/CopyIdsPopover.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/components/ui/Codeblock.tsx
  web/src/components/ui/MarkdownViewer.tsx
  web/src/features/playground/page/components/GenerationOutput.tsx
  web/src/features/prompts/components/PromptSelectionDialog.tsx
  web/src/utils/clipboard.ts
Labels: size:M, auto-merge

#7229 feat(model-prices): add o1-pro
  worker/src/constants/default-model-prices.json
Labels: size:M, auto-merge

#7232 feat(MarkdownViewer): add URL sanitization using DOMPurify for safe link rendering
  web/src/components/ui/MarkdownViewer.tsx
Labels: size:M, auto-merge

#7248 fix(popover): update max-width calculation for popover component to use fit-content
  web/src/components/ui/popover.tsx
Labels: ui, size:XS, auto-merge

#7272 fix(trace-graph): validate node existence before selection and handle errors gracefully
  web/src/features/trace-graph-view/components/TraceGraphCanvas.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
Labels: bug, size:M, auto-merge

#7252 chore: allow trace deletions on entire history
  web/src/components/table/use-cases/traces.tsx
  worker/src/features/batchAction/handleBatchActionJob.ts
Labels: size:S, auto-merge

#7241 feat(otel-ingestion): handle long-running traces
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/OtelIngestionProcessor.ts
  web/src/features/otel/server/index.ts
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: size:XXL, auto-merge

#7274 fix: propagate searchQuery to deleteMany call
  packages/shared/src/features/batchAction/types.ts
  web/src/components/table/use-cases/traces.tsx
  worker/src/__tests__/batchAction.test.ts
  worker/src/features/batchAction/handleBatchActionJob.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
Labels: size:M, auto-merge

#7279 fix(trpcErrorToast): enhance error handling for 5xx server errors wit…
  web/src/utils/trpcErrorToast.tsx
Labels: size:XS, auto-merge

#7282 style(sessions): align header pills
  web/src/components/session/index.tsx
Labels: size:XS, auto-merge

#7290 fix(PopoverFilterBuilder): ensure filter buttons do not submit forms
  web/src/features/filters/components/filter-builder.tsx
Labels: size:XS, auto-merge

#7293 fix: keep zod/v3 schema for langchainjs interactions
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  web/src/features/evals/server/router.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/features/utilities.ts
Labels: size:M, auto-merge

#7294 chore(dialog): move close button to DialogHeader for improved accessibility
  web/src/components/deleteButton.tsx
  web/src/components/ui/dialog.tsx
Labels: ui, size:S, auto-merge

#7300 security: upgrade release-it
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#7305 chore: improve search tooltip
  web/src/components/table/data-table-toolbar.tsx
Labels: ui, size:M, auto-merge

#7306 chore: clean up scripts
  worker/package.json
  worker/src/scripts/refill-ingestion-events.ts
  worker/src/scripts/s3-ingestion-event-relpay.ts
Labels: size:XL, auto-merge

#7312 fix: fix select all UI bug
  web/src/components/table/use-cases/traces.tsx
Labels: bug, ui, size:XS, auto-merge

#6358 chore: upgrade react email
  packages/shared/package.json
  packages/shared/src/server/services/email/batchExportSuccess/sendBatchExportSuccessEmail.ts
  packages/shared/src/server/services/email/organizationInvitation/sendMembershipInvitationEmail.ts
  packages/shared/src/server/services/email/passwordReset/sendResetPasswordVerificationRequest.tsx
  pnpm-lock.yaml
Labels: dependencies, size:S, auto-merge

#7313 security: upgrade react-syntax-highlighter
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS, auto-merge

#7314 feat(otel): parse trace attributes from trace metadata
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: size:L, auto-merge

#7292 refactor(peek): remove urlPathname parameter from peek navigation and state hooks
  web/src/components/table/peek.tsx
  web/src/components/table/peek/hooks/useDatasetComparePeekNavigation.ts
  web/src/components/table/peek/hooks/useDatasetComparePeekState.ts
  web/src/components/table/peek/hooks/useEvalTemplatesPeekNavigation.ts
  web/src/components/table/peek/hooks/useObservationPeekNavigation.ts
  web/src/components/table/peek/hooks/useObservationPeekState.ts
  web/src/components/table/peek/hooks/usePeekState.ts
  web/src/components/table/peek/hooks/useRunningEvaluatorsPeekNavigation.ts
  web/src/components/table/peek/hooks/useTracePeekNavigation.ts
  web/src/components/table/peek/hooks/useTracePeekState.ts
  web/src/components/table/peek/peek-dataset-compare-detail.tsx
  web/src/components/table/peek/peek-evaluator-config-detail.tsx
  web/src/components/table/peek/peek-evaluator-template-detail.tsx
  web/src/components/table/peek/peek-observation-detail.tsx
  web/src/components/table/peek/peek-trace-detail.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/evals/components/eval-templates-table.tsx
  web/src/features/evals/components/evaluator-table.tsx
Labels: size:L, auto-merge

#7325 chore(otel): add metrics for shallow trace events and sdk batches
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: size:M, auto-merge

#7343 fix: gracefully fail exceeded context length for evals
  worker/src/queues/batchExportQueue.ts
  worker/src/queues/evalQueue.ts
Labels: size:XS, auto-merge

#7337 fix(otel): force modelparam values to be strings
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: bug, size:M, auto-merge

#7355 docs: Update network diagram
  CONTRIBUTING.md
Labels: size:M, auto-merge, codex

#7344 feat(playground): allow non-streaming responses
  web/src/env.mjs
  web/src/features/playground/page/components/Messages.tsx
  web/src/features/playground/page/context/index.tsx
  web/src/features/playground/server/chatCompletionHandler.ts
  web/src/features/playground/server/validateChatCompletionBody.ts
Labels: feat-playground, size:L

#7364 feat(dashboard): add csv download from ui and loading state
  web/src/features/widgets/chart-library/BigNumber.tsx
  web/src/features/widgets/chart-library/Chart.tsx
  web/src/features/widgets/chart-library/DownloadButton.tsx
  web/src/features/widgets/components/DashboardWidget.tsx
Labels: feat-dashboard, size:L, auto-merge, codex

#7357 chore(evals): re-introduce delay input field for evaluation timing
  web/src/features/evals/components/inner-evaluator-form.tsx
  web/src/features/evals/utils/evaluator-form-utils.ts
Labels: size:S, auto-merge

#6550 chore: add otel conventional attributes to clickhouse db spans
  packages/shared/src/server/repositories/clickhouse.ts
Labels: size:L, auto-merge

#7383 fix: center align dataset description vertically
  web/src/features/datasets/components/DatasetsTable.tsx
Labels: ui, size:XS, auto-merge

#7401 chore: upgrade prisma to 6.10.1
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS, auto-merge

#7402 chore: add devcontainer.json
  .devcontainer.json
  .gitignore
Labels: size:XS, auto-merge

#7389 chore(seeder): represent correct langfuse data model in seed data
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/package.json
  packages/shared/prisma/seed.ts
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/scripts/seeder/load-seed-clickhouse.ts
  packages/shared/scripts/seeder/prepare-clickhouse.ts
  packages/shared/scripts/seeder/seed-clickhouse.ts
  packages/shared/scripts/seeder/seed-postgres.ts
  packages/shared/scripts/seeder/utils/README.md
  packages/shared/scripts/seeder/utils/chat_ml_json.json
  packages/shared/scripts/seeder/utils/clickhouse-builder.ts
  packages/shared/scripts/seeder/utils/clickhouse-seed-constants.ts
  packages/shared/scripts/seeder/utils/data-generators.ts
  packages/shared/scripts/seeder/utils/markdown.txt
  packages/shared/scripts/seeder/utils/nested_json.json
  packages/shared/scripts/seeder/utils/postgres-seed-constants.ts
  packages/shared/scripts/seeder/utils/seed-helpers.ts
  packages/shared/scripts/seeder/utils/seeder-orchestrator.ts
  packages/shared/scripts/seeder/utils/types.ts
Labels: size:XXL, auto-merge

#7421 fix(prompts): bottom pagination buttons didn't respond
  web/src/features/prompts/components/prompts-table.tsx
Labels: size:XS, auto-merge

#7424 feat(sidebar): persist collapsed state
  web/src/components/nav/nav-main.tsx
  web/src/components/ui/hover-card.tsx
  web/src/components/ui/sidebar.tsx
Labels: ui, size:L, auto-merge

#7439 add claude.md file
  CLAUDE.md
Labels: size:L, auto-merge

#7447 fix(observation): filter out null values from model parameters in ObservationPreview
  web/src/components/trace/ObservationPreview.tsx
Labels: size:XS, auto-merge

#7448 fix(playground): do not report playground errors to sentry
  web/src/features/playground/page/context/index.tsx
Labels: feat-playground, size:XS, auto-merge

#7199 feat: add ability to export dataset items
  packages/shared/src/interfaces/tableNames.ts
  web/src/features/datasets/components/DatasetItemsTable.tsx
  worker/src/__tests__/batchExport.test.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
Labels: ui, feat-datasets, size:L, auto-merge

#7454 fix(trace-ui): remove unnecessary json key
  web/src/components/schemas/ChatMlSchema.ts
Labels: ui, size:XS, auto-merge

#7392 chore(cloud): apply pro rate limits to core plan (tmp)
  web/src/features/public-api/server/RateLimitService.ts
Labels: size:S, auto-merge

#7468 fix(llm-connection-vertex): use zodV3 for structured output calls
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  web/src/features/evals/server/router.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/features/utilities.ts
Labels: size:S, auto-merge

#7475 fix: handle dataset queries with cached traces in evals
  worker/src/__tests__/evalService.test.ts
  worker/src/features/evaluation/evalService.ts
Labels: feat-evals, size:M

#7486 feat: line breaks on evaluation run tooltip hints
  packages/shared/scripts/seeder/utils/data-generators.ts
  web/src/components/scores-table-cell.tsx
  web/src/features/scores/components/AnnotateDrawerContent.tsx
Labels: feat-scores, size:XS, auto-merge

#7487 chore: reduce number of listed S3 files in event processing
  packages/shared/src/env.ts
  packages/shared/src/server/services/StorageService.ts
Labels: size:XS, auto-merge

#7494 chore: improve support widget CTAs
  web/src/components/nav/support-menu-dropdown.tsx
  web/src/features/support-chat/PlainChat.tsx
Labels: ui, size:S, auto-merge

#7500 chore: gracefully handle failed evals
  worker/src/features/evaluation/evalService.ts
  worker/src/queues/evalQueue.ts
Labels: feat-evals, size:S, auto-merge

#7507 fix: show falsy values in IOTableCell unless null/undefined
  web/src/components/ui/CodeJsonViewer.tsx
Labels: ui, size:XS, auto-merge

#7510 chore: update contributing.md with recent state
  CONTRIBUTING.md
Labels: size:L, auto-merge

#7382 fix: long trace names shouldn't break at icons
  web/src/components/trace/ObservationTree.tsx
Labels: bug, size:S, auto-merge

#7538 perf: cache eval entities during variable extraction
  worker/src/features/evaluation/evalService.ts
Labels: feat-evals, size:M

#7542 chore: only consider getWaitingCount for queue length
  worker/src/queues/workerManager.ts
Labels: size:XS, auto-merge

#7541 chore: skip s3 LIST for projects configured in env
  packages/shared/src/env.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
Labels: lgtm, size:S, auto-merge

#7543 chore: add python sdk v3 notification
  web/src/components/nav/sidebar-notifications.tsx
Labels: size:XS, auto-merge

#7552 chore(cloud): remove posthog groups to reduce costs
  web/src/pages/_app.tsx
Labels: size:M, auto-merge

#7560 fix: warn if missing encryption_key when updating posthog integration
  web/src/features/posthog-integration/posthog-integration-router.ts
Labels: size:M, auto-merge

#7567 feat(dashboard): allow filtering by score value in custom dashboards
  web/src/features/query/dashboardUiTableToViewMapping.ts
  web/src/features/query/dataModel.ts
  web/src/features/widgets/components/WidgetForm.tsx
Labels: feat-dashboard, feat-scores, size:M, auto-merge

#7570 fix(evals): show loading state of detail buttons only if preview is enabled
  web/src/features/evals/components/inner-evaluator-form.tsx
Labels: size:S

#7574 exp: add aggregating merge trees experiment for traces tables
  packages/shared/src/server/repositories/definitions.ts
  worker/src/env.ts
  worker/src/services/ClickhouseWriter/index.ts
  worker/src/services/IngestionService/README.md
  worker/src/services/IngestionService/index.ts
Labels: size:L, auto-merge

#7388 feat(prompts): prompt chat message placeholders in backend and api
  CLAUDE.md
  fern/apis/server/definition/prompts.yml
  packages/shared/scripts/seeder/seed-postgres.ts
  packages/shared/scripts/seeder/utils/postgres-seed-constants.ts
  packages/shared/src/features/prompts/types.ts
  packages/shared/src/index.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/llm/compileChatMessages.ts
  packages/shared/src/server/llm/types.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/compileChatMessages.servertest.ts
  web/src/__tests__/prompts.v2.servertest.ts
  web/src/components/ChatMessages/ChatMessageComponent.tsx
  web/src/components/ChatMessages/index.tsx
  web/src/components/ChatMessages/types.ts
  web/src/components/ChatMessages/utils/createEmptyMessage.ts
  web/src/components/schemas/ChatMlSchema.ts
  web/src/components/trace/IOPreview.tsx
  web/src/features/experiments/server/router.ts
  web/src/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/playground/page/components/MessagePlaceholderComponent.tsx
  web/src/features/playground/page/components/MessagePlaceholders.tsx
  web/src/features/playground/page/context/index.tsx
  web/src/features/playground/page/playground.tsx
  web/src/features/playground/page/types.ts
  web/src/features/prompts/components/NewPromptForm/PromptChatMessages.tsx
  web/src/features/prompts/components/NewPromptForm/validation.ts
  worker/src/features/experiments/experimentService.ts
Labels: feat-prompt-management, size:XXL, auto-merge

#7581 feat(posthog-export): Add environment attribute to PostHog exports
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:S, auto-merge
