Repository langfuse/langfuse, pull requests merged in 2025-05, with the labels that each got.

#6664 chore: add eval execution metric
  worker/src/queues/evalQueue.ts
Labels: size:XS

#6665 chore: disable dlx retry for oss
  worker/src/env.ts
  worker/src/services/dlx/dlxRetryService.ts
Labels: size:XS

#6683 chore: improve front end performance
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/components/ui/MarkdownViewer.tsx
Labels: ui, size:S, auto-merge

#6691 fix: improve axis labeling in widgets
  packages/shared/scripts/prepareClickhouse.ts
  web/src/features/widgets/chart-library/HorizontalBarChart.tsx
  web/src/features/widgets/chart-library/utils.ts
  web/src/features/widgets/components/DashboardWidget.tsx
  web/src/features/widgets/components/WidgetForm.tsx
Labels: ui, size:S, auto-merge

#6694 fix(trace-ui): usage breakdown on hover
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/BreakdownToolTip.tsx
Labels: ui, size:S, auto-merge

#6690 chore(peek): memoize table body for enhanced front-end performance
  web/src/components/table/data-table.tsx
  web/src/components/table/peek/hooks/usePeekView.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/ui/sheet.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
Labels: ui, size:L, auto-merge

#6695 fix: navigation issue with organization/project members pages
  web/src/features/rbac/components/MembersTable.tsx
  web/src/features/rbac/components/MembershipInvitesPage.tsx
Labels: size:M, auto-merge

#6626 chore: remove non-production note on worker in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size:XS, auto-merge

#6701 fix: allow protected keys in metadata object
  packages/shared/scripts/prepareClickhouse.ts
  web/src/__tests__/async/traces-trpc.servertest.ts
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/traces.ts
Labels: lgtm, size:M, auto-merge

#6710 fix(score-analytics): css on categorical charts
  web/src/features/scores/components/ScoreChart.tsx
  web/src/features/scores/components/TimeseriesChart.tsx
Labels: feat-scores, size:XS, auto-merge

#6715 feat: add totalTokens and totalCost to dashboard builder
  web/src/features/query/dataModel.ts
Labels: feat-dashboard, size:S, auto-merge

#6714 fix: increase io limit
  packages/shared/src/env.ts
  web/src/__tests__/async/traces-api.servertest.ts
Labels: size:S, auto-merge

#6721 chore(ui): increase contrast ratio of annotation selection
  web/src/components/ui/toggle.tsx
  web/src/features/scores/components/AnnotateDrawerContent.tsx
Labels: ui, size:XS, auto-merge

#6722 chore: show full user email on hover
  web/src/components/nav/nav-user.tsx
Labels: ui, size:XS, auto-merge

#6723 chore(ui): add border to trace timeline bars to increase contrast
  web/src/components/trace/TraceTimelineView.tsx
Labels: ui, size:XS, auto-merge

#6716 fix: persist changes in evals template edit on tab change
  web/src/ee/features/evals/components/template-form.tsx
Labels: size:S, auto-merge

#6724 feat: allow metadata filtering in dashboard builder
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/__tests__/queryBuilderSQLI.servertest.ts
  web/src/features/query/dashboardUiTableToViewMapping.ts
  web/src/features/query/server/queryBuilder.ts
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
Labels: feat-dashboard, feat-metadata, size:L, auto-merge

#6725 style(observations): correctly display costs as sums
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/ObservationTree.tsx
Labels: size:S, auto-merge

#6595 feat(tables): support saving and sharing table views
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250517273700_add_table_view_presets.sql/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/domain/index.ts
  packages/shared/src/domain/table-view-presets.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/services/TableViewService/TableViewService.ts
  packages/shared/src/server/services/TableViewService/index.ts
  packages/shared/src/server/services/TableViewService/types.ts
  web/src/__tests__/table-view-presets.clienttest.ts
  web/src/components/deleteButton.tsx
  web/src/components/table/data-table-toolbar.tsx
  web/src/components/table/table-view-presets/README.md
  web/src/components/table/table-view-presets/components/data-table-view-presets-drawer.tsx
  web/src/components/table/table-view-presets/hooks/useTableViewManager.ts
  web/src/components/table/table-view-presets/hooks/useViewData.ts
  web/src/components/table/table-view-presets/hooks/useViewMutations.ts
  web/src/components/table/table-view-presets/validation.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/datasets/components/DatasetsTable.tsx
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/server/api/root.ts
  web/src/server/api/routers/tableViewPresets.ts
Labels: size:XXL, auto-merge

#6730 chore(table-views): handle nullish avatar
  packages/shared/src/server/services/TableViewService/types.ts
  web/src/components/table/table-view-presets/components/data-table-view-presets-drawer.tsx
Labels: size:S

#6676 feat(scores): support run level scores
  fern/apis/client/definition/score.yml
  fern/apis/server/definition/commons.yml
  fern/apis/server/definition/ingestion.yml
  fern/apis/server/definition/score.yml
  packages/shared/clickhouse/migrations/clustered/0017_add_run_id_column_scores.down.sql
  packages/shared/clickhouse/migrations/clustered/0017_add_run_id_column_scores.up.sql
  packages/shared/clickhouse/migrations/clustered/0018_add_scores_run_index.down.sql
  packages/shared/clickhouse/migrations/clustered/0018_add_scores_run_index.up.sql
  packages/shared/clickhouse/migrations/unclustered/0017_add_run_id_column_scores.down.sql
  packages/shared/clickhouse/migrations/unclustered/0017_add_run_id_column_scores.up.sql
  packages/shared/clickhouse/migrations/unclustered/0018_add_scores_run_index.down.sql
  packages/shared/clickhouse/migrations/unclustered/0018_add_scores_run_index.up.sql
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/domain/scores.ts
  packages/shared/src/features/scores/interfaces/README.md
  packages/shared/src/features/scores/interfaces/api/shared.ts
  packages/shared/src/features/scores/interfaces/api/v2/schemas.ts
  packages/shared/src/features/scores/interfaces/shared.ts
  packages/shared/src/server/ingestion/types.ts
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/scores-utils.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/scores_converters.ts
  packages/shared/src/server/test-utils/tracing-factory.ts
  packages/shared/src/utils/scores.ts
  web/public/generated/api-client/openapi.yml
  web/public/generated/api/openapi.yml
  web/src/__tests__/async/scores-api-v2.servertest.ts
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/service.ts
  web/src/features/public-api/server/scores.ts
  web/src/features/public-api/server/traces.ts
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/features/scores/components/ScoreDetailColumnHelpers.tsx
  web/src/features/scores/hooks/useIndividualScoreColumns.ts
  web/src/features/scores/lib/getDefaultScoreData.ts
  web/src/server/api/routers/scores.ts
  worker/src/features/database-read-stream/getDatabaseReadStream.ts
  worker/src/services/IngestionService/index.ts
Labels: feat-scores, lgtm, size:XL, auto-merge

#6734 chore(table-view-presets): conditionally apply generations filter; add avatar fallback; set beta badge
  packages/shared/src/server/services/TableViewService/TableViewService.ts
  packages/shared/src/server/services/TableViewService/types.ts
  web/src/components/table/table-view-presets/components/data-table-view-presets-drawer.tsx
  web/src/components/table/use-cases/observations.tsx
Labels: size:M, auto-merge

#6737 fix(otel): avoid logging model name as model param
  web/src/features/otel/server/index.ts
Labels: bug, lgtm, size:XS, auto-merge

#6736 feat: add otel attribute parsing for google adk
  web/src/features/otel/server/index.ts
Labels: lgtm, size:S, auto-merge

#6739 chore(run-scores): show only populated run-level scores
  packages/shared/src/server/repositories/scores.ts
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/scores/hooks/useIndividualScoreColumns.ts
Labels: feat-datasets, feat-scores, size:L, auto-merge

#6743 chore: add sentry release tag
  web/Dockerfile
  web/sentry.client.config.ts
Labels: size:XS

#6753 fix(ui) langgraph agent graph
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
Labels: bug, ui, size:S, auto-merge

#6759 fix: full text search
  web/src/components/table/data-table-toolbar.tsx
  web/src/components/table/use-cases/observations.tsx
Labels: size:XS

#6762 fix(ui-graph-view): fix metadata parsing in isLanggraphTrace
  web/src/features/trace-graph-view/utils/isLanggraphTrace.ts
Labels: ui, size:S, auto-merge

#6763 chore: do not fetch metadata for trace detail initial load
  packages/shared/src/server/repositories/observations.ts
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
  web/src/pages/api/public/traces/[traceId].ts
  web/src/server/api/routers/traces.ts
  worker/src/__tests__/traceDeletion.test.ts
Labels: size:M, auto-merge

#6768 refactor: refactor observations by id repo function
  packages/shared/src/server/repositories/observations.ts
  web/src/__e2e__/api.servertest.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
  web/src/__tests__/prompts.v1.servertest.ts
  web/src/__tests__/prompts.v2.servertest.ts
  web/src/ee/features/annotation-queues/server/annotationQueueItems.ts
  web/src/ee/features/annotation-queues/server/annotationQueues.ts
  web/src/features/comments/validateCommentReferenceObject.ts
  web/src/pages/api/public/dataset-run-items.ts
  web/src/pages/api/public/observations/[observationId].ts
  web/src/server/api/routers/observations.ts
  worker/src/__tests__/dataRetentionProcessing.test.ts
  worker/src/__tests__/projectDeletionProcessing.test.ts
Labels: size:L, auto-merge

#6764 fix: align signed download URL with hostname
  packages/shared/src/server/services/StorageService.ts
Labels: bug, size:M, auto-merge

#6773 chore: improve auth error message
  web/src/pages/auth/sign-in.tsx
  web/src/server/auth.ts
Labels: size:XS, auto-merge

#6729 feat: add org API keys to organization settings
  web/src/__tests__/async/organizations-api-key-trpc.servertest.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/public-api/components/ApiKeyList.tsx
  web/src/features/public-api/components/CreateApiKeyButton.tsx
  web/src/features/public-api/server/organizationApiKeyRouter.ts
  web/src/features/rbac/constants/organizationAccessRights.ts
  web/src/features/setup/components/SetupPage.tsx
  web/src/pages/organization/[organizationId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/server/api/root.ts
Labels: feat-api, size:XL, auto-merge

#6778 feat: add new metrics api endpoint
  fern/apis/server/definition/metrics.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/metrics-api.servertest.ts
  web/src/features/public-api/types/metrics.ts
  web/src/pages/api/public/metrics/index.ts
Labels: feat-api, size:XL, auto-merge

#6772 chore(ui): improve ux of full-text search input
  web/src/components/table/data-table-toolbar.tsx
Labels: ui, lgtm, size:L, auto-merge

#6781 fix(ui-graph-view): fetch graph data separately
  packages/shared/src/server/repositories/traces.ts
  web/src/components/trace/index.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
  web/src/features/trace-graph-view/types.ts
  web/src/features/trace-graph-view/utils/isLanggraphTrace.ts
  web/src/server/api/routers/traces.ts
Labels: ui, size:L, auto-merge

#6782 chore(ui-graph-view): allow graph view in impersonation mode
  web/src/components/trace/index.tsx
Labels: ui, size:XS, auto-merge

#6780 feat(datasets): support `GET` dataset-run-items
  fern/apis/server/definition/dataset-run-items.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/datasets-api.servertest.ts
  web/src/features/public-api/types/datasets.ts
  web/src/pages/api/public/dataset-run-items.ts
Labels: feat-datasets, size:L, auto-merge

#6784 fix: fix metadata json selector
  web/src/ee/features/evals/components/inner-evaluator-form.tsx
Labels: size:XS

#6789 chore: remove unused env variable
  .env.prod.example
  web/src/env.mjs
Labels: size:XS, auto-merge

#6792 fix(session-ui): handling mine type as enum string equivalent
  web/src/components/ui/LangfuseMediaView.tsx
Labels: ui, size:XS, auto-merge

#6793 fix: Increase memory usage for deploy
  .github/workflows/_deploy_ecs_service.yml
  web/Dockerfile
Labels: size:XS, auto-merge

#6794 fix(dashboard): warn on slow chart render and ask users to confirm
  web/src/features/widgets/chart-library/Chart.tsx
Labels: size:M, auto-merge

#6796 chore: remove queryPlayground page
  web/src/pages/project/[projectId]/queryPlayground.tsx
Labels: size:L, auto-merge

#6795 chore(dashboard): use more granular time buckets on home dashboard
  fern/apis/server/definition/metrics.yml
  packages/shared/src/server/repositories/dashboards.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/features/dashboard/components/ChartScores.tsx
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/components/score-analytics/CategoricalScoreChart.tsx
  web/src/features/dashboard/components/score-analytics/NumericScoreTimeSeriesChart.tsx
  web/src/server/api/services/sqlInterface.ts
  web/src/utils/date-range-utils.ts
Labels: size:M, auto-merge

#6797 fix(dashboard): increase precision of numbers on hover cards
  web/src/features/widgets/chart-library/HorizontalBarChart.tsx
  web/src/features/widgets/chart-library/LineChartTimeSeries.tsx
  web/src/features/widgets/chart-library/PieChart.tsx
  web/src/features/widgets/chart-library/VerticalBarChart.tsx
  web/src/features/widgets/chart-library/VerticalBarChartTimeSeries.tsx
Labels: size:M, auto-merge

#6798 chore: fix clickhouse timeout settings
  packages/shared/src/server/clickhouse/client.ts
Labels: size:S

#6799 fix(dashboard): render localized time strings for LineCharts
  web/src/features/widgets/chart-library/Chart.tsx
Labels: size:M, auto-merge

#6801 chore: parameterize clickhouse deletion timeouts
  packages/shared/src/env.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:S

#6817 fix(ui-tool-calls): handle parsing errors gracefully
  packages/shared/src/server/llm/types.ts
Labels: size:XS, auto-merge

#6822 perf: also add trace_id to observations search
  packages/shared/src/server/repositories/observations.ts
  web/src/server/api/routers/observations.ts
Labels: size:XS, auto-merge

#6819 feat(dashboard): add newly created widget to dashboard on save
  web/src/features/widgets/components/SelectWidgetDialog.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
  web/src/pages/project/[projectId]/widgets/new.tsx
Labels: feat-dashboard, size:L, auto-merge

#6824 feat(dashboards): add support for cloning existing dashboards
  packages/shared/src/server/services/DashboardService/DashboardService.ts
  web/src/components/deleteButton.tsx
  web/src/features/dashboard/components/DashboardTable.tsx
  web/src/features/dashboard/components/EditDashboardDialog.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
Labels: feat-dashboard, size:L, auto-merge

#6828 fix: fix traceid filter for observations by id clickhouse query
  packages/shared/src/server/repositories/observations.ts
  web/src/__tests__/async/repositories/observation-repository.servertest.ts
Labels: bug, size:M

#6783 chore(cloud): increases api rate limits
  packages/shared/src/interfaces/rate-limits.ts
  web/src/__tests__/rate-limit.servertest.ts
  web/src/features/public-api/server/RateLimitService.ts
  web/src/pages/api/public/dataset-items/[datasetItemId].ts
  web/src/pages/api/public/dataset-items/index.ts
  web/src/pages/api/public/dataset-run-items.ts
  web/src/pages/api/public/datasets.ts
  web/src/pages/api/public/datasets/[name]/index.ts
  web/src/pages/api/public/datasets/[name]/runs/[runName].ts
  web/src/pages/api/public/datasets/[name]/runs/index.ts
  web/src/pages/api/public/v2/datasets/[datasetName]/index.ts
  web/src/pages/api/public/v2/datasets/index.ts
Labels: feat-api, size:M

#6835 chore: reduce log level for prompt service
  packages/shared/src/server/services/PromptService/index.ts
Labels: feat-prompt-management, feat-log-levels, size:XS, auto-merge

#6836 chore: reduce error logs for llm 429 errors
  worker/src/features/utilities.ts
Labels: size:XS

#6829 fix(dashboard): avoid invalid filter name on view switches
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/query/server/queryBuilder.ts
Labels: bug, size:M, auto-merge

#6843 chore: change logging pattern around redis retries
  packages/shared/src/server/redis/redis.ts
Labels: size:S, auto-merge

#6851 chore: reduce worker logs
  worker/src/queues/ingestionQueue.ts
Labels: size:XS

#6820 chore(dashboard): auto-save dashboard on any changes
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
Labels: size:M, auto-merge

#6853 fix(dashboard): map traceRelease and traceVersion correctly on breakdown
  web/src/features/query/dataModel.ts
Labels: size:XS, auto-merge

#6854 feat(dashboard): add new widget to dashboard on save
  web/src/features/dashboard/components/SelectDashboardDialog.tsx
  web/src/pages/project/[projectId]/widgets/new.tsx
Labels: feat-dashboard, size:L, auto-merge

#6858 chore(dashboard): make hovers in dark mode more readable
  web/src/features/widgets/chart-library/HorizontalBarChart.tsx
  web/src/features/widgets/chart-library/LineChartTimeSeries.tsx
  web/src/features/widgets/chart-library/PieChart.tsx
  web/src/features/widgets/chart-library/VerticalBarChart.tsx
  web/src/features/widgets/chart-library/VerticalBarChartTimeSeries.tsx
Labels: feat-dashboard, size:S

#6856 feat(dashboard): add documentation hovers onto widget properties
  web/src/features/query/dataModel.ts
  web/src/features/query/server/queryBuilder.ts
  web/src/features/query/types.ts
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/features/widgets/components/WidgetPropertySelectItem.tsx
Labels: feat-dashboard, size:L

#6861 perf: skip zod validation for otel event batches
  packages/shared/src/server/ingestion/processEventBatch.ts
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: size:M, auto-merge

#6841 feat(ui-ee): show/hide product modules in main menu via LANGFUSE_UI_VISIBLE/HIDDEN_PRODUCT_MODULES
  .env.prod.example
  web/src/components/layouts/layout.tsx
  web/src/components/layouts/routes.tsx
  web/src/components/nav/support-menu-dropdown.tsx
  web/src/ee/features/ui-customization/productModuleSchema.ts
  web/src/ee/features/ui-customization/uiCustomizationRouter.ts
  web/src/env.mjs
Labels: ui, size:L, auto-merge

#6869 chore: reduce title size in widget item doc hover
  web/src/features/widgets/components/WidgetPropertySelectItem.tsx
Labels: ui, size:XS, auto-merge

#6871 chore: increase default timeframe in custom dashboards to 7d
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/hooks/useDashboardDateRange.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
Labels: size:S, auto-merge

#6870 perf: increase socket lifetime and connections for clickhouse client
  packages/shared/src/env.ts
  packages/shared/src/server/clickhouse/client.ts
Labels: size:XS, auto-merge

#6692 feat(otel): add Langfuse attribute parsing
  packages/shared/src/server/auth/types.ts
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/attributes.ts
  web/src/features/otel/server/index.ts
  web/src/features/public-api/server/apiAuth.ts
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: lgtm, size:XL, auto-merge

#6878 perf(otel): do not pass deep parsed metadata
  packages/shared/src/server/ingestion/processEventBatch.ts
  web/src/features/otel/server/index.ts
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: lgtm, size:M, auto-merge

#6849 chore: remove clickhouse session id
  web/src/features/datasets/server/service.ts
Labels: size:M, auto-merge

#6873 feat(dashboards): add langfuse managed read-only dashboard support
  packages/shared/src/server/services/DashboardService/DashboardService.ts
  packages/shared/src/server/services/DashboardService/types.ts
  web/src/features/dashboard/components/DashboardTable.tsx
  web/src/features/dashboard/components/SelectDashboardDialog.tsx
  web/src/features/widgets/components/DashboardWidget.tsx
  web/src/features/widgets/components/WidgetTable.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
  web/src/pages/project/[projectId]/widgets/[widgetId]/index.tsx
  web/src/server/api/routers/dashboardWidgets.ts
Labels: feat-dashboard, size:XL, auto-merge

#6888 chore(dashboard): show description on hover in selection tables
  web/src/features/dashboard/components/SelectDashboardDialog.tsx
  web/src/features/widgets/components/SelectWidgetDialog.tsx
Labels: size:XS, auto-merge

#6889 feat(dashboard): include dashboards in cmdk menu
  web/src/features/command-k-menu/CommandMenu.tsx
Labels: feat-dashboard, size:M, auto-merge

#6890 chore(dashboard): auto-generate widget name from selected props
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/features/widgets/utils.ts
  web/src/pages/project/[projectId]/widgets/[widgetId]/index.tsx
  web/src/pages/project/[projectId]/widgets/new.tsx
Labels: feat-dashboard, size:L, auto-merge

#6895 fix(ui): hover state color of chat message types
  web/src/components/ChatMessages/ChatMessageComponent.tsx
Labels: ui, size:XS, auto-merge

#6897 chore: Update AGENTS guide
  AGENTS.md
Labels: size:S, codex

#6899 chore: ignore HEAD request for auth api endpoints
  web/src/pages/api/auth/[...nextauth].ts
Labels: size:XS, auto-merge

#6898 feat(auth): switch to OTP based password reset instead of magic link
  packages/shared/src/server/services/email/passwordReset/sendResetPasswordVerificationRequest.tsx
  web/src/features/auth-credentials/components/ResetPasswordButton.tsx
  web/src/server/auth.ts
Labels: feat-auth, size:L, auto-merge, codex

#6901 chore(ui): hide thread refs in support chat
  web/src/features/support-chat/PlainChat.tsx
Labels: size:XS, auto-merge, codex

#6902 fix(ui): peek view header should stay single line on mobile screens
  web/src/components/table/peek.tsx
Labels: ui, size:XS, auto-merge

#6903 feat: otel span mapping for pipecat traces
  web/src/features/otel/server/index.ts
Labels: size:S, auto-merge

#6904 fix(auth): add domain check for multi-tenant sso providers
  web/src/ee/features/multi-tenant-sso/utils.ts
  web/src/server/auth.ts
Labels: size:M, auto-merge

#6905 chore(ui): trim password reset otp
  web/src/features/auth-credentials/components/ResetPasswordButton.tsx
Labels: size:XS, auto-merge

#6908 chore(experiments): improve delete experiment confirm message
  web/src/features/datasets/components/DeleteDatasetRunButton.tsx
Labels: size:XS, auto-merge

#6909 perf: add mediaId index to efficiently delete media items
  packages/shared/prisma/migrations/20250519073249_add_trace_media_media_id_index/migration.sql
  packages/shared/prisma/migrations/20250519073327_add_observation_media_media_id_index/migration.sql
  packages/shared/prisma/schema.prisma
Labels: size:XS, auto-merge

#6900 chore(media): make ID generation fully deterministic based on hash
  packages/shared/prisma/migrations/20250519093327_media_add_index_project_id_id/migration.sql
  packages/shared/prisma/migrations/20250519093328_media_relax_id_uniqueness_to_project_only/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/__tests__/media.servertest.ts
  web/src/pages/api/public/media/[mediaId].ts
  web/src/pages/api/public/media/index.ts
  web/src/server/api/routers/media.ts
  worker/src/__tests__/dataRetentionProcessing.test.ts
  worker/src/__tests__/projectDeletionProcessing.test.ts
Labels: size:M

#6912 chore: add lw3-1 notification
  web/src/components/nav/sidebar-notifications.tsx
Labels: size:XS, auto-merge

#6916 feat(ui): implement optional sidebar notification expiry
  web/src/components/nav/sidebar-notifications.tsx
Labels: feat-metadata, size:S, auto-merge, codex

#6917 chore(dashboards): order metrics and dimensions in widgetform
  web/src/features/widgets/components/WidgetForm.tsx
Labels: feat-dashboard, size:S, auto-merge

#6891 feat(dashboard): make dashboard widgets draggable
  packages/shared/prisma/migrations/20250519145128_resize_dashboard_y_axis_components/migration.sql
  packages/shared/prisma/seed.ts
  pnpm-lock.yaml
  web/package.json
  web/src/components/ui/chart.tsx
  web/src/features/widgets/chart-library/Chart.tsx
  web/src/features/widgets/components/DashboardGrid.tsx
  web/src/features/widgets/components/DashboardWidget.tsx
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
  web/src/styles/globals.css
Labels: dependencies, feat-dashboard, size:L, auto-merge

#6921 chore: upgrade zod
  ee/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
Labels: dependencies, size:XS, auto-merge

#6925 fix(tables-ui): truncate name columns in traces and observations table
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/traces.tsx
Labels: ui, size:S, auto-merge

#6928 fix(auth): only apply login domain enforcement to multi-tenant sso
  web/src/ee/features/multi-tenant-sso/utils.ts
Labels: size:XS

#6930 chore: add metrics to measure by-id recency
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  web/src/server/api/routers/traces.ts
Labels: size:M

#6932 chore(dashboards): expand measures for dashboards
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/query/dataModel.ts
  web/src/features/widgets/components/DashboardWidget.tsx
  web/src/features/widgets/components/WidgetForm.tsx
Labels: feat-dashboard, size:L, auto-merge

#6933 feat(dashboards): add big number chart type
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250520123737_add_single_aggregate_chart_type/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/server/services/DashboardService/types.ts
  web/src/features/widgets/chart-library/BigNumber.tsx
  web/src/features/widgets/chart-library/Chart.tsx
  web/src/features/widgets/components/WidgetForm.tsx
Labels: feat-dashboard, lgtm, size:L

#6877 feat(dashboards): add langfuse managed dashboards
  worker/src/constants/langfuse-dashboards.json
  worker/src/initialize.ts
  worker/src/scripts/upsertLangfuseDashboards.ts
Labels: feat-dashboard, size:L, auto-merge

#6929 chore: update product notification - lw3-2
  web/src/components/nav/sidebar-notifications.tsx
Labels: lgtm, size:S, auto-merge

#6939 chore(dashboards): add more langfuse managed templates
  web/src/components/layouts/routes.tsx
  web/src/features/widgets/components/SelectWidgetDialog.tsx
  web/src/features/widgets/components/WidgetTable.tsx
  worker/src/constants/langfuse-dashboards.json
Labels: feat-dashboard, size:L, auto-merge

#6941 docs: add note that docker ENTRYPOINT is covered by semver
  web/Dockerfile
  worker/Dockerfile
Labels: lgtm, size:XS, auto-merge

#6944 chore: update pipcat otel attribute mapping
  web/src/features/otel/server/index.ts
Labels: size:S, auto-merge

#6942 chore: lw3-3 product hunt notification
  web/src/components/nav/sidebar-notifications.tsx
Labels: ui, size:M

#6955 fix(ui-jump-to-playground): allow response format in modelParams
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: ui, feat-playground, size:S

#6957 fix(ui-jump-to-playground): look up llm api keys when model parsing
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: ui, feat-playground, size:M, auto-merge

#6966 fix: dynamically calc max value for home line charts
  web/src/features/dashboard/components/BaseTimeSeriesChart.tsx
Labels: size:S, auto-merge

#6972 feat(otel): add support for observations of type 'event'
  web/src/features/otel/server/index.ts
Labels: size:XS, auto-merge

#6978 perf: drop unused observation_media index
  packages/shared/prisma/migrations/20250522140357_remove_obsolete_observation_media_index/migration.sql
  packages/shared/prisma/schema.prisma
Labels: size:XS, auto-merge

#6977 chore: lw3-4 notification
  web/src/components/nav/sidebar-notifications.tsx
Labels: size:XS, auto-merge

#6982 feat(cost-tracking+llm-keys): add claude 4 sonnet and opus
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:M, auto-merge

#6866 fix(cloud): plain.com initialization issues via update queue
  web/src/features/support-chat/PlainChat.tsx
Labels: bug, size:M, auto-merge

#6992 chore: lw3-5 notification
  web/src/components/nav/sidebar-notifications.tsx
Labels: size:XS, auto-merge

#6997 feat: add new /api/public/organizations/projects route to list projects
  fern/apis/server/definition/observations.yml
  fern/apis/server/definition/organizations.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/organizations-api.servertest.ts
  web/src/ee/features/admin-api/public/organizations/projects.ts
  web/src/pages/api/public/organizations/projects/index.ts
Labels: feat-api, size:XXL, auto-merge

#6995 perf: skip S3 list calls for OTEL observations
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/queues.ts
  web/src/pages/api/public/otel/v1/traces/index.ts
  worker/src/queues/ingestionQueue.ts
Labels: size:M, auto-merge

#7007 chore: do not alert on missing API keys or model
  packages/shared/src/server/services/DefaultEvaluationModelService/DefaultEvalModelService.ts
  worker/src/__tests__/evalService.test.ts
  worker/src/queues/evalQueue.ts
Labels: size:S, auto-merge

#7017 fix(otel): set trace name only if root span or attr provided
  web/src/features/otel/server/index.ts
Labels: size:XS, auto-merge

#7019 fix: do not wrap traces toolbar
  web/src/components/table/data-table-toolbar.tsx
Labels: bug, size:XS, auto-merge

#7015 chore: ensure eval config modal closes after successful delete
  web/src/components/deleteButton.tsx
  web/src/ee/features/evals/components/evaluator-table.tsx
Labels: size:S, auto-merge

#7020 fix(scores): conditionally render metadata in score badges
  web/src/components/grouped-score-badge.tsx
Labels: size:S, auto-merge

#7023 fix(llm-tool-dialog): do not propagate textarea keystrokes up
  web/src/ee/features/playground/page/components/CreateOrEditLLMSchemaDialog.tsx
  web/src/ee/features/playground/page/components/CreateOrEditLLMToolDialog.tsx
Labels: bug, size:XS, auto-merge

#7018 feat(evaluation): allow filtering by log status
  packages/shared/src/tableDefinitions/types.ts
  packages/shared/src/types.ts
  web/src/ee/features/evals/components/eval-log.tsx
  web/src/ee/features/evals/server/router.ts
  web/src/features/filters/hooks/useFilterState.ts
  web/src/server/api/definitions/evalExecutionsTable.ts
Labels: feat-evals, size:L, auto-merge

#7029 fix: prompt variables of SQL Semantic Equivalence evaluator
  worker/src/constants/managed-evaluators.json
Labels: bug, size:XS, auto-merge

#7035 feat(model): add regex for `claude-sonnet-4@20250514`
  worker/src/constants/default-model-prices.json
Labels: size:XS, auto-merge

#7039 fix(playground): update tools and schemas if name already exists
  web/src/ee/features/playground/page/components/CreateOrEditLLMSchemaDialog.tsx
  web/src/ee/features/playground/page/components/CreateOrEditLLMToolDialog.tsx
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/ee/features/playground/page/components/PlaygroundTools/index.tsx
  web/src/ee/features/playground/page/components/StructuredOutputSchemaSection.tsx
Labels: feat-playground, size:M

#7041 fix(playground): resolve prompts when jumping to playground
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/prompts/components/prompt-detail.tsx
Labels: size:S, auto-merge

#7062 chore: add logging to retry queue
  worker/src/services/dlq/dlqRetryService.ts
Labels: size:S

#7077 perf: add exact timestamp match for eval batch actions
  packages/shared/src/server/queues.ts
  packages/shared/src/server/repositories/traces.ts
  worker/src/ee/evaluation/evalService.ts
  worker/src/features/batchAction/handleBatchActionJob.ts
Labels: feat-evals, size:S, auto-merge

#7082 feat(ui): misc improvements to dashboards including mobile view, big number chart, truncate title/description, enforce min height/width of widgets
  web/src/features/widgets/chart-library/BigNumber.tsx
  web/src/features/widgets/chart-library/Chart.tsx
  web/src/features/widgets/components/DashboardGrid.tsx
  web/src/features/widgets/components/DashboardWidget.tsx
  web/src/features/widgets/components/WidgetForm.tsx
Labels: feat-dashboard, size:L, auto-merge

#7072 feat: allow host credentials for blob storage S3 integration
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250529071241_make_blobstorage_integration_credentials_optional/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/features/blobstorage-integration/blobstorage-integration-router.ts
  web/src/features/blobstorage-integration/types.ts
  web/src/pages/project/[projectId]/settings/integrations/blobstorage.tsx
  worker/src/ee/integrations/blobstorage/handleBlobStorageIntegrationProjectJob.ts
Labels: size:L, auto-merge

#7098 chore: remove popup from count for historic eval elements
  web/src/ee/features/evals/components/execution-count-tooltip.tsx
Labels: size:M, auto-merge
