Repository langfuse/langfuse, pull requests merged in 2025-09, with the labels that each got.

#8824 Fix/keyboard shortcuts modifier handling
  web/src/features/navigate-detail-pages/DetailPageNav.tsx
Labels: bug, lgtm, size:XS, auto-merge

#8835 chore(dataset-remote-run): validate remote run URL
  web/src/features/datasets/server/dataset-router.ts
Labels: size:S, auto-merge

#8795 chore: upgrade to nextjs v15
  .github/workflows/pipeline.yml
  .npmrc
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/Dockerfile
  web/next.config.mjs
  web/package.json
  web/src/components/NoDataOrLoading.tsx
  web/src/components/editor/CodeMirrorEditor.tsx
  web/src/components/table/ValueCell.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/hooks/usePanelState.ts
  web/src/components/ui/MarkdownViewer.tsx
  web/src/components/ui/calendar.tsx
  web/src/components/ui/timeline.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/features/dashboard/components/TotalMetric.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/filters/components/filter-builder.tsx
  web/src/features/notifications/Notification.tsx
  web/src/features/table/types.ts
  web/src/features/theming/ThemeProvider.tsx
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/hooks/use-element-visibility.tsx
  web/src/pages/api/public/otel/otlp-proto/generated/root.ts
  web/src/pages/api/public/scim/Users/[id].ts
  web/src/pages/api/trpc/[trpc].ts
Labels: dependencies, size:XL, auto-merge

#8853 Revert "chore: upgrade to nextjs v15"
  .github/workflows/pipeline.yml
  .npmrc
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/Dockerfile
  web/next.config.mjs
  web/package.json
  web/src/components/NoDataOrLoading.tsx
  web/src/components/editor/CodeMirrorEditor.tsx
  web/src/components/table/ValueCell.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/hooks/usePanelState.ts
  web/src/components/ui/MarkdownViewer.tsx
  web/src/components/ui/calendar.tsx
  web/src/components/ui/timeline.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/features/dashboard/components/TotalMetric.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/filters/components/filter-builder.tsx
  web/src/features/notifications/Notification.tsx
  web/src/features/table/types.ts
  web/src/features/theming/ThemeProvider.tsx
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/hooks/use-element-visibility.tsx
  web/src/pages/api/public/otel/otlp-proto/generated/root.ts
  web/src/pages/api/public/scim/Users/[id].ts
  web/src/pages/api/trpc/[trpc].ts
Labels: size:XL, auto-merge

#8813 Map gen_ai.input/output.messages to input/output
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: feat-api, lgtm, size:M, auto-merge

#8714 chore: move obsevation type setting override to mapper
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/ObservationTypeMapper.ts
  web/src/features/otel/server/OtelIngestionProcessor.ts
Labels: size:L, auto-merge

#8870 chore: patch flaky trace repository test
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
Labels: size:S, auto-merge

#8882 chore: bump dd-trace to 5.65.0
  packages/shared/package.json
  pnpm-lock.yaml
  web/Dockerfile
  web/package.json
  worker/package.json
Labels: dependencies, size:XS, auto-merge

#8883 fix(trace-single-ui): fix unavailable ref
  web/src/components/trace/index.tsx
  web/src/features/trace-graph-view/buildStepData.ts
  web/src/features/trace-graph-view/components/TraceGraphCanvas.tsx
  web/src/features/trace-graph-view/components/TraceGraphView.tsx
Labels: bug, size:M

#8888 chore: add env note to review.md
  REVIEW.md
Labels: size:XS

#8865 feat(table-ui): filter score columns to show score only if has value for given table
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/tableMappings/mapScoresColumnsTable.ts
  web/src/__tests__/async/repositories/score-repository.servertest.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/annotation-queues/components/AnnotationQueuesTable.tsx
  web/src/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/features/annotation-queues/pages/AnnotationQueueItems.tsx
  web/src/features/dashboard/components/ChartScores.tsx
  web/src/features/dashboard/components/ScoresTable.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/features/scores/components/ScoreDetailColumnHelpers.tsx
  web/src/features/scores/hooks/useIndividualScoreColumns.ts
  web/src/features/scores/hooks/useScoreColumns.ts
  web/src/features/scores/lib/scoreColumns.ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/prompts/metrics.tsx
  web/src/server/api/routers/scores.ts
Labels: feat-scores, size:XXL, auto-merge

#8892 fix(ci): attempt fix title checker prevented push to docker
  .github/workflows/pipeline.yml
  .github/workflows/validate-pr-title.yml
Labels: size:M

#8861 chore: upgrade to nextjs 15 & react 19
  .github/workflows/pipeline.yml
  .npmrc
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/Dockerfile
  web/next.config.mjs
  web/package.json
  web/src/components/NoDataOrLoading.tsx
  web/src/components/editor/CodeMirrorEditor.tsx
  web/src/components/table/ValueCell.tsx
  web/src/components/table/data-table-column-visibility-filter.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/hooks/usePanelState.ts
  web/src/components/ui/MarkdownViewer.tsx
  web/src/components/ui/calendar.tsx
  web/src/components/ui/timeline.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/features/dashboard/components/TotalMetric.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/filters/components/filter-builder.tsx
  web/src/features/notifications/Notification.tsx
  web/src/features/table/types.ts
  web/src/features/theming/ThemeProvider.tsx
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/hooks/use-element-visibility.tsx
  web/src/pages/api/public/otel/otlp-proto/generated/root.ts
  web/src/pages/api/public/scim/Users/[id].ts
  web/src/pages/api/trpc/[trpc].ts
Labels: dependencies, size:XL

#8634 build: add caches to CI pipeline
  .github/workflows/pipeline.yml
  turbo.json
Labels: lgtm, size:M, auto-merge

#8915 fix: make redis recently-processed cache cluster-safe
  worker/src/queues/ingestionQueue.ts
Labels: bug, size:S, auto-merge

#8922 fix(trace): jumptoplayground can cause infinite loop
  web/src/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: bug, size:S, auto-merge

#8927 fix(dataset-run-items): pagination for single dataset run detail view
  packages/shared/src/server/repositories/dataset-run-items.ts
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/features/datasets/server/dataset-router.ts
Labels: bug, size:M, auto-merge

#8921 chore: improve billing portal navigation, 2 buttons to make it more obvious
  web/src/ee/features/billing/components/BillingSettings.tsx
Labels: ui, size:S, auto-merge

#8947 perf(dataset-runs-metrics): utilise trace_id bloom filter in filtered observations
  packages/shared/src/server/repositories/dataset-run-items.ts
Labels: feat-datasets, size:S, auto-merge

#8954 fix(tracing): spacings on single user page
  web/src/pages/project/[projectId]/users/[userId].tsx
Labels: ui, size:S, auto-merge

#8961 fix(home): dashboard dark mode score analysis graph
  web/src/features/dashboard/components/score-analytics/NumericScoreHistogram.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/scores/components/ScoreChart.tsx
Labels: size:S

#8965 fix(trace-detail): nested observations not expanded in timeline
  web/src/components/trace/index.tsx
Labels: bug, size:XS, auto-merge

#8966 fix(support): improve context in initial support email
  web/src/features/support-chat/plain/plainClient.ts
  web/src/features/support-chat/trpc/plainRouter.ts
Labels: bug, size:L, auto-merge

#8967 feat(dataset-runs-ui): fix select and name columns on y-/x-scroll
  web/src/components/table/data-table.tsx
  web/src/components/table/types.ts
  web/src/features/datasets/components/DatasetRunsTable.tsx
Labels: feat-datasets, size:M, auto-merge

#8878 chore: decouple upload file from url signing in storage service
  packages/shared/src/server/services/StorageService.ts
  web/src/features/blobstorage-integration/blobstorage-integration-router.ts
  worker/src/__tests__/dataRetentionProcessing.test.ts
  worker/src/__tests__/projectDeletionProcessing.test.ts
  worker/src/__tests__/scoreDeletion.test.ts
  worker/src/__tests__/storageservice.test.ts
  worker/src/__tests__/traceDeletion.test.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
  worker/src/features/blobstorage/handleBlobStorageIntegrationProjectJob.ts
  worker/src/queues/coreDataS3ExportQueue.ts
Labels: lgtm, size:L, auto-merge

#8981 feat(table-ui): pin all select columns for y-/x-overflow
  web/src/components/table/data-table.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/table/components/TableSelectionManager.tsx
Labels: ui, size:S, auto-merge

#8970 feat(dataset-run-metrics): add total cost column to dataset runs table
  packages/shared/src/server/repositories/dataset-run-items-converters.ts
  packages/shared/src/server/repositories/dataset-run-items.ts
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:M, auto-merge

#8995 feat: allow custom select filters in dashboard widget flow
  web/src/features/widgets/components/WidgetForm.tsx
Labels: feat-dashboard, size:XS, auto-merge

#8997 fix(dataset-router): correct datasetItemIds value assignment in dataset filtering logic
  web/src/features/datasets/server/dataset-router.ts
Labels: size:XS, auto-merge

#9006 chore: add email to auth span
  web/src/server/auth.ts
Labels: size:XS

#9012 fix(otel): handle event observation type
  packages/shared/src/server/otel/ObservationTypeMapper.ts
Labels: bug, size:XS, auto-merge

#8885 chore(peek): remove polling logic and dependency on table state from peek implementation
  web/src/components/table/data-table.tsx
  web/src/components/table/peek.tsx
  web/src/components/table/peek/hooks/useDatasetComparePeekNavigation.ts
  web/src/components/table/peek/hooks/useDatasetComparePeekState.ts
  web/src/components/table/peek/hooks/useEvalTemplatesPeekNavigation.ts
  web/src/components/table/peek/hooks/useObservationPeekNavigation.ts
  web/src/components/table/peek/hooks/useObservationPeekState.ts
  web/src/components/table/peek/hooks/usePeekCompareDetail.ts
  web/src/components/table/peek/hooks/usePeekNavigation.ts
  web/src/components/table/peek/hooks/usePeekRunsCompareData.ts
  web/src/components/table/peek/hooks/usePeekState.ts
  web/src/components/table/peek/hooks/usePeekView.ts
  web/src/components/table/peek/hooks/useRunningEvaluatorsPeekNavigation.ts
  web/src/components/table/peek/hooks/useTracePeekNavigation.ts
  web/src/components/table/peek/hooks/useTracePeekState.ts
  web/src/components/table/peek/peek-dataset-compare-detail.tsx
  web/src/components/table/peek/peek-evaluator-config-detail.tsx
  web/src/components/table/peek/peek-evaluator-template-detail.tsx
  web/src/components/table/peek/peek-observation-detail.tsx
  web/src/components/table/peek/peek-trace-detail.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/evals/components/eval-templates-table.tsx
  web/src/features/evals/components/evaluator-table.tsx
  web/src/utils/navigation.ts
Labels: size:XXL, auto-merge

#9021 feat(tables-ui): pin columns in annotation and prompt metrics tables
  web/src/features/annotation-queues/components/AnnotationQueueItemsTable.tsx
  web/src/features/annotation-queues/components/AnnotationQueuesTable.tsx
  web/src/pages/project/[projectId]/prompts/metrics.tsx
Labels: ui, size:XS, auto-merge

#9027 chore: disallow background migrations on langfuse cloud
  web/src/features/background-migrations/server/background-migrations-router.ts
Labels: size:S, auto-merge

#9035 style: increase tooltip and sidebar toggle z-index
  web/src/components/ui/sidebar.tsx
  web/src/components/ui/tooltip.tsx
Labels: ui, size:XS, auto-merge

#8977 chore: ip allowlist for webhooks
  packages/shared/src/env.ts
  packages/shared/src/server/webhooks/ipBlocking.ts
  packages/shared/src/server/webhooks/validation.ts
  worker/src/__tests__/ip-blocking.test.ts
Labels: bug, size:L, auto-merge

#9028 fix: require admin api key for background migration retries in OSS
  web/src/ee/features/admin-api/server/adminApiAuth.ts
  web/src/features/background-migrations/components/background-migrations.tsx
  web/src/features/background-migrations/components/retry-background-migration.tsx
  web/src/features/background-migrations/server/background-migrations-router.ts
  web/src/server/api/trpc.ts
Labels: feat-api-auth, size:L, auto-merge

#9040 feat(dataset-run-items): pin dataset item id column in ui table
  web/src/features/datasets/components/DatasetRunItemsByRunTable.tsx
Labels: feat-datasets, size:XS, auto-merge

#9042 feat(sessions): add trace detail peek view and clean up layout
  packages/shared/scripts/seeder/seed-postgres.ts
  packages/shared/scripts/seeder/utils/data-generators.ts
  packages/shared/scripts/seeder/utils/seeder-orchestrator.ts
  web/src/components/session/index.tsx
  web/src/components/trace/IOPreview.tsx
  web/src/features/datasets/components/NewDatasetItemFromExistingObject.tsx
  web/src/hooks/usePreserveRelativeScroll.ts
Labels: feat-sessions, size:XL, auto-merge

#9050 chore(stripe): bump stripe from 17.4.0 to 18.5.0.basil
  pnpm-lock.yaml
  web/package.json
  web/src/ee/features/billing/components/BillingActionButtons.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
  web/src/ee/features/billing/server/stripeWebhookApiHandler.ts
Labels: dependencies, size:L

#9054 fix(otel): add root span metadata to trace
  packages/shared/src/server/otel/OtelIngestionProcessor.ts
Labels: bug, size:XS, auto-merge

#9022 feat(ui): add notification card for JS SDK v4 GA
  web/src/components/nav/sidebar-notifications.tsx
Labels: ui, size:XS, auto-merge

#9064 fix(ui): update JS/TS SDK v4 notification
  web/src/components/nav/sidebar-notifications.tsx
Labels: ui, size:XS, auto-merge

#9117 perf: drop final on check trace exists
  .env.dev-redis-cluster.example
  packages/shared/src/env.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/repositories/definitions.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/test-utils/clickhouse-helpers.ts
  worker/src/env.ts
  worker/src/features/evaluation/evalService.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/services/IngestionService/index.ts
Labels: size:L, auto-merge

#9133 fix(ingestion-service): skip tokenization for obs level ERROR
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/calculateTokenCost.unit.test.ts
Labels: bug, size:M, auto-merge

#9142 chore: move readme images to github assets
  README.md
Labels: size:S

#9134 feat(billing): invoice table in billing settings
  web/src/components/table/data-table-pagination.tsx
  web/src/components/table/data-table.tsx
  web/src/ee/features/billing/components/BillingInvoiceTable.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/ee/features/billing/components/BillingUsageChart.tsx
  web/src/ee/features/billing/components/useBillingInformation.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
Labels: size:XL

#9141 fix: fetch environment options from raw data
  packages/shared/src/server/repositories/environments.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/evals/components/inner-evaluator-form.tsx
  web/src/features/projects/server/projectsRouter.ts
  web/src/features/widgets/components/WidgetForm.tsx
  web/src/pages/project/[projectId]/dashboards/[dashboardId]/index.tsx
  web/src/pages/project/[projectId]/index.tsx
  web/src/pages/project/[projectId]/users.tsx
Labels: bug, size:M, auto-merge

#9150 chore: add debugging log for invalid start_time in batch exports
  packages/shared/src/server/repositories/observations_converters.ts
Labels: size:S, auto-merge

#9158 chore(cloud): remove eval count limit from hobby/free plan
  web/src/features/entitlements/constants/entitlements.ts
Labels: size:XS

#9162 fix(llm-completion): add transformations for providers requiring a user message
  packages/shared/src/server/llm/fetchLLMCompletion.ts
Labels: bug, size:S, auto-merge

#9184 chore: add sdk-api-spec bot
  .github/workflows/sdk-api-spec.yml
Labels: size:L

#9188 chore: switch docker compose cluster to bitnami legacy
  docker-compose.dev-redis-cluster.yml
Labels: lgtm, size:S

#9176 feat(api): GET /scores support for filtering by sessionId
  fern/apis/server/definition/score-v2.yml
  packages/shared/src/features/scores/interfaces/api/v2/endpoints.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/scores-api-v1.servertest.ts
  web/src/__tests__/async/scores-api-v2.servertest.ts
  web/src/features/public-api/server/scores.ts
  web/src/pages/api/public/v2/scores/index.ts
Labels: feat-scores, size:M, auto-merge

#9190 fix(trace-ui): don't render markdown if content too big
  pnpm-lock.yaml
  web/package.json
  web/src/components/trace/IOPreview.tsx
  web/src/components/ui/MarkdownJsonView.tsx
  web/src/components/ui/PrettyJsonView.tsx
  web/src/utils/constants.ts
Labels: bug, size:M, auto-merge

#9169 feat(billing): Rewrite Billing Service to Reduce Complexity and Minimize Data Drift Risks
  packages/shared/src/interfaces/cloudConfigSchema.ts
  web/src/app/api/billing/stripe-webhook/route.ts
  web/src/ee/features/billing/README.md
  web/src/ee/features/billing/components/BillingInvoiceTable.tsx
  web/src/ee/features/billing/components/BillingScheduleNotification.tsx
  web/src/ee/features/billing/components/BillingSwitchPlanDialog.tsx
  web/src/ee/features/billing/components/BillingUsageChart.tsx
  web/src/ee/features/billing/components/StripeCancellationButton.tsx
  web/src/ee/features/billing/components/StripeKeepPlanButton.tsx
  web/src/ee/features/billing/components/StripeSwitchPlanButton.tsx
  web/src/ee/features/billing/components/useBillingInformation.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
  web/src/ee/features/billing/server/stripeBillingService.ts
  web/src/ee/features/billing/server/stripeWebhookHandler.ts
  web/src/ee/features/billing/stripeClientReference.ts
  web/src/ee/features/billing/utils/stripeCatalogue.ts
  web/src/ee/features/billing/utils/stripeClientReference.ts
  web/src/ee/features/billing/utils/stripeExpand.ts
  web/src/ee/features/billing/utils/stripeIdempotencyKey.ts
  web/src/ee/features/billing/utils/stripeSubscriptionMetadata.ts
  web/src/features/entitlements/server/getPlan.ts
  web/src/server/api/trpc.ts
Labels: feat-api, size:XXL

#9195 chore: update sdk-api-spec bot
  .github/workflows/sdk-api-spec.yml
Labels: size:S

#9199 fix(billing): apply existing discounts to new subscription phase when updating via subscription schedule
  web/src/ee/features/billing/server/stripeBillingService.ts
Labels: bug, size:M

#9203 chore: update fern python generator
  fern/apis/server/generators.yml
  fern/fern.config.json
Labels: size:XS

#9053 feat(billing): new billing setup
  packages/shared/src/interfaces/cloudConfigSchema.ts
  pnpm-lock.yaml
  web/package.json
  web/src/app/api/billing/stripe-webhook/route.ts
  web/src/components/LocalIsoDate.tsx
  web/src/components/table/data-table-pagination.tsx
  web/src/components/table/data-table.tsx
  web/src/ee/features/billing/README.md
  web/src/ee/features/billing/components/BillingActionButtons.tsx
  web/src/ee/features/billing/components/BillingCurrentPlanLabel.tsx
  web/src/ee/features/billing/components/BillingInvoiceTable.tsx
  web/src/ee/features/billing/components/BillingScheduleNotification.tsx
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/ee/features/billing/components/BillingSwitchPlanDialog.tsx
  web/src/ee/features/billing/components/BillingUsageChart.tsx
  web/src/ee/features/billing/components/StripeCancellationButton.tsx
  web/src/ee/features/billing/components/StripeCustomerPortalButton.tsx
  web/src/ee/features/billing/components/StripeKeepPlanButton.tsx
  web/src/ee/features/billing/components/StripeSwitchPlanButton.tsx
  web/src/ee/features/billing/components/useBillingInformation.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
  web/src/ee/features/billing/server/stripeBillingService.ts
  web/src/ee/features/billing/server/stripeWebhookHandler.ts
  web/src/ee/features/billing/stripeClientReference.ts
  web/src/ee/features/billing/utils/stripeCatalogue.ts
  web/src/ee/features/billing/utils/stripeClientReference.ts
  web/src/ee/features/billing/utils/stripeExpand.ts
  web/src/ee/features/billing/utils/stripeIdempotencyKey.ts
  web/src/ee/features/billing/utils/stripeSubscriptionMetadata.ts
  web/src/features/entitlements/server/getPlan.ts
  web/src/server/api/trpc.ts
Labels: feat-api, size:XXL

#9194 feat: show last authentication method on login
  web/src/features/auth/components/AuthProviderButton.tsx
  web/src/pages/auth/sign-in.tsx
Labels: feat-auth, size:L, auto-merge

#9215 fix(experiment-form-ui): prevent event bubbling from embedded form submission handlers
  web/src/features/evals/components/inner-evaluator-form.tsx
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: bug, size:S, auto-merge

#9183 chore(single-trace): make tree a little more dense and allow click everywhere
  web/src/components/trace/SpanItem.tsx
  web/src/components/trace/TraceSearchList.tsx
  web/src/components/trace/TraceTree.tsx
Labels: ui, size:L, auto-merge

#9227 chore(sdk-api-spec-bot): auto add reviewer
  .github/workflows/sdk-api-spec.yml
Labels: size:S

#9228 fix(billing): automatically cancel and invoice stripe subscriptions when an org is deleted
  web/src/ee/features/billing/server/stripeBillingService.ts
  web/src/ee/features/billing/utils/stripeIdempotencyKey.ts
  web/src/features/organizations/server/organizationRouter.ts
Labels: bug, size:M, auto-merge

#9231 fix(trpc): show toast on trpc error to user
  web/src/utils/api.ts
Labels: bug, size:XS, auto-merge

#9191 fix: improve error message for CH memory issues on public API
  packages/shared/src/server/repositories/clickhouse.ts
  web/src/__tests__/async/repositories/clickhouse-resource-errors.servertest.ts
  web/src/__tests__/withMiddlewares.servertest.ts
  web/src/features/public-api/server/withMiddlewares.ts
  web/src/server/api/trpc.ts
Labels: bug, size:XL, auto-merge

#9239 style: Fix grammar of org invite email subject
  packages/shared/src/server/services/email/organizationInvitation/sendMembershipInvitationEmail.ts
Labels: bug, lgtm, size:XS, auto-merge

#9253 style(experiments-compare): sort scores alphabetically in cell
  web/src/features/datasets/components/DatasetAggregateTableCell.tsx
  web/src/features/scores/lib/aggregateScores.ts
Labels: feat-datasets, feat-scores, size:S, auto-merge

#9143 feat(score-configs): support mutability
  fern/apis/server/definition/score-configs.yml
  packages/shared/src/domain/score-configs.ts
  packages/shared/src/server/ingestion/validateAndInflateScore.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/score-configs.servertest.ts
  web/src/components/table/use-cases/score-configs.tsx
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/public-api/types/score-configs.ts
  web/src/features/score-configs/components/ArchiveScoreConfigButton.tsx
  web/src/features/score-configs/components/ScoreConfigDetails.tsx
  web/src/features/score-configs/components/ScoreConfigSettings.tsx
  web/src/features/score-configs/components/UpsertScoreConfigDialog.tsx
  web/src/features/score-configs/lib/upsertFormTypes.ts
  web/src/features/score-configs/lib/validateScoreConfigUpsertFormInput.ts
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/pages/api/public/score-configs/[configId].ts
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/server/api/routers/scoreConfigs.ts
  web/src/server/api/routers/scores.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-scores, size:XXL

#9235 feat(billing): Add option to add discount code to active subscriptions from settings menu
  web/src/ee/features/billing/components/BillingDiscountCodeButton.tsx
  web/src/ee/features/billing/components/BillingDiscountView.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
  web/src/ee/features/billing/server/stripeBillingService.ts
  web/src/ee/features/billing/utils/stripeIdempotencyKey.ts
Labels: size:L

#9265 chore: upgrade axios
  packages/shared/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#9288 chore: remove hosting of ..-in-the-middle packages
  .npmrc
Labels: size:XS, auto-merge

#9291 chore(cloud): limit org members to 2 on free plan to be in line with pricing/packaging
  web/src/ee/features/billing/components/BillingDiscountView.tsx
  web/src/features/entitlements/constants/entitlements.ts
Labels: size:XS

#9292 fix(billing): Add delimiting line to support emails
  web/src/features/support-chat/trpc/plainRouter.ts
Labels: size:XS, auto-merge

#9339 feat(ui): add search bar to members table
  web/src/features/rbac/components/MembersTable.tsx
  web/src/features/rbac/server/allMembersRoutes.ts
Labels: ui, size:M, auto-merge

#9218 feat(score-configs): support mutability
  fern/apis/server/definition/score-configs.yml
  packages/shared/scripts/seeder/seed-postgres.ts
  packages/shared/src/domain/score-configs.ts
  packages/shared/src/features/scoreConfigs/index.ts
  packages/shared/src/features/scoreConfigs/validation.ts
  packages/shared/src/features/scores/index.ts
  packages/shared/src/features/scores/interfaces/ingestion/validation.ts
  packages/shared/src/features/scores/scoreConfigTypes.ts
  packages/shared/src/index.ts
  packages/shared/src/server/ingestion/validateAndInflateScore.ts
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/score-configs.servertest.ts
  web/src/components/table/use-cases/score-configs.tsx
  web/src/features/annotation-queues/components/CreateOrEditAnnotationQueueButton.tsx
  web/src/features/annotation-queues/components/processors/SessionAnnotationProcessor.tsx
  web/src/features/annotation-queues/components/processors/TraceAnnotationProcessor.tsx
  web/src/features/annotation-queues/components/shared/AnnotationDrawerSection.tsx
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/public-api/types/score-configs.ts
  web/src/features/score-configs/components/ArchiveScoreConfigButton.tsx
  web/src/features/score-configs/components/ScoreConfigDetails.tsx
  web/src/features/score-configs/components/ScoreConfigSettings.tsx
  web/src/features/score-configs/components/UpsertScoreConfigDialog.tsx
  web/src/features/score-configs/lib/upsertFormTypes.ts
  web/src/features/score-configs/lib/validateScoreConfigUpsertFormInput.ts
  web/src/features/scores/components/AnnotateDrawerContent.tsx
  web/src/features/scores/hooks/useScoreMutations.ts
  web/src/features/scores/lib/getDefaultScoreData.ts
  web/src/pages/api/public/score-configs/[configId].ts
  web/src/pages/api/public/score-configs/index.ts
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/server/api/routers/scoreConfigs.ts
  web/src/server/api/routers/scores.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-scores, size:XXL, auto-merge

#9392 perf: avoid updates on session ingest
  worker/src/services/IngestionService/index.ts
Labels: size:XS, auto-merge

#9396 chore: update clickhouse writer batch size
  worker/src/env.ts
Labels: size:XS, auto-merge

#9399 fix(billing): Fix invoice table decimal display
  web/src/ee/features/billing/components/BillingInvoiceTable.tsx
Labels: bug, size:S

#9407 chore: do not upgrade to postgres 18
  docker-compose.build.yml
  docker-compose.dev-azure.yml
  docker-compose.dev-redis-cluster.yml
  docker-compose.dev.yml
  docker-compose.yml
Labels: size:S, auto-merge

#9410 feat(playground): add support for claude sonnet 4.5
  packages/shared/package.json
  packages/shared/src/server/llm/types.ts
  pnpm-lock.yaml
  web/package.json
  worker/src/constants/default-model-prices.json
Labels: feat-playground, size:S, auto-merge

#9431 feat(billing): write org.billingAnchor on organization create and subscription create and delete
  web/src/__tests__/billingCycleHelpers.servertest.ts
  web/src/ee/features/admin-api/server/organizations/index.ts
  web/src/ee/features/billing/server/stripeWebhookHandler.ts
  web/src/ee/features/usage-thresholds/services/setBillingCycleAnchor.ts
  web/src/ee/features/usage-thresholds/utils/billingCycleHelpers.ts
  web/src/features/organizations/server/organizationRouter.ts
Labels: feat-api, size:L

#9432 fix(otel): preferential parsing of environment key from span attributes
  packages/shared/src/server/otel/OtelIngestionProcessor.ts
Labels: bug, size:XS, auto-merge

#9433 feat(billing): Add clickhouse queries to retrieve usage
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
Labels: feat-scores, size:L

#9359 feat(auth): add support for Keycloak scope and ID token configuration
  web/src/env.mjs
  web/src/server/auth.ts
Labels: feat-auth, lgtm, size:S, auto-merge

#9438 feat(billing): add usage aggregation and threshold processing fns
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250930143723_change_billing_cycle_to_timestamptz/migration.sql
  packages/shared/prisma/migrations/20250930144939_add_billing_cycle_usage_state/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/interfaces/parseDbOrg.ts
  web/src/__tests__/billingCycleHelpers.servertest.ts
  web/src/__tests__/thresholdProcessing.servertest.ts
  web/src/__tests__/usageAggregation.servertest.ts
  web/src/ee/features/usage-thresholds/constants.ts
  web/src/ee/features/usage-thresholds/services/thresholdProcessing.ts
  web/src/ee/features/usage-thresholds/services/usageAggregation.ts
  web/src/ee/features/usage-thresholds/utils/billingCycleHelpers.ts
Labels: size:XXL

#9337 chore: upgrade turborepo to 2.5.8
  package.json
  packages/config-eslint/library.js
  packages/config-eslint/next.js
  packages/config-eslint/package.json
  pnpm-lock.yaml
  web/Dockerfile
  worker/Dockerfile
Labels: dependencies, size:S, auto-merge

#9445 fix: add current datetime to ai filter prompt
  web/src/features/natural-language-filters/server/router.ts
Labels: feat-api, size:S, auto-merge

#9447 feat(billing): add email templates for notifications
  packages/shared/src/server/index.ts
  packages/shared/src/server/services/email/usageThresholdSuspension/UsageThresholdSuspensionEmailTemplate.tsx
  packages/shared/src/server/services/email/usageThresholdSuspension/sendUsageThresholdSuspensionEmail.ts
  packages/shared/src/server/services/email/usageThresholdWarning/UsageThresholdWarningEmailTemplate.tsx
  packages/shared/src/server/services/email/usageThresholdWarning/sendUsageThresholdWarningEmail.ts
  worker/src/__tests__/thresholdProcessing.test.ts
  worker/src/ee/usageThresholds/thresholdProcessing.ts
  worker/src/ee/usageThresholds/usageAggregation.ts
Labels: size:XL
