Repository langfuse/langfuse, pull requests merged in 2025-01, with the labels that each got.

#4868 fix(ui): improve /trace/:id redirect when trace is accessed while still being processed
  web/src/pages/trace/[traceId].tsx
Labels: ui, size:M, auto-merge

#4871 chore: remove beta label from evaluation menu
  web/src/components/layouts/routes.tsx
Labels: size:XS, auto-merge

#4873 chore(cloud): disable deletion of traces via UI as it caused performance issues
  web/src/components/table/data-table-multi-select-actions/trace-table-multi-select-action.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/index.tsx
  web/src/features/entitlements/constants/entitlements.ts
Labels: ui, size:M

#4884 fix: use database upserts correctly
  web/src/__tests__/async/datasets-api.servertest.ts
  web/src/pages/api/public/dataset-items/index.ts
Labels: size:L, auto-merge

#4891 security: upgrade next
  ee/package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS

#4467 chore: remove postgres from ingestion merge
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: dependencies, size:L, auto-merge

#4872 fix(prompt-experiments): do not restrict to evalModelsOnly in order to use anthropic, bedrock, vertex
  web/src/components/ModelParameters/index.tsx
  web/src/ee/features/evals/components/template-form.tsx
  web/src/ee/features/experiments/components/CreateExperimentsForm.tsx
  web/src/ee/features/playground/page/playground.tsx
  web/src/features/public-api/components/CreateLLMApiKeyDialog.tsx
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:M, auto-merge

#4894 fix: use singular unit in clickhouse datediff for 23.x support
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  web/src/features/datasets/server/service.ts
  web/src/features/public-api/server/traces.ts
Labels: bug, size:M, auto-merge

#4896 chore: skip existence check for score deletion
  web/src/pages/api/public/scores/[scoreId].ts
Labels: size:M, auto-merge

#4898 fix(models): allow string tokenizer config
  web/src/features/models/validation.ts
Labels: size:XS

#4902 chore: move sessions, traces, comments router logs to logger
  web/src/server/api/routers/comments.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
Labels: size:M, auto-merge

#4905 fix: do not error on 403 by model provider for eval executions
  worker/src/queues/evalQueue.ts
Labels: size:S, auto-merge

#4907 chore(media): increase rate-limit to use ingestion budget
  web/src/pages/api/public/media/[mediaId].ts
  web/src/pages/api/public/media/index.ts
Labels: size:XS

#4909 security: upgrade nanoid
  ee/package.json
  package.json
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:S, auto-merge

#4910 security: prevent prototype pollution in dataset compare view
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
Labels: size:XS, auto-merge

#4911 feat: add CLICKHOUSE_DB support
  .env.prod.example
  packages/shared/clickhouse/scripts/down.sh
  packages/shared/clickhouse/scripts/drop.sh
  packages/shared/clickhouse/scripts/up.sh
  packages/shared/src/env.ts
  packages/shared/src/server/clickhouse/client.ts
  web/src/env.mjs
  web/src/features/datasets/server/service.ts
  worker/src/env.ts
Labels: size:M, auto-merge

#4928 fix: correctly export categorical scores for trace exports
  packages/shared/src/server/repositories/scores.ts
  web/src/features/datasets/server/service.ts
  web/src/pages/api/public/traces/[traceId].ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
  worker/src/__tests__/batch-export.test.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: bug, size:M, auto-merge

#4927 chore: reduce number of parsing iterations for observations and traces
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/traces_converters.ts
  packages/shared/src/utils/json.ts
  packages/shared/src/utils/zod.ts
  web/src/__tests__/zod.servertest.ts
Labels: size:M, auto-merge

#4931 feat(models): lastUsed column to full lookback
  web/src/components/table/use-cases/models.tsx
  web/src/server/api/routers/models.ts
Labels: size:XS

#4930 chore: add BUILD_ID to otel setup and exclude health from tracing
  web/Dockerfile
  web/src/env.mjs
  web/src/observability.config.ts
  worker/Dockerfile
  worker/src/env.ts
  worker/src/instrumentation.ts
Labels: size:S, auto-merge

#4932 chore(cost): add langchain-compatible price keys
  worker/src/constants/default-model-prices.json
Labels: feat-cost-tracking, size:M

#4926 perf: improve session all time search performance
  packages/shared/src/server/index.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  web/src/__tests__/async/sessions-ui-table.servertest.ts
  web/src/server/api/routers/sessions.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: feat-sessions, size:XL, auto-merge

#4943 feat: backup redis queues to postgres
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250108220721_add_queue_backup_table/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/pages/api/admin/bullmq/index.ts
Labels: size:L, auto-merge

#4947 fix(models-table): sorting across pages
  web/src/server/api/routers/models.ts
Labels: bug, size:M

#4946 fix: remove trace tracesession fk
  packages/shared/prisma/migrations/20250109083346_drop_trace_tracesession_fk/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/__tests__/async/sessions-ui-table.servertest.ts
  web/src/pages/api/public/sessions/[sessionId].ts
  web/src/server/api/routers/comments.ts
  web/src/server/api/routers/sessions.ts
Labels: lgtm, size:L, auto-merge

#4953 fix: sessions table id filter
  packages/shared/src/server/services/sessions-ui-table-service.ts
Labels: size:M

#4952 chore: accept projectId list which skips clickhouse reads during ingestion
  worker/src/env.ts
  worker/src/services/IngestionService/index.ts
Labels: size:S, auto-merge

#4954 fix: sessions metrics api performance
  packages/shared/src/server/services/sessions-ui-table-service.ts
Labels: size:S

#4955 chore: set created_at in ClickHouse based on min S3 timestamp
  packages/shared/src/server/services/StorageService.ts
  worker/src/queues/ingestionQueue.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
  worker/src/services/IngestionService/tests/calculateTokenCost.unit.test.ts
Labels: size:M, auto-merge

#4951 fix(pubic-api): observations and traces FINAL
  packages/shared/src/server/repositories/observations_converters.ts
  packages/shared/src/server/repositories/traces_converters.ts
  web/src/__tests__/async/observation-api.servertest.ts
  web/src/features/public-api/server/observations.ts
Labels: size:S

#4956 chore: enable clickhouse cluster mode by default
  web/src/env.mjs
Labels: size:XS, auto-merge

#4958 fix: fix trace exports
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: bug, size:XS, auto-merge

#4968 chore: daily instead of hourly telemetry
  web/src/features/telemetry/index.ts
Labels: size:XS

#4967 chore: stream clickhouse results to posthog to reduce memory consumption
  packages/shared/src/server/repositories/clickhouse.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  worker/src/ee/integrations/posthog/handlePostHogIntegrationProjectJob.ts
Labels: size:L, auto-merge

#4966 feat: script to replay missing events
  pnpm-lock.yaml
  worker/package.json
  worker/src/scripts/refill-ingestion-events.ts
Labels: dependencies, size:L, auto-merge

#4978 chore(cloud): improve ui of cloud region selection, remove login error notice
  web/src/features/auth/components/AuthCloudRegionSwitch.tsx
  web/src/pages/auth/sign-in.tsx
  web/src/pages/auth/sign-up.tsx
Labels: size:M, auto-merge

#4979 chore(ui): remove introducing orgs banner
  web/src/features/organizations/components/ProjectOverview.tsx
Labels: ui, size:M, auto-merge

#4980 fix(ui): docs menu item should open in new tab
  web/src/components/nav-main.tsx
Labels: ui, size:S, auto-merge

#4981 chore(ui): do not collapse chat messages on prompt view
  web/src/components/trace/IOPreview.tsx
  web/src/features/prompts/components/prompt-detail.tsx
Labels: ui, size:S, auto-merge

#4982 chore(ui): add descriptions to the setup onboarding flow
  web/src/features/setup/components/SetupPage.tsx
Labels: ui, size:M, auto-merge

#4983 feat(ui): add support dropdown menu to replace /support page
  web/src/__e2e__/auth.spec.ts
  web/src/components/Support.tsx
  web/src/components/layouts/layout.tsx
  web/src/components/layouts/routes.tsx
  web/src/components/nav/app-sidebar.tsx
  web/src/components/nav/nav-main.tsx
  web/src/components/nav/nav-user.tsx
  web/src/components/nav/sidebar-notifications.tsx
  web/src/components/nav/support-menu-dropdown.tsx
  web/src/features/feedback/component/FeedbackButton.tsx
  web/src/features/organizations/components/ProjectOverview.tsx
  web/src/features/public-api/components/QuickstartExamples.tsx
  web/src/features/support-chat/chat.tsx
  web/src/pages/support.tsx
Labels: size:L, auto-merge

#4984 chore(ui): improve button labels for playground and experiments on prompt view
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
  web/src/features/prompts/components/prompt-detail.tsx
Labels: ui, size:S, auto-merge

#4985 feat(annotation-queue): show "add to dataset" button on trace preview
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
Labels: feat-datasets, size:L, auto-merge

#4987 fix(ui): chatIsVisible rendering issues
  web/src/components/nav/support-menu-dropdown.tsx
  web/src/features/support-chat/chat.tsx
Labels: ui, size:XS, auto-merge

#4986 chore: remove old launch week notifications
  web/src/components/nav/sidebar-notifications.tsx
Labels: size:M, auto-merge

#4989 fix(ui): support menu forwardref error, memo list of options, keys for separators
  web/src/components/nav/nav-main.tsx
  web/src/components/nav/support-menu-dropdown.tsx
Labels: size:L, auto-merge

#4991 fix: telemetry error "invalid input syntax for type interval"
  web/src/features/telemetry/index.ts
Labels: size:XS

#4995 fix: fix session table sorting
  packages/shared/src/server/services/sessions-ui-table-service.ts
  web/src/__tests__/async/sessions-ui-table.servertest.ts
Labels: size:L, auto-merge

#4999 fix: drop dataset run item temp tables from all CH nodes
  web/src/features/datasets/server/service.ts
Labels: size:XS

#5001 fix: fail open on redis errors in ratelimitservice
  web/src/features/public-api/server/RateLimitService.ts
Labels: bug, size:XS, auto-merge

#5004 chore(models): update fern types startDate unit
  fern/apis/server/definition/commons.yml
  fern/apis/server/definition/models.yml
  fern/fern.config.json
  web/public/generated/api/openapi.yml
Labels: size:S

#5014 fix(fern-models): unit to optional commons.model
  fern/apis/server/definition/commons.yml
Labels: size:XS

#5013 fix: process status codes on eval execution errors
  packages/shared/src/errors/ApiError.ts
  worker/src/__tests__/evalService.test.ts
  worker/src/features/utilities.ts
Labels: bug, size:L, auto-merge

#5022 chore: upgrade bullmq to 5.34.10
  packages/shared/package.json
  pnpm-lock.yaml
  web/package.json
  worker/package.json
  worker/src/__tests__/redisConsumer.test.ts
Labels: dependencies, size:XS, auto-merge

#5024 feat(ui-tabels): Count of group selection on column visibility
  web/src/components/table/data-table-column-visibility-filter.tsx
Labels: ui, size:S, auto-merge

#5028 fix: correctly order sessions by time
  packages/shared/src/server/services/sessions-ui-table-service.ts
  web/src/__tests__/async/sessions-ui-table.servertest.ts
Labels: size:M, auto-merge

#5029 chore(ui-dashboard): save selected score graphs in the dashboard to `localStorage` (project-bound)
  web/src/components/table/use-cases/score-configs.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
Labels: feat-dashboard, size:S, auto-merge

#5037 chore: fallback to error.status for eval error handling
  worker/src/features/utilities.ts
Labels: size:XS, auto-merge

#5027 fix(ingestion): overwriting of observation level
  worker/src/services/IngestionService/index.ts
Labels: lgtm, size:XS

#5039 feat(trace-detail-ui): filter by minObservationlvl
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/index.tsx
  web/src/components/trace/lib/helpers.ts
  web/src/components/ui/select.tsx
Labels: ui, size:L

#5043 style(ui-tables): fix position of `No results.` text if table has no data
  web/src/components/table/data-table.tsx
Labels: ui, size:XS, auto-merge

#5044 feat(trace-tree-ui): add hint for hidden obs
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
  web/src/components/trace/lib/helpers.ts
Labels: size:M

#5045 fix(ui-annoation): bug when re-submitting score comments on categorical scores
  web/src/features/scores/components/AnnotateDrawerContent.tsx
Labels: bug, size:XS, auto-merge

#5041 chore: remove legacy v3-migration env variables
  .env.dev.legacy.example
  .github/workflows/pipeline.yml
  .gitignore
  docker-compose.yml
  packages/shared/src/env.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
  web/src/__tests__/events.servertest.ts
  web/src/__tests__/generations.servertest.ts
  web/src/__tests__/ingestion.servertest.ts
  web/src/__tests__/metrics-api.servertest.ts
  web/src/__tests__/prompts.v1.servertest.ts
  web/src/__tests__/prompts.v2.servertest.ts
  web/src/__tests__/scores.servertest.ts
  web/src/__tests__/server/api/routers/traces.servertest.ts
  web/src/__tests__/sessions.servertest.ts
  web/src/__tests__/spans.servertest.ts
  web/src/__tests__/tokenCost.servertest.ts
  web/src/__tests__/traces.servertest.ts
  web/src/env.mjs
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/pages/api/public/dataset-run-items.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/trpc.ts
  web/src/server/utils/checkClickhouseAccess.ts
  worker/src/ee/evaluation/evalService.ts
  worker/src/env.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:XXL

#5051 chore: add project_id to get clickhouse query ingestion
  worker/src/services/IngestionService/index.ts
Labels: size:XS, auto-merge

#5054 chore: correct data region
  web/src/features/auth/components/AuthCloudRegionSwitch.tsx
Labels: size:XS, auto-merge

#5055 chore: update architecture diagram
  CONTRIBUTING.md
Labels: size:M, auto-merge

#5063 chore: skip zod parse for json parsing
  packages/shared/src/utils/json.ts
  web/src/__tests__/zod.servertest.ts
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/server/traces.ts
Labels: size:M, auto-merge

#5066 fix(cloud): remove race condition check in metering cron job
  worker/src/ee/cloudUsageMetering/handleCloudUsageMeteringJob.ts
Labels: bug, size:M

#5068 chore: add cloud meter event trigger
  packages/shared/src/server/redis/cloudUsageMeteringQueue.ts
  worker/package.json
  worker/src/scripts/refill-billing-event.ts
Labels: size:M, auto-merge

#5072 fix: retry stripe in metering logic and meter again if error ocurred
  worker/src/ee/cloudUsageMetering/handleCloudUsageMeteringJob.ts
  worker/src/queues/cloudUsageMeteringQueue.ts
Labels: bug, size:M, auto-merge

#5074 fix: add race condition check to billing queue
  worker/src/ee/cloudUsageMetering/handleCloudUsageMeteringJob.ts
Labels: bug, size:M, auto-merge

#5076 fix: retry stripe apis
  worker/src/ee/cloudUsageMetering/handleCloudUsageMeteringJob.ts
Labels: size:S, auto-merge

#5077 fix: quickly recover from metering queue errors
  worker/src/queues/cloudUsageMeteringQueue.ts
Labels: size:S

#5069 chore: remove outdated postgres executions
  packages/shared/src/server/repositories/scores.ts
  web/src/ee/features/annotation-queues/server/annotationQueueItems.ts
  web/src/ee/features/annotation-queues/server/annotationQueues.ts
  web/src/ee/features/evals/server/router.ts
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/datasets/server/service.ts
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/pages/api/public/metrics/daily.ts
  web/src/pages/api/public/observations/[observationId].ts
  web/src/pages/api/public/observations/index.ts
  web/src/pages/api/public/scores/[scoreId].ts
  web/src/pages/api/public/scores/index.ts
  web/src/pages/api/public/sessions/[sessionId].ts
  web/src/pages/api/public/traces/[traceId].ts
  web/src/pages/api/public/traces/index.ts
  web/src/server/api/routers/comments.ts
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/generations/getAllQueries.ts
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/routers/users.ts
  web/src/server/utils/checkClickhouseAccess.ts
Labels: feat-datasets, feat-evals, feat-scores, feat-comments, feat-users, feat-sessions, size:XXL

#5073 feat(model): add support for o1 model costs
  CONTRIBUTING.md
  worker/src/constants/default-model-prices.json
Labels: lgtm, feat-cost-tracking, size:M

#5075 feat(cloud): snapshot usage metering to postgres db
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250116154613_add_billing_meter_backups/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/redis/meteringDataPostgresExportQueue.ts
  worker/src/app.ts
  worker/src/ee/meteringDataPostgresExport/handleMeteringDataPostgresExportJob.ts
  worker/src/env.ts
Labels: size:L

#5087 feat(model): add playground and eval support for `gemini-2.0-flash-exp`
  packages/shared/src/server/llm/types.ts
  worker/src/constants/default-model-prices.json
Labels: feat-evals, feat-playground, size:S

#4656 feat(datasets): upload dataset via csv import
  pnpm-lock.yaml
  web/next.config.mjs
  web/package.json
  web/src/components/ui/progress.tsx
  web/src/features/datasets/components/DatasetForm.tsx
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/ImportCard.tsx
  web/src/features/datasets/components/NewDatasetItemButton.tsx
  web/src/features/datasets/components/PreviewCsvImport.tsx
  web/src/features/datasets/components/UploadDatasetCsv.tsx
  web/src/features/datasets/components/UploadDatasetCsvButton.tsx
  web/src/features/datasets/lib/csvHelpers.ts
  web/src/features/datasets/lib/findDefaultColumn.ts
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
Labels: feat-datasets, size:XXL, auto-merge

#5091 feat(cloud): export billing meter backup to s3
  packages/shared/src/server/redis/coreDataS3ExportQueue.ts
  worker/src/queues/coreDataS3ExportQueue.ts
Labels: lgtm, size:XS, auto-merge

#5094 fix(ui): support menu button width
  web/src/components/nav/support-menu-dropdown.tsx
Labels: ui, size:XS, auto-merge

#5090 fix: update ordering for get traces calls to avoid stale results
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/server/traces.ts
Labels: size:M, auto-merge

#5096 chore(cloud): run analytics jobs daily
  packages/shared/src/server/redis/coreDataS3ExportQueue.ts
  packages/shared/src/server/redis/meteringDataPostgresExportQueue.ts
Labels: size:XS, auto-merge

#5102 fix: fix session ui table ordering
  packages/shared/src/server/services/sessions-ui-table-service.ts
Labels: ui, size:XS

#5103 fix: flaky session export test
  worker/src/__tests__/batch-export.test.ts
Labels: size:XS, auto-merge

#5105 fix: return 404 error instead of 500 for not found observations trpc …
  web/src/server/api/routers/observations.ts
Labels: bug, size:M

#5111 fix: correct the rate limiter header return types
  web/src/__tests__/rate-limit.servertest.ts
  web/src/features/public-api/server/RateLimitService.ts
Labels: size:M

#5114 fix: allow field overwrites with `null` in ingestion api
  web/src/__tests__/async/ingestion-api.servertest.ts
  web/src/__tests__/async/scores-api.servertest.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
  worker/src/services/IngestionService/utils.ts
Labels: bug, size:XL, auto-merge

#5117 fix(ingestion): allow nullish tokens_details in openai usage schema
  packages/shared/src/server/ingestion/types.ts
Labels: size:XS

#5120 fix(trace-view): show disabled jump to playground instead of hiding
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: size:S

#5122 fix(llm-api-keys): improve form dialog for bedrock
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:S

#5125 feat(onboarding): add GitHub star prompt with badge
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/pages/onboarding.tsx
Labels: ui, lgtm, size:M, auto-merge

#5127 revert: ask for github star during onboarding
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/pages/onboarding.tsx
Labels: size:M, auto-merge

#5123 chore: remove queryClickhouse toggles
  web/src/__tests__/async/dataset-service.servertest.ts
  web/src/components/layouts/ClickhouseAdminToggle.tsx
  web/src/components/layouts/layout.tsx
  web/src/components/session/index.tsx
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/index.tsx
  web/src/features/dashboard/components/ChartScores.tsx
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/ScoresTable.tsx
  web/src/features/dashboard/components/TracesBarListChart.tsx
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/components/UserChart.tsx
  web/src/features/dashboard/components/hooks.ts
  web/src/features/dashboard/components/score-analytics/CategoricalScoreChart.tsx
  web/src/features/dashboard/components/score-analytics/NumericScoreHistogram.tsx
  web/src/features/dashboard/components/score-analytics/NumericScoreTimeSeriesChart.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/datasets/components/DatasetCompareRunPeekView.tsx
  web/src/features/datasets/components/DatasetCompareRunsTable.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/datasets/server/service.ts
  web/src/features/prompts/components/prompts-table.tsx
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/features/scores/hooks/useIndividualScoreColumns.ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/index.tsx
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
  web/src/pages/project/[projectId]/users.tsx
  web/src/pages/project/[projectId]/users/[userId].tsx
  web/src/server/api/routers/comments.ts
  web/src/server/api/routers/generations/filterOptionsQuery.ts
  web/src/server/api/routers/generations/getAllQueries.ts
  web/src/server/api/routers/observations.ts
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/traces.ts
  web/src/server/api/routers/users.ts
  web/src/server/api/trpc.ts
Labels: feat-datasets, feat-dashboard, size:L, auto-merge

#5137 chore: remove postgres fallback for generations table calls
  packages/shared/src/server/queries/createGenerationsQuery.ts
  packages/shared/src/server/queries/index.ts
  web/src/server/api/routers/generations/db/getAllGenerationsSqlQuery.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: lgtm, size:L

#5139 chore(traces): remove unsued code pulling trace data from prisma [deprecated]
  packages/shared/src/server/queries/createTracesQuery.ts
  packages/shared/src/server/queries/index.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:L, auto-merge

#5143 feat: add support for DATABASE_ARGS config
  web/entrypoint.sh
  worker/entrypoint.sh
Labels: size:S, auto-merge

#5144 chore: reduce default write interval for CH queue to 1000
  worker/src/env.ts
Labels: size:XS, auto-merge

#5145 feat(dataset-runs): add product analytics events
  web/src/ee/features/experiments/components/CreateExperimentsForm.tsx
  web/src/features/datasets/components/DatasetAnalytics.tsx
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DeleteDatasetRunButton.tsx
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
Labels: feat-datasets, size:M, auto-merge

#5146 fix: observation table type alignment
  web/src/components/table/use-cases/generations.tsx
  web/src/components/table/use-cases/observations.tsx
Labels: size:XL, auto-merge

#5135 chore: skip re-builds for same tree hash
  .github/workflows/pipeline.yml
Labels: size:M, auto-merge

#5121 chore: remove legacy/batched ingestion pipeline code
  .env.prod.example
  package.json
  packages/shared/src/server/auth/gitHubEnterpriseProvider.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/ingestion/legacy/EventProcessor.ts
  packages/shared/src/server/ingestion/legacy/index.ts
  packages/shared/src/server/ingestion/processEventBatch.ts
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/redis/legacyIngestion.ts
  pnpm-lock.yaml
  turbo.json
  web/package.json
  web/scripts/model-match.ts
  web/src/__tests__/model-match.servertest.ts
  web/src/__tests__/usage.servertest.ts
  web/src/features/ingest/usage.ts
  web/src/pages/api/public/events.ts
  web/src/pages/api/public/generations.ts
  web/src/pages/api/public/ingestion.ts
  web/src/pages/api/public/scores/index.ts
  web/src/pages/api/public/spans.ts
  web/src/pages/api/public/traces/index.ts
  web/src/utils/types.ts
  worker/package.json
  worker/src/app.ts
  worker/src/env.ts
  worker/src/features/tokenisation/types.ts
  worker/src/queues/legacyIngestionQueue.ts
Labels: size:XXL, auto-merge

#5149 security: upgrade katex
  package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:XS, auto-merge

#5116 chore: allow skipping ingestion CH reads for projects created after cutoff date
  worker/src/env.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:M, auto-merge

#5124 chore(models-ui): move models into settings
  web/src/components/layouts/routes.tsx
  web/src/components/nav/sidebar-notifications.tsx
  web/src/components/table/use-cases/models.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/features/models/components/ModelSettings.tsx
  web/src/features/models/components/UpsertModelFormDrawer.tsx
  web/src/pages/project/[projectId]/models.tsx
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/models/[modelId].tsx
Labels: ui, size:L, auto-merge

#5151 fix: correctly upgrade katex
  web/package.json
Labels: dependencies, size:XS, auto-merge

#5150 feat(ee): add audit log view to project settings
  web/src/ee/features/audit-log-viewer/AuditLogsSettingsPage.tsx
  web/src/ee/features/audit-log-viewer/AuditLogsTable.tsx
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/rbac/constants/projectAccessRights.ts
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/server/api/root.ts
  web/src/server/api/routers/auditLogs.ts
Labels: feat-rbac, size:L, auto-merge

#5092 fix #5023 by using unix timestamp
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: bug, size:XS

#5118 fix: build shared package when dev is run
  turbo.json
Labels: bug, size:XS

#5156 chore: disable secondary queue
  worker/src/app.ts
  worker/src/env.ts
Labels: size:XS

#5153 feat(cloud): switch between available plans
  web/src/ee/features/billing/components/BillingSettings.tsx
  web/src/ee/features/billing/server/cloudBillingRouter.ts
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/ee/features/evals/server/router.ts
Labels: size:L, auto-merge

#5164 chore: use a distribution metric for langfuse.ingestion.count_files
  packages/shared/src/server/instrumentation/index.ts
  worker/src/queues/ingestionQueue.ts
Labels: size:S, auto-merge

#5163 feat(prompts): add diff view on new prompt version
  pnpm-lock.yaml
  web/package.json
  web/src/components/DiffViewer.tsx
  web/src/components/json-editor.tsx
  web/src/features/prompts/components/NewPromptForm/ReviewPromptDialog.tsx
  web/src/features/prompts/components/NewPromptForm/index.tsx
  web/src/features/prompts/components/PromptVersionDiffDialog.tsx
  web/src/features/prompts/components/prompt-history.tsx
Labels: feat-prompt-management, size:L

#5168 fix(diff-view-ui): add line breaks
  web/src/components/DiffViewer.tsx
Labels: ui, size:M

#5110 feat(prompts): support in UI prompt duplication
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/prompts/components/NewPromptForm/index.tsx
  web/src/features/prompts/components/duplicate-prompt.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/hooks/usePromptNameValidation.tsx
  web/src/features/prompts/server/actions/createPrompt.ts
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: feat-prompt-management, size:L, auto-merge

#5176 fix(prompt-diff-dialog): keep open on cursor leaving window
  web/src/features/prompts/components/PromptVersionDiffDialog.tsx
  web/src/features/prompts/components/prompt-history.tsx
Labels: bug, size:S

#5167 feat(llm-api-keys): allow for extra headers
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250122152102_add_llm_api_keys_extra_headers/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/server/index.ts
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  packages/shared/src/server/llm/utils.ts
  web/src/ee/features/evals/server/router.ts
  web/src/ee/features/playground/server/chatCompletionHandler.ts
  web/src/features/llm-api-key/server/router.ts
  web/src/features/llm-api-key/types.ts
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
  web/src/features/public-api/components/LLMApiKeyList.tsx
  worker/src/__tests__/experimentsService.test.ts
  worker/src/features/utilities.ts
Labels: feat-api, lgtm, size:L

#5178 feat: allow data retention configuration in project settings
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250123103200_add_retention_days_to_projects/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/features/auth/lib/projectRetentionSchema.ts
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/projects/components/ConfigureRetention.tsx
  web/src/features/projects/server/projectsRouter.ts
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/server/auth.ts
  web/types/next-auth.d.ts
Labels: lgtm, size:L, auto-merge

#5183 chore(cloud): add login issue banner, allow to open support chat
  web/src/features/auth/components/AuthCloudRegionSwitch.tsx
  web/src/pages/auth/sign-in.tsx
Labels: feat-auth, size:S, auto-merge

#5192 perf: add timestamp filter to observations join in eval queue
  packages/shared/src/server/repositories/traces.ts
Labels: size:XS, auto-merge

#5165 feat(traces): display number of all log kinds on trace table
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  packages/shared/src/tableDefinitions/tracesTable.ts
  web/src/__tests__/async/repositories/trace-repository.servertest.ts
  web/src/components/level-colors.tsx
  web/src/components/table/use-cases/traces.tsx
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: feat-log-levels, size:L, auto-merge

#5194 fix(comments-api): increase comment character limit to 3,000
  web/src/features/public-api/types/comments.ts
Labels: size:XS, auto-merge

#5193 feat(auth): Add AUTH_CUSTOM_ID_TOKEN environment variable
  .env.prod.example
  packages/shared/src/server/auth/customSsoProvider.ts
  web/src/ee/features/multi-tenant-sso/types.ts
  web/src/env.mjs
  web/src/server/auth.ts
Labels: feat-auth, lgtm, size:M, auto-merge

#5152 feat: add support for DATABASE_ARGS config (branch v2)
  web/entrypoint.sh
  worker/entrypoint.sh
Labels: size:S

#5196 feat(auth-v2): Add AUTH_CUSTOM_ID_TOKEN environment variable (#5193)
  .env.prod.example
  packages/shared/src/server/auth/customSsoProvider.ts
  web/src/ee/features/multi-tenant-sso/types.ts
  web/src/env.mjs
  web/src/server/auth.ts
Labels: size:M

#5106 feat: update prompt versions
  fern/apis/server/definition/prompt-version.yml
  fern/apis/server/definition/prompts.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/prompts.v2.servertest.ts
  web/src/features/prompts/server/actions/updatePrompts.ts
  web/src/features/prompts/server/handlers/promptNameHandler.ts
  web/src/features/prompts/server/handlers/promptVersionHandler.ts
  web/src/pages/api/public/v2/prompts/[promptName]/index.ts
  web/src/pages/api/public/v2/prompts/[promptName]/version/[promptVersion].ts
Labels: feat-prompt-management, lgtm, size:L, auto-merge

#5198 feat: add proxy support for oauth flows
  ee/package.json
  package.json
  packages/shared/package.json
  patches/next-auth@4.24.11.patch
  pnpm-lock.yaml
  web/package.json
  web/src/env.mjs
Labels: feat-auth, size:M, auto-merge

#5201 feat: add proxy support for oauth flows (#5198)
  ee/package.json
  package.json
  packages/shared/package.json
  patches/next-auth@4.24.11.patch
  pnpm-lock.yaml
  web/package.json
  web/src/env.mjs
Labels: feat-auth, size:M

#5202 fix(trace-timeline): first token label
  web/src/components/trace/TraceTimelineView.tsx
Labels: size:XS

#5208 fix(media-api): increase tx maxWait
  web/src/pages/api/public/media/index.ts
Labels: size:XS

#5210 fix(media): reduce tx level to RepeateableRead
  web/src/pages/api/public/media/index.ts
Labels: size:XS

#5211 fix(media): remove transactions
  web/src/pages/api/public/media/index.ts
Labels: lgtm, size:L

#5203 feat(auth): make checks and auth method configurable across SSO providers
  web/src/env.mjs
  web/src/server/auth.ts
Labels: feat-auth, lgtm, size:L, auto-merge

#5217 fix(openapi): upgrade openapi spec generator to correctly specify /ingestion 207 status code
  fern/apis/client/generators.yml
  fern/apis/server/definition/ingestion.yml
  fern/apis/server/definition/score.yml
  fern/apis/server/generators.yml
  web/public/generated/api-client/openapi.yml
  web/public/generated/api/openapi.yml
Labels: size:S

#5218 fix: align input/output and metadata parsing between GET /traces and /traces/:id
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/server/traces.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:L, auto-merge

#5221 chore: add client side logging for auth errors
  web/src/components/layouts/layout.tsx
Labels: lgtm, size:S, auto-merge

#5222 fix(media): base id gen on project ID + content hash
  web/src/pages/api/public/media/index.ts
Labels: size:S

#5219 feat(v2-auth): make checks and auth method configurable across SSO providers (#5203)
  web/src/env.mjs
  web/src/server/auth.ts
Labels: feat-auth, size:L

#5224 ci: run codespell also on v2 branch and prs
  .github/workflows/codespell.yml
Labels: size:XS

#5225 ci(v2): run codespell also on v2 branch and prs (#5224)
  .github/workflows/codespell.yml
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/ee/features/evals/server/router.ts
Labels: size:S

#5223 perf: use final for traces and observations api if no skip indexes are filtered
  packages/shared/src/server/queries/clickhouse-sql/clickhouse-filter.ts
  web/src/features/public-api/server/observations.ts
  web/src/features/public-api/server/traces.ts
Labels: size:M, auto-merge

#5229 fix(llm-api-key): extra header JSON parsing
  packages/shared/src/server/llm/utils.ts
Labels: size:XS

#5228 feat(ui): scroll deeplinked observation into view in trace tree
  web/src/components/trace/ObservationTree.tsx
Labels: ui, size:L, auto-merge

#5230 fix(ui): tabIndex on sign in page to skip password reset and cloud region info
  web/src/features/auth/components/AuthCloudRegionSwitch.tsx
  web/src/pages/auth/sign-in.tsx
Labels: ui, size:XS, auto-merge

#5231 fix(evals): remove system message
  web/src/ee/features/evals/server/router.ts
  worker/src/ee/evaluation/evalService.ts
Labels: size:S

#5209 fix(experiments): improve error handling
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  worker/src/__tests__/experimentsService.test.ts
  worker/src/ee/experiments/experimentService.ts
  worker/src/features/utilities.ts
  worker/src/queues/experimentQueue.ts
Labels: size:L, auto-merge

#5232 fix(cloud): fallback to clickhouse when usage meter cannot be fetched from stripe
  web/src/ee/features/billing/server/cloudBillingRouter.ts
Labels: size:L, auto-merge

#5233 fix: align naming of prompt patch docs
  fern/apis/server/definition/prompt-version.yml
Labels: size:XS, auto-merge

#5234 chore(datasets): increase csv upload limit to 10MB
  web/src/features/datasets/components/PreviewCsvImport.tsx
  web/src/features/datasets/components/UploadDatasetCsv.tsx
Labels: size:M, auto-merge

#5236 fix: use correct path for prompt versions api
  fern/apis/server/definition/prompt-version.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/prompts.v2.servertest.ts
  web/src/pages/api/public/v2/prompts/[promptName]/versions/[promptVersion].ts
Labels: bug, size:S, auto-merge
