Repository langfuse/langfuse, pull requests merged in 2025-03, with the labels that each got.

#5783 chore(ui): improve perf of sessions hasAny
  packages/shared/src/server/repositories/trace-sessions.ts
Labels: ui, feat-sessions, size:XS, auto-merge

#5791 chore(ui): remove redundant className props from splash screens
  web/src/components/onboarding/TracesOnboarding.tsx
  web/src/components/onboarding/UsersOnboarding.tsx
  web/src/components/ui/splash-screen.tsx
Labels: ui, size:S, auto-merge

#5792 fix(ui): overflow behaviour on trace timeline
  web/src/components/trace/TraceTimelineView.tsx
Labels: ui, size:XS, auto-merge

#5680 feat(ui): add settings deep links to cmd+k
  web/src/features/command-k-menu/CommandMenu.tsx
  web/src/pages/organization/[organizationId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/index.tsx
Labels: ui, size:L, auto-merge

#5793 fix(cloud): only active evals should count towards plan limit
  web/src/ee/features/evals/pages/evaluators.tsx
  web/src/ee/features/evals/server/router.ts
Labels: feat-evals, size:M, auto-merge

#5795 fix(ui): add playsInline attribute to video players
  web/src/components/ui/LangfuseMediaView.tsx
  web/src/components/ui/splash-screen.tsx
Labels: ui, size:XS, auto-merge

#5797 feat(datasets): add archive/unarchive functionality for dataset items on single item view
  web/src/pages/project/[projectId]/datasets/[datasetId]/items/[itemId].tsx
Labels: feat-datasets, size:M, auto-merge

#5798 feat(ui): add LLM connections settings page separate from api keys
  web/src/pages/project/[projectId]/settings/index.tsx
Labels: ui, size:M, auto-merge

#5804 chore: reduce log level for frequent logs
  worker/src/ee/evaluation/evalService.ts
  worker/src/services/IngestionService/index.ts
Labels: lgtm, feat-log-levels, size:XS, auto-merge

#5764 fix: use aes-gcm 12 bytes for IV
  packages/shared/src/encryption/index.ts
Labels: lgtm, size:XS, auto-merge

#5814 chore: upgrade fern and add java sdk example
  fern/apis/server/generators.yml
  fern/fern.config.json
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
Labels: dependencies, size:S, auto-merge

#5789 style(ui): trace view alignment improvements
  web/src/components/ItemBadge.tsx
  web/src/components/grouped-score-badge.tsx
  web/src/components/layouts/page-header.tsx
  web/src/components/trace/IOPreview.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/ObservationTree.tsx
  web/src/components/trace/TracePreview.tsx
Labels: ui, size:L, auto-merge

#5800 feat(datasets): copy items between datasets
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/features/datasets/components/NewDatasetItemForm.tsx
  web/src/features/datasets/components/NewDatasetItemFromExistingObject.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items/[itemId].tsx
Labels: feat-datasets, size:L, auto-merge

#5811 perf: reduce memory consumption on observations query
  web/src/features/public-api/server/observations.ts
Labels: size:S, auto-merge

#5816 feat(datasets): allow for deletion of dataset items in ui and public API
  fern/apis/server/definition/dataset-items.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/datasets-api.servertest.ts
  web/src/features/datasets/components/DatasetItemsTable.tsx
  web/src/features/datasets/components/NewDatasetItemFromExistingObject.tsx
  web/src/features/datasets/server/dataset-router.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/features/public-api/types/datasets.ts
  web/src/pages/api/public/dataset-items/[datasetItemId].ts
  web/src/pages/project/[projectId]/datasets/[datasetId]/items/[itemId].tsx
Labels: feat-datasets, size:L, auto-merge

#5830 fix(ui): overlapping status message on trace detail page
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
Labels: ui, size:M, auto-merge

#5834 feat(datasets): deletion of dataset runs via api
  fern/apis/server/definition/datasets.yml
  web/src/__tests__/async/datasets-api.servertest.ts
  web/src/features/public-api/types/datasets.ts
  web/src/pages/api/public/datasets/[name]/runs/[runName].ts
Labels: feat-datasets, size:L, auto-merge

#5838 chore: reduce default batch size of background migrations
  worker/src/backgroundMigrations/addGenerationsCostBackfill.ts
  worker/src/backgroundMigrations/migrateObservationsFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateScoresFromPostgresToClickhouse.ts
  worker/src/backgroundMigrations/migrateTracesFromPostgresToClickhouse.ts
Labels: size:S, auto-merge

#5841 feat: map pydantic logfire events to langfuse datamodel
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#5842 chore(api): update api reference and postman collection
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
Labels: size:M

#5828 feat(auth): add workos as idp
  .env.prod.example
  web/src/env.mjs
  web/src/pages/auth/sign-in.tsx
  web/src/server/auth.ts
Labels: feat-auth, size:M, auto-merge

#5824 Expose S3_CONCURRENT_READS and S3_CONCURRENT_WRITES as env variables
  packages/shared/src/env.ts
  packages/shared/src/server/services/StorageService.ts
  worker/src/env.ts
  worker/src/queues/ingestionQueue.ts
Labels: bug, feat-api, size:S

#5851 chore: add missing clickhouse writer metrics
  worker/src/services/ClickhouseWriter/index.ts
Labels: size:XS, auto-merge

#5863 chore: add name mappings to sync prisma schema with reality
  packages/shared/prisma/schema.prisma
Labels: size:S, auto-merge

#5866 feat(auth): add AUTH_WORKOS_ORGANIZATION_ID and AUTH_WORKOS_CONNECTION_ID envs
  .env.prod.example
  web/src/env.mjs
  web/src/pages/auth/sign-in.tsx
Labels: feat-auth, size:M, auto-merge

#5865 chore: consistent casing of README files
  ee/README.md
  packages/shared/src/server/instrumentation/README.md
  packages/shared/src/server/repositories/README.md
  web/src/features/prompts/README.md
Labels: size:M, auto-merge

#5872 feat(batch-exports): increase row limit to 1.5M
  worker/src/env.ts
Labels: size:XS

#5870 chore: fix contributingmd file
  CONTRIBUTING.md
  packages/shared/clickhouse/scripts/seed.ts
  packages/shared/package.json
  turbo.json
Labels: size:L, auto-merge

#5765 feat: add environment filter
  packages/shared/src/server/repositories/dashboards.ts
  packages/shared/src/server/repositories/environments.ts
  packages/shared/src/server/repositories/index.ts
  packages/shared/src/server/repositories/trace-sessions.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  packages/shared/src/tableDefinitions/mapDashboards.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapScoresTable.ts
  packages/shared/src/tableDefinitions/mapSessionTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  web/src/components/table/data-table-toolbar.tsx
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/dashboard/components/ChartScores.tsx
  web/src/features/dashboard/components/LatencyChart.tsx
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/components/ScoresTable.tsx
  web/src/features/dashboard/components/TracesBarListChart.tsx
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/components/UserChart.tsx
  web/src/features/dashboard/components/score-analytics/ScoreAnalytics.tsx
  web/src/features/projects/server/projectsRouter.ts
  web/src/hooks/use-environment-filter.tsx
  web/src/pages/project/[projectId]/index.tsx
  web/src/pages/project/[projectId]/users.tsx
Labels: feat-dashboard, size:XL, auto-merge

#5879 chore: fix contributingmd file
  CONTRIBUTING.md
Labels: size:S

#5880 chore: add noindex header
  web/next.config.mjs
Labels: size:M, auto-merge

#5877 feat: add environment column to UI tables
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/sessions-ui-table-service.ts
  packages/shared/src/server/services/traces-ui-table-service.ts
  web/src/components/table/use-cases/observations.tsx
  web/src/components/table/use-cases/scores.tsx
  web/src/components/table/use-cases/sessions.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/pages/project/[projectId]/users.tsx
  web/src/server/api/routers/sessions.ts
  web/src/server/api/routers/users.ts
Labels: ui, size:L, auto-merge

#5883 chore: return 200 instead of 207 as OTel success status
  web/src/pages/api/public/otel/v1/traces/index.ts
Labels: size:XS, auto-merge

#5889 fix: enforce ints on usageDetails
  packages/shared/src/server/ingestion/types.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
Labels: lgtm, size:M, auto-merge

#5895 feat: create new environment materialized views for quick lookups
  packages/shared/clickhouse/migrations/clustered/0009_add_project_environments.down.sql
  packages/shared/clickhouse/migrations/clustered/0009_add_project_environments.up.sql
  packages/shared/clickhouse/migrations/unclustered/0009_add_project_environments.down.sql
  packages/shared/clickhouse/migrations/unclustered/0009_add_project_environments.up.sql
  packages/shared/src/server/repositories/environments.ts
  web/src/__tests__/async/repositories/environment-repository.servertest.ts
  web/src/features/projects/server/projectsRouter.ts
Labels: size:L, auto-merge

#5900 chore: remove redundant readme files
  ee/Readme.md
  packages/shared/src/server/instrumentation/Readme.md
  packages/shared/src/server/repositories/Readme.md
  web/src/features/prompts/readme.md
Labels: size:M, auto-merge

#5858 feat: add CUSTOM_EMAIL_CLAIM, CUSTOM_NAME_CLAIM, CUSTOM_SUB_CLAIM for…
  packages/shared/src/env.ts
  packages/shared/src/server/auth/customSsoProvider.ts
Labels: feat-auth, size:S

#5907 chore: test processing of special characters in S3
  packages/shared/src/server/ingestion/types.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
Labels: size:L, auto-merge

#5912 feat(datasets): add multi-delete for dataset runs table
  web/src/features/datasets/components/DatasetRunsTable.tsx
  web/src/features/datasets/components/DeleteDatasetRunButton.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:L, auto-merge

#5914 fix: select/highlight text in Compare Dataset view
  pnpm-lock.yaml
  web/package.json
  web/src/components/layouts/peek-view.tsx
Labels: feat-datasets, size:XS, auto-merge

#5916 fix: ui config in localstorage should persist signing out
  web/src/components/layouts/layout.tsx
Labels: ui, size:XS, auto-merge

#5926 chore: add initial cursor rules
  .cursor/rules/authorization-and-rbac.mdc
  .cursor/rules/entitlements.mdc
  .cursor/rules/frontend-features.mdc
  .cursor/rules/public-api.mdc
Labels: feat-rbac, size:M, auto-merge

#5932 feat: add api key actions to auditlog table
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250310100328_add_api_key_to_audit_log/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/server/auth/types.ts
  web/src/ee/features/audit-log-viewer/AuditLogsTable.tsx
  web/src/features/audit-logs/auditLog.ts
  web/src/features/prompts/server/handlers/promptVersionHandler.ts
  web/src/features/prompts/server/handlers/promptsHandler.ts
  web/src/features/public-api/server/apiAuth.ts
  web/src/pages/api/public/comments/index.ts
  web/src/pages/api/public/dataset-items/[datasetItemId].ts
  web/src/pages/api/public/dataset-items/index.ts
  web/src/pages/api/public/datasets/[name]/runs/[runName].ts
  web/src/pages/api/public/models/[modelId]/index.ts
  web/src/pages/api/public/models/index.ts
  web/src/pages/api/public/score-configs/index.ts
  web/src/pages/api/public/scores/[scoreId].ts
  web/src/pages/api/public/v2/datasets/index.ts
  web/src/server/api/routers/auditLogs.ts
Labels: feat-api, size:L, auto-merge

#5931 feat: add trace delete API endpoints
  fern/apis/server/definition/trace.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/async/traces-api.servertest.ts
  web/src/features/public-api/types/traces.ts
  web/src/pages/api/public/traces/[traceId].ts
  web/src/pages/api/public/traces/index.ts
Labels: feat-api, size:L, auto-merge

#5934 chore: limit event id length
  packages/shared/src/server/ingestion/types.ts
Labels: lgtm, size:XS, auto-merge

#5938 fix: correctly extract jsonpath form observations for evals
  worker/src/ee/evaluation/evalService.ts
Labels: size:XS, auto-merge

#5937 perf(playground): memoizate ChatMessages
  web/src/components/ChatMessages/ChatMessageComponent.tsx
  web/src/components/ChatMessages/index.tsx
  web/src/ee/features/playground/page/context/index.tsx
Labels: feat-playground, size:L, auto-merge

#5940 security: upgrade axios to 1.8.2
  ee/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#5941 chore(cloud): add more data masking for posthog
  web/src/components/trace/IOPreview.tsx
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/features/datasets/components/EditDatasetItem.tsx
  web/src/features/datasets/components/NewDatasetItemForm.tsx
  web/src/pages/_app.tsx
Labels: size:M, auto-merge

#5943 feat(datasets): show run name on runitems table
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-datasets, size:M, auto-merge

#5944 fix: fix eval status on details page
  web/src/components/level-counts-display.tsx
  web/src/ee/features/evals/components/evaluator-detail.tsx
  web/src/ee/features/evals/components/evaluator-table.tsx
  web/src/ee/features/evals/server/router.ts
  web/src/ee/features/evals/utils/job-execution-utils.ts
Labels: feat-evals, size:L, auto-merge

#5946 docs: improve public api cursor rule
  .cursor/rules/public-api.mdc
Labels: size:XS, auto-merge

#5947 docs: add zod type strict() to public api cursor rule
  .cursor/rules/public-api.mdc
Labels: size:XS, auto-merge

#5948 fix: use readonly for the column definitions
  packages/shared/src/server/queries/clickhouse-sql/factory.ts
  packages/shared/src/server/queries/clickhouse-sql/orderby-factory.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/tableDefinitions/mapDashboards.ts
  packages/shared/src/tableDefinitions/mapObservationsTable.ts
  packages/shared/src/tableDefinitions/mapScoresTable.ts
  packages/shared/src/tableDefinitions/mapSessionTable.ts
  packages/shared/src/tableDefinitions/mapTracesTable.ts
  packages/shared/src/tableDefinitions/types.ts
Labels: size:M, auto-merge

#5939 chore: refactor score deletions into async queue
  packages/shared/src/features/batchExport/types.ts
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/redis/scoreDelete.ts
  packages/shared/src/server/repositories/eventLog.ts
  packages/shared/src/server/repositories/scores.ts
  web/src/__tests__/async/scores-api.servertest.ts
  web/src/__tests__/test-utils.ts
  web/src/pages/api/public/scores/[scoreId].ts
  web/src/server/api/routers/scores.ts
  worker/src/__tests__/batchAction.test.ts
  worker/src/__tests__/scoreDeletion.test.ts
  worker/src/app.ts
  worker/src/env.ts
  worker/src/features/batchAction/handleBatchActionJob.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
  worker/src/features/scores/processClickhouseScoreDelete.ts
  worker/src/queues/scoreDelete.ts
Labels: ui, feat-scores, size:L, auto-merge

#5956 feat: add score deletion to UI
  packages/shared/scripts/prepareClickhouse.ts
  packages/shared/src/features/batchAction/types.ts
  web/src/__tests__/async/scores-trpc.servertest.ts
  web/src/components/table/use-cases/scores.tsx
  web/src/server/api/routers/scores.ts
  web/src/server/api/routers/traces.ts
Labels: ui, feat-scores, size:L, auto-merge

#5950 chore: rename batch exports from generation to observation as table was generalized
  packages/shared/src/features/batchExport/types.ts
  web/src/components/table/use-cases/observations.tsx
  worker/src/__tests__/batchExport.test.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:M, auto-merge

#5961 chore: remove unnecessary comment
  web/src/components/table/use-cases/scores.tsx
Labels: size:XS, auto-merge

#5882 feat(prompts): add composability
  fern/apis/server/definition/prompts.yml
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250303144044_add_prompt_dependencies_table/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/features/prompts/parsePromptDependencyTags.ts
  packages/shared/src/index.ts
  packages/shared/src/server/services/PromptService.ts
  packages/shared/src/server/services/PromptService/index.ts
  packages/shared/src/server/services/PromptService/types.ts
  packages/shared/src/server/services/PromptService/utils.ts
  web/public/generated/api/openapi.yml
  web/src/__tests__/promptCache.servertest.ts
  web/src/__tests__/prompts.v2.servertest.ts
  web/src/__tests__/test-utils.ts
  web/src/components/editor/CodeMirrorEditor.tsx
  web/src/components/editor/PromptLinkingEditor.tsx
  web/src/components/trace/IOPreview.tsx
  web/src/components/ui/CodeJsonViewer.tsx
  web/src/features/notifications/ErrorNotification.tsx
  web/src/features/prompts/components/NewPromptForm/PromptChatMessages.tsx
  web/src/features/prompts/components/NewPromptForm/index.tsx
  web/src/features/prompts/components/NewPromptForm/validation.ts
  web/src/features/prompts/components/PromptSelectionDialog.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/components/renderContentWithPromptButtons.tsx
  web/src/features/prompts/server/actions/createPrompt.ts
  web/src/features/prompts/server/routers/promptRouter.ts
  web/src/features/prompts/server/utils/validation.ts
  web/src/utils/trpcErrorToast.tsx
Labels: feat-prompt-management, size:XXL

#5977 feat: extract logfire.msg as span and trace name
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#5983 fix(prompts): block label deletion if dependent exists
  packages/shared/src/features/prompts/parsePromptDependencyTags.ts
  web/src/features/prompts/components/renderContentWithPromptButtons.tsx
  web/src/features/prompts/server/actions/updatePrompts.ts
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: size:L, auto-merge

#5986 fix: search past observations with correct timestamp in evals
  worker/src/__tests__/evalService.test.ts
  worker/src/ee/evaluation/evalService.ts
Labels: bug, size:M, auto-merge

#5980 chore: reproduce clickhouse missing surrogate key error
  packages/shared/src/server/clickhouse/client.ts
  web/src/__tests__/async/ingestion-api.servertest.ts
Labels: size:M, auto-merge

#5996 feat(llm-connections): allow extraHeaders for azure
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:XS, auto-merge

#6000 fix(llm-connections): show bedrock error
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:XS

#5999 docs: add security notes to docker compose deployment
  docker-compose.yml
Labels: size:S, auto-merge

#5945 feat(api): add api for annotation queues
  fern/apis/server/definition/annotation-queues.yml
  web/public/generated/api/openapi.yml
  web/public/generated/postman/collection.json
  web/src/__tests__/annotation-queues-api.servertest.ts
  web/src/features/public-api/types/annotation-queues.ts
  web/src/pages/api/public/annotation-queues/[queueId].ts
  web/src/pages/api/public/annotation-queues/[queueId]/items/[itemId].ts
  web/src/pages/api/public/annotation-queues/[queueId]/items/index.ts
  web/src/pages/api/public/annotation-queues/index.ts
Labels: feat-api, lgtm, size:XXL, auto-merge

#6002 chore: reduce host port mapping for internal docker compose components
  docker-compose.yml
Labels: size:S, auto-merge

#5949 feat(ui): add csv/json export for scores table
  web/src/components/table/use-cases/scores.tsx
  worker/src/__tests__/batchAction.test.ts
  worker/src/__tests__/batchExport.test.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: ui, feat-scores, size:L, auto-merge

#6005 chore: remove unused prisma query builder
  web/src/__tests__/query-builder.servertest.ts
  web/src/features/dashboard/components/LatencyTables.tsx
  web/src/features/dashboard/components/ScoresTable.tsx
  web/src/features/dashboard/components/hooks.ts
  web/src/features/dashboard/lib/score-analytics-utils.ts
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/scores/adapters/index.ts
  web/src/server/api/services/queryBuilder.ts
  web/src/server/api/services/sqlInterface.ts
Labels: feat-dashboard, feat-scores, size:XL, auto-merge

#6014 fix(ui): hide jump to playground button when not entitled
  web/src/ee/features/playground/page/components/JumpToPlaygroundButton.tsx
Labels: ui, size:XS, auto-merge

#6003 feat(cost-tracking): add OpenAIResponseUsageSchema support
  fern/apis/server/definition/ingestion.yml
  packages/shared/src/server/ingestion/types.ts
  web/public/generated/api/openapi.yml
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: feat-cost-tracking, size:L, auto-merge

#6023 chore(docker-compose): bind services to localhost
  docker-compose.dev.yml
  docker-compose.yml
Labels: size:M

#5985 feat: Add environment tag on trace / observation detail views
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
Labels: lgtm, feat-tags, size:XS, auto-merge

#5994 fix(ui): fixed misalignment of badges in trace and observation details
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
Labels: ui, lgtm, size:M, auto-merge

#5995 fix(ui): fixed scrollbar appearing on IO preview mode switcher in trace and observation details
  web/src/components/trace/ObservationPreview.tsx
  web/src/components/trace/TracePreview.tsx
  web/src/components/ui/tabs-bar.tsx
  web/src/ee/features/evals/pages/evaluators.tsx
  web/src/ee/features/evals/pages/templates.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
  web/src/pages/project/[projectId]/evals/log.tsx
  web/src/pages/project/[projectId]/prompts/[promptName]/metrics.tsx
Labels: ui, lgtm, size:S, auto-merge

#6027 chore(ui): standardize the prompt variable list preview across views
  web/src/ee/features/evals/components/template-form.tsx
  web/src/features/prompts/components/NewPromptForm/index.tsx
  web/src/features/prompts/components/PromptVariableListPreview.tsx
  web/src/features/prompts/components/prompt-detail.tsx
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: ui, feat-prompt-management, size:M, auto-merge

#6031 chore(ui): alignment and sizing consitency in ObservationTree / GroupedScoreBadge
  web/src/components/grouped-score-badge.tsx
  web/src/components/trace/ObservationTree.tsx
Labels: ui, lgtm, size:S, auto-merge

#6037 chore(ui): remove padding of "Additional Input" field on OpenAiMessageView
  web/src/components/trace/IOPreview.tsx
Labels: ui, lgtm, size:S, auto-merge

#6050 fix(ui): make models detail page scrollable
  web/src/pages/project/[projectId]/settings/models/[modelId].tsx
Labels: ui, size:XS, auto-merge

#6020 chore: enable datadog profiling for web
  web/Dockerfile
  web/next.config.mjs
Labels: size:M, auto-merge

#6055 feat: support external S3 endpoint for batch exports
  packages/shared/src/server/services/StorageService.ts
  web/src/env.mjs
  worker/src/__tests__/storageservice.test.ts
  worker/src/env.ts
  worker/src/features/batchExport/handleBatchExportJob.ts
Labels: size:L, feat-multimodal-media, auto-merge

#6053 chore: better error message when uploading existing dataset item
  web/src/pages/api/public/dataset-items/index.ts
Labels: lgtm, size:XS, auto-merge

#6063 chore: pin node 20.18.3 to avoid issue introduced by 20.19.0
  .github/workflows/pipeline.yml
  .nvmrc
  web/Dockerfile
  worker/Dockerfile
Labels: dependencies, size:S, auto-merge

#6064 chore: lock dd-trace to 5.36.0
  web/Dockerfile
Labels: dependencies, size:XS, auto-merge

#6051 chore(ui): render min-level hint in a single line
  web/src/components/trace/ObservationTree.tsx
Labels: ui, size:S, auto-merge

#6070 fix(ui): padding on single prompt page
  web/src/features/prompts/components/prompt-detail.tsx
Labels: ui, size:XS, auto-merge

#6079 fix(peek-view): ensure `onClickRow` action smoothly keeps peek view open; onClick of select cells independent of peek view state
  web/src/components/table/data-table.tsx
  web/src/components/table/peek.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/features/table/components/TableSelectionManager.tsx
Labels: size:M, auto-merge

#6068 fix(ui): OpenAiMessageView now renders messages where content is an empty string instead of ignoring them
  web/src/components/trace/IOPreview.tsx
Labels: bug, ui, lgtm, size:M, auto-merge

#6022 feat: enable Atla integration
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  web/src/ee/features/playground/page/hooks/useModelParams.ts
  web/src/env.mjs
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: feat-playground, size:M

#6086 chore(ui): control for more specific onClick actions in table with peek view
  web/src/components/star-toggle.tsx
  web/src/components/table/peek.tsx
Labels: ui, size:XS, auto-merge

#6088 feat(llm-connections): add atla adapter
  packages/shared/src/server/llm/fetchLLMCompletion.ts
  packages/shared/src/server/llm/types.ts
  web/src/ee/features/playground/page/hooks/useModelParams.ts
  web/src/features/public-api/components/CreateLLMApiKeyForm.tsx
Labels: size:M, auto-merge

#6096 chore(tests): fully unpin node version from temporary fix #6063
  .github/workflows/pipeline.yml
  web/Dockerfile
  worker/Dockerfile
Labels: lgtm, size:S, auto-merge

#6099 chore(ui): improve padding in peek view header
  web/src/components/table/peek.tsx
Labels: ui, size:XS, auto-merge

#6107 fix(model-params-ui): duplicate model names leading to rendering issues
  web/src/components/ModelParameters/index.tsx
Labels: size:XS

#6100 feat(cloud): show status page menu item during incidents
  .env.prod.example
  web/src/components/layouts/routes.tsx
  web/src/components/nav/support-menu-dropdown.tsx
  web/src/env.mjs
  web/src/features/cloud-status-notification/components/CloudStatusMenu.tsx
  web/src/features/cloud-status-notification/server/cloud-status-router.ts
  web/src/features/cloud-status-notification/types.ts
  web/src/server/api/root.ts
Labels: size:L, auto-merge

#6108 chore: reduce cloudwatch flush frequency and batch metrics
  packages/shared/src/server/instrumentation/index.ts
Labels: size:M, auto-merge

#6115 chore(cloud): cache response of cloudStatus api for 5 minutes
  web/src/features/cloud-status-notification/components/CloudStatusMenu.tsx
Labels: size:XS, auto-merge

#6119 chore: add dd env variables to github build command
  .github/workflows/_deploy_ecs_service.yml
Labels: size:XS

#6117 chore(cloud): add posthog for projects and orgs
  web/src/pages/_app.tsx
Labels: size:M, auto-merge

#6124 fix(ui): dom nesting error `page-header`
  web/src/components/session/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/compare.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/index.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/items.tsx
  web/src/pages/project/[projectId]/datasets/[datasetId]/runs/[runId].tsx
Labels: ui, size:L, auto-merge

#6125 fix(ui): dom nesting error `data-table-row-height-switch`
  web/src/components/table/data-table-row-height-switch.tsx
  web/src/features/datasets/components/DatasetRunItemsTable.tsx
Labels: ui, size:XS, auto-merge

#6136 fix: safely parse big numbers in api responses
  packages/shared/package.json
  packages/shared/src/utils/json.ts
  pnpm-lock.yaml
  web/src/__tests__/async/ingestion-api.servertest.ts
  web/src/__tests__/zod.servertest.ts
Labels: size:M, auto-merge

#6138 feat: add additional input/output parsing for pydantic via OTel
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: size:M, auto-merge

#6139 chore(ui): clamp `page-header` title to one line
  web/src/components/layouts/page-header.tsx
Labels: ui, size:XS, auto-merge

#6140 chore: update .env.prod.example
  .env.prod.example
Labels: size:M, auto-merge

#6129 feat: cache LLM models in Redis
  .env.prod.example
  packages/shared/src/env.ts
  packages/shared/src/server/ingestion/modelMatch.ts
  web/src/env.mjs
  web/src/pages/api/public/models/[modelId]/index.ts
  worker/src/__tests__/modelMatch.test.ts
  worker/src/env.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: lgtm, size:L, auto-merge

#6147 chore: improve model match observability
  packages/shared/src/server/ingestion/modelMatch.ts
Labels: size:XS, auto-merge

#6145 fix(prompts): trim prompt names
  web/src/features/prompts/server/utils/validation.ts
Labels: size:XS, auto-merge

#6149 chore(ui): do not auto-generate new api keys in setup-tracing step
  web/src/features/public-api/components/QuickstartExamples.tsx
  web/src/features/setup/components/SetupPage.tsx
Labels: ui, size:L

#6148 perf: cache model not found
  packages/shared/src/server/ingestion/modelMatch.ts
  worker/src/__tests__/modelMatch.test.ts
Labels: lgtm, size:M, auto-merge

#6157 fix: fix model paring from redis
  packages/shared/src/env.ts
  packages/shared/src/server/index.ts
  worker/src/__tests__/modelMatch.test.ts
  worker/src/env.ts
  worker/src/services/IngestionService/index.ts
  worker/src/services/modelMatch.ts
Labels: bug, size:M, auto-merge

#6173 feat: extract top-level metadata from langfuse.metadata
  web/src/__tests__/server/api/otel/otelMapping.servertest.ts
  web/src/features/otel/server/index.ts
Labels: feat-metadata, size:L, auto-merge

#6141 chore: drop queue backup option in bullmq
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250321102240_drop_queue_backup_table/migration.sql
  packages/shared/prisma/schema.prisma
  web/src/pages/api/admin/bullmq/index.ts
Labels: lgtm, size:L, auto-merge

#6181 chore(prompts): add error logs for resolvePromptGraph
  packages/shared/src/server/services/PromptService/index.ts
Labels: size:L, auto-merge

#6184 fix(cost-tracking): null values in OpenAI usage schema
  fern/apis/server/definition/ingestion.yml
  packages/shared/src/server/ingestion/types.ts
  web/public/generated/api/openapi.yml
  worker/src/services/IngestionService/tests/IngestionService.integration.test.ts
Labels: size:M

#6186 chore(azure-llm-connection): update api-version to support reasoning models
  packages/shared/src/server/llm/fetchLLMCompletion.ts
Labels: size:XS

#6116 feat(evals): preview number of historic items to be evaluated
  packages/shared/src/server/index.ts
  packages/shared/src/server/services/datasets-ui-table-service.ts
  web/src/__tests__/async/datasets-ui-table.servertest.ts
  web/src/ee/features/evals/components/eval-form-descriptions.tsx
  web/src/ee/features/evals/components/evaluator-form.tsx
  web/src/ee/features/evals/components/execution-count-tooltip.tsx
  web/src/ee/features/evals/components/inner-evaluator-form.tsx
  web/src/ee/features/evals/utils/evaluator-form-utils.ts
  web/src/features/datasets/server/dataset-router.ts
Labels: feat-evals, size:XXL, auto-merge

#6187 fix(evaluator-templates): control editing state
  web/src/ee/features/evals/components/template-form.tsx
Labels: size:XS, auto-merge

#6189 fix(prompt-experiments): show form error if name is duplicated
  web/src/ee/features/experiments/components/CreateExperimentsForm.tsx
  web/src/ee/features/experiments/hooks/useExperimentNameValidation.tsx
  web/src/features/prompts/hooks/usePromptNameValidation.tsx
Labels: bug, size:M, auto-merge

#6143 feat: add blob storage integration
  packages/shared/prisma/generated/types.ts
  packages/shared/prisma/migrations/20250324110557_add_blobstorage_integration_table/migration.sql
  packages/shared/prisma/schema.prisma
  packages/shared/src/server/index.ts
  packages/shared/src/server/queues.ts
  packages/shared/src/server/redis/blobStorageIntegrationProcessingQueue.ts
  packages/shared/src/server/redis/blobStorageIntegrationQueue.ts
  packages/shared/src/server/redis/getQueue.ts
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
  packages/shared/src/server/services/StorageService.ts
  web/src/features/audit-logs/auditLog.ts
  web/src/features/blobstorage-integration/blobstorage-integration-router.ts
  web/src/features/blobstorage-integration/types.ts
  web/src/features/entitlements/constants/entitlements.ts
  web/src/features/posthog-analytics/usePostHogClientCapture.ts
  web/src/pages/project/[projectId]/settings/index.tsx
  web/src/pages/project/[projectId]/settings/integrations/blobstorage.tsx
  web/src/pages/project/[projectId]/settings/integrations/posthog.tsx
  web/src/server/api/root.ts
  worker/package.json
  worker/src/__tests__/blobStorageIntegrationProcessing.test.ts
  worker/src/app.ts
  worker/src/ee/integrations/blobstorage/handleBlobStorageIntegrationProjectJob.ts
  worker/src/ee/integrations/blobstorage/handleBlobStorageIntegrationSchedule.ts
  worker/src/env.ts
  worker/src/queues/blobStorageIntegrationQueue.ts
Labels: size:XXL, auto-merge

#6193 chore(cloud): remove rate limits from projects api as it is used by auth_check in sdks
  web/src/pages/api/public/projects.ts
Labels: feat-api, size:S, auto-merge

#6006 feat: add custom-query backend
  packages/shared/src/server/clickhouse/schema.ts
  packages/shared/src/server/queries/index.ts
  packages/shared/src/tableDefinitions/mapDashboards.ts
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/__tests__/queryBuilderDashboards.servertest.ts
  web/src/__tests__/queryBuilderSQLI.servertest.ts
  web/src/features/dashboard/components/TracesBarListChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/query/dashboardUiTableToViewMapping.ts
  web/src/features/query/dataModel.ts
  web/src/features/query/index.ts
  web/src/features/query/server/queryBuilder.ts
  web/src/features/query/types.ts
  web/src/pages/project/[projectId]/index.tsx
  web/src/pages/project/[projectId]/queryPlayground.tsx
Labels: feat-dashboard, size:XXL, auto-merge

#6207 chore: auto-close stale issues
  .github/workflows/stale_issues.yml
Labels: size:S, auto-merge

#6206 fix(evaluator-config): preview execution of dataset run items
  packages/shared/src/server/services/datasets-ui-table-service.ts
  web/src/__tests__/async/datasets-ui-table.servertest.ts
  web/src/ee/features/evals/components/eval-form-descriptions.tsx
  web/src/ee/features/evals/components/execution-count-tooltip.tsx
  web/src/ee/features/evals/components/inner-evaluator-form.tsx
  web/src/features/datasets/server/dataset-router.ts
  worker/src/ee/evaluation/evalService.ts
Labels: feat-datasets, feat-evals, size:M, auto-merge

#6209 chore(cloud): update blobstorage integration entitlement
  web/src/features/entitlements/constants/entitlements.ts
Labels: size:XS, auto-merge

#6208 fix: fix by model charts
  packages/shared/src/server/repositories/dashboards.ts
  web/src/__tests__/async/repositories/dashboard-repository.servertest.ts
  web/src/features/dashboard/components/ModelUsageChart.tsx
Labels: size:L, auto-merge

#6215 fix: use correct column name for filtering traces bar chart
  web/src/features/query/dashboardUiTableToViewMapping.ts
Labels: size:XS, auto-merge

#6224 chore: improve sentry setup
  web/sentry.client.config.ts
Labels: size:XS

#6226 chore: move the traces timeseries chart to new query builder
  packages/shared/src/server/clickhouse/client.ts
  web/src/__tests__/queryBuilder.servertest.ts
  web/src/features/dashboard/components/ModelCostTable.tsx
  web/src/features/dashboard/components/TracesTimeSeriesChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/pages/project/[projectId]/index.tsx
Labels: size:L, auto-merge

#6230 perf: reduce memory usage for posthog export via join_algo overwrite
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:S

#6233 chore: bump timeout for posthog export queries
  packages/shared/src/server/repositories/observations.ts
  packages/shared/src/server/repositories/scores.ts
  packages/shared/src/server/repositories/traces.ts
Labels: size:XS, auto-merge

#6234 chore: enable sentry tunnel
  web/next.config.mjs
Labels: size:XS

#6235 chore: remove warnings on missing domain timestamp
  worker/src/services/IngestionService/index.ts
Labels: size:S

#6242 security: upgrade next
  ee/package.json
  pnpm-lock.yaml
  web/package.json
Labels: dependencies, size:S, auto-merge

#6216 fix(trace-timeline): overflow and scroll behaviour
  web/src/components/grouped-score-badge.tsx
  web/src/components/trace/TraceTimelineView.tsx
Labels: bug, size:L, auto-merge

#6246 chore: add sentry remove dd env variables in build step
  .github/workflows/_deploy_ecs_service.yml
Labels: size:XS

#6245 chore: migrate observation by model charts to new query builder
  web/src/__tests__/queryBuilderDashboards.servertest.ts
  web/src/features/dashboard/components/ModelUsageChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/features/query/server/queryBuilder.ts
  web/src/pages/project/[projectId]/index.tsx
Labels: feat-dashboard, size:L, auto-merge

#6248 fix(ui): detail navigation on users > traces page
  web/src/components/table/peek.tsx
  web/src/components/table/use-cases/traces.tsx
  web/src/components/trace/TraceTimelineView.tsx
  web/src/components/trace/index.tsx
Labels: ui, size:S, auto-merge

#6249 chore: set sentry profiling sample rate
  web/sentry.client.config.ts
Labels: size:XS, auto-merge

#6250 feat(evals): allow adding custom value to tags filter
  web/src/ee/features/evals/components/inner-evaluator-form.tsx
  web/src/features/filters/components/filter-builder.tsx
Labels: feat-evals, size:XS, auto-merge

#6251 chore(eval-count-tooltip): refactor to extract business logic into hook
  web/src/ee/features/evals/components/execution-count-tooltip.tsx
  web/src/ee/features/evals/hooks/useEvalTargetCount.ts
Labels: feat-evals, size:M, auto-merge

#6255 chore: add logger for trpc route
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: size:M

#6256 fix(prompts): dollar sign in replaceValue breaking resolution
  packages/shared/src/server/services/PromptService/index.ts
Labels: bug, size:XS

#6258 fix(prompt-ui): state stuck in showing prompt diff cycle
  web/src/components/trace/TraceTimelineView.tsx
  web/src/features/prompts/components/PromptVersionDiffDialog.tsx
Labels: ui, size:XS, auto-merge

#6265 chore(docker-compose): update default LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT
  docker-compose.yml
Labels: size:XS

#6264 fix(prompts): handle resolvePromptGraph on deleted prompt
  web/src/features/prompts/server/routers/promptRouter.ts
Labels: bug, size:XS

#6266 chore: update list of allowed blob storage export intervals
  web/src/pages/project/[projectId]/settings/integrations/blobstorage.tsx
Labels: size:XS, auto-merge

#6262 chore: migrate user chart to new query builder
  web/src/__tests__/queryBuilderDashboards.servertest.ts
  web/src/features/dashboard/components/UserChart.tsx
  web/src/features/dashboard/server/dashboard-router.ts
  web/src/pages/project/[projectId]/index.tsx
Labels: feat-dashboard, size:L, auto-merge

#6268 fix(ui): trace timeline width calculation error
  web/src/components/trace/TraceTimelineView.tsx
Labels: bug, ui, size:XS, auto-merge
